nuxt/framework

packages/nuxi/src/commands/generate.ts
resolves https://github.com/nuxt/framework/issues/1562
This PR:
1. updates the `execa` command (it doesn't take arguments in the first part) 
1. writes types and closes out the nuxt instance before passing on the command
1. sets `_export: true` before writing types (as otherwise will fall foul of https://github.com/nuxt/framework/blob/46f858dd82cfe237d66b932423a5c784f9533f2f/packages/bridge/src/nitro.ts#L14-L16
=> fix(nuxi): generate types with `nuxi generate`

packages/nuxt3/src/components/module.ts
This PR ensures `components.d.ts` isn't added to `nuxt.d.ts` unless the file has actually been generated. It should just ensure the file remains clean (as there seem to be no negative consequences to adding nonexistent refs other than the squiggly red line).
=> fix(nuxt3): only add ref if types were generated

packages/nuxt3/src/pages/module.ts
resolves #1602
This PR adds `vue-router` types when the pages module is being used.
=> fix(nuxt3): add `vue-router` types when used

packages/bridge/src/runtime/app.plugin.mjs
resolves https://github.com/nuxt/framework/issues/1589
resolves #967
context: https://github.com/nuxt/framework/discussions/964#discussioncomment-1471713
This PR enables accessing injected properties within Bridge directly via `useNuxtApp()` to decrease the difference between Nuxt 2/3.
Example:
```ts
const { $myInjectedProperty } = useNuxtApp()
```
=> feat!(bridge): allow accessing injections from `useNuxtApp`

packages/nuxt3/src/app/nuxt.ts
https://github.com/antfu/unocss/issues/27
For example, in some cases, we might be relying on module side-effect in a plugin but does not have the explicit `default export`, this PR mocked those plugins to provide a noop function to avoid the undefined error.
```ts
// plugins/foo.js
import 'winid.css'
```
=> fix(nuxt3): allows plugins without default export

packages/nuxt3/src/app/legacy.ts
resolves #1587
This PR aims to provide compatible APIs for legacy modules that rely on certain flags from [the Nuxt context](https://nuxtjs.org/docs/2.x/internals-glossary/context).
=> fix(nuxt3): enable legacy access to $config and static flags

packages/bridge/src/vite/vite.ts, packages/vite/src/vite.ts
partly solves #1622
resolves #966
This PR removes some unused vite aliases which conflict with directory names when present (`/app` and `/build`). I can't find any indication these are used but please correct me if I'm wrong.
I've removed `~` and `@` too as these should be defined in `nuxt.options.alias` but if this was a workaround or I have misunderstood the purpose of this please do let me know (cc @pi0).
It also fixes the warmup command for vite. (Previously this was actually not doing anything as there was no route resolved for it.)
=> fix(vite): remove conflicting vite aliases

packages/kit/src/config/schema/_common.ts, packages/nuxt3/src/components/module.ts
Context: #243
This resolves a todo item by resolving more than just `.vue` files in components directory, as well as adding `.jsx` to valid extensions. There may be a reason this wasn't implemented yet however? - cc: @pi0.
=> fix(nuxt3): use nuxt extensions for component discovery

packages/nuxi/src/utils/engines.ts
closes #1642
Failed to handle dynamic import properly in https://github.com/nuxt/framework/pull/1598
=> fix(nuxi): satisfies isn't always default export

packages/vite/src/dev-bundler.ts
resolves #1380
If there is a `srcDir`, vite fully resolves paths outside of it (e.g. to node_modules), which are expressed as `/@fs/C:/my/path` - but we weren't removing the slash before the drive letter. This PR handles it.
related: https://github.com/nuxt/framework/pull/1646
=> fix(vite): normalize full windows paths

docs/docus.config.ts
Updated Algolia API keys, cannot check locally so far. Running into this error locally:
=> chore(docs): update algolia api key

packages/bridge/src/vite/vite.ts, packages/vite/src/vite.ts, test/fixtures/bridge/tsconfig.json
When we have `tsconfig.json` in the project and run `nuxi generate` in a clean workspace, it will fail to find `.nuxt/tsconfig.json`. This also appends on `nuxi generate` because this is triggered during loading Nuxt and before we write the types.
This PR bring up a failed test, and disabled the vite's tsconfig.json resolving. Currently wait for a bug fix on Vite's side https://github.com/vitejs/vite/pull/5538
=> fix(vite, bridge): avoid vite resolving `tsconfig.json`

packages/vite/src/dev-bundler.ts
See https://github.com/nuxt/framework/issues/940#issuecomment-960937200
The current error message when loading externals is:
```
(node:31884) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
Unexpected token 'export'
at wrapSafe (internal/modules/cjs/loader.js:1001:16)  
at Module._compile (internal/modules/cjs/loader.js:1049:27)  
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)  
at Module.load (internal/modules/cjs/loader.js:950:32)  
at Function.Module._load (internal/modules/cjs/loader.js:790:14)  
at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)  
at ModuleJob.run (internal/modules/esm/module_job.js:169:25)  
at …
```
=> fix(vite): expose underlying import errors

packages/bridge/src/vite/module.ts, test/fixtures/bridge/nuxt.config.ts
Currently, even if we enable `bridge.vite: true`, it still runs webpack on build unless `vite.build: true` is set. Which could be confusing. This PR flips the default by making the vite build opt-out instead of opt-in.
=> fix(bridge): enable vite build by default

packages/bridge/src/vite/client.ts, packages/vite/src/client.ts, packages/vite/src/plugins/dev-ssr-css.ts
Currently we have the css entries in the manifest and injected as <link ref="stylesheet"> by the renderer. The problem here is that during dev, vite's css are actually a JS module that controls a <style> for HMR. This makes client as duplicated of styles
For example:
Since the style from <link> can't be changed without a full page reload. This makes the old style persist and potentially conflict with the updated ones.
This PR makes the dev css module swap the `<link>` version with the same id to prevent duplication.
=> fix(vite): swap `<link>` style on dev ssr

packages/vite/src/plugins/dev-ssr-css.ts
resolves #1731 
querySelectorAll returns a NodeList, which we can iterate over.
=> fix(vite): use `forEach` on NodeList not Element

packages/vite/src/plugins/dev-ssr-css.ts
#1731 
Potentially fixes an bug introduced here:
https://github.com/nuxt/framework/pull/1712/files#diff-3849e94b5e97edc9444890d8800209cb730a3ac9c0e7004ee9d85d2c2dad12d5R21
Where `document.querySelector(...).forEach(...)` should be `document.querySelectorAll(...).forEach(...)`
=> Fix(vite) use querySelectorAll instead of querySelector for dev-ssr-css

packages/bridge/src/auto-imports.ts, packages/bridge/test/auto-imports.test.ts, packages/nuxt3/src/auto-imports/imports.ts, packages/nuxt3/test/auto-imports.test.ts
resolves #1706
This PR adds some missing auto-imports in Nuxt 3. (We may want to tweak this list further - please suggest away - as a lot of the more technical ones probably don't need to be auto-imported.) It also disables auto imports in Nuxt Bridge that aren't supported by the Vue 2 Composition API. And it adds tests so we will know in future if there is a new composable introduced that we should add to the list.
=> fix(nuxt3): add missing auto imports

packages/bridge/src/vite/plugins/default-export.ts
https://github.com/posva/pinia/issues/767
In `@pinia/nuxt`, it exports like this:
```ts
export { PiniaNuxtPlugin as default };
```
which causing
=> fix(bridge): default export detection

docs/content/1.getting-started/4.bridge-composition-api.md, packages/bridge/src/auto-imports.ts, packages/bridge/src/runtime/composables.ts
resolves #1689
This PR is a better replacement for the `useMeta` provided by `@nuxtjs/composition-api`. As much as possible it tries to follow the pattern of Nuxt 2 `vue-meta`, except that it also accepts reactive sources, which it watches.
=> feat(bridge): add `useNuxt2Meta()` composable

packages/webpack/src/utils/postcss.ts
Remove default value on loaderConfig, so that we can fall back to search postcss config file if not postcss config is configured.
=> fix(webpack): detect postcss config and show warning

packages/nuxi/src/utils/prepare.ts
see #1822
some issues will be thrown up by `vue-tsc` that are somewhat outside our control, such as:
```
nitro/dist/index.d.ts:14:21 - error TS7016: Could not find a declaration file for module 'fs-extra'. '/node_modules/fs-extra/lib/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/fs-extra` if it exists or add a new declaration (.d.ts) file containing `declare module 'fs-extra';`
import fsExtra from 'fs-extra';
~~~~~~~~~~
listhen/dist/index.d.ts:3:35 - error TS7016: Could not find a declaration file for module 'selfsigned'. '/node_modules/selfsigned/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/selfsigned` if it exists or add a new declaration (.d.ts) file containing `declare module 'selfsigned';`
import { SelfsignedOptions } from 'selfsigned'; …
```
=> fix(nuxi): default to skipping lib check

packages/nuxi/src/utils/prepare.ts
should probably have been included in https://github.com/nuxt/framework/pull/1824 🤦 
see #1822
This PR covers the following errors that would be thrown up by a TS lib-check:
```
node_modules/pathe/dist/index.d.ts:1:8 - error TS1259: Module '"path"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
1 import path from 'path';
~~~~
node_modules/@types/node/path.d.ts:167:5
167     export = path;
~~~~~~~~~~~~~~
This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
node_modules/rollup-plugin-visualizer/dist/plugin/index.d.ts:2:8 - error TS1259: Module '"/node_modules/open/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
2 import opn from "open";
~~~ …
```
=> fix(nuxi): set `allowSyntheticDefaultImports`

packages/bridge/src/vite/client.ts, packages/vite/src/client.ts
Resolves #1821, Resolves #1713 Resolves #1006
Related https://github.com/vitejs/vite/issues/5616
Remove `global` to `globalThis` replacements from vite. 
Alternatives to bring the backward compatibility back:
- Polyfill `process` and `global` in `globalThis`
- Use replacement with better regex
=> fix(vite): remove `global` replacement

docs/content/2.concepts/3.typescript.md
resolves #1819
This adds a line about how to check types manually. There are currently some issues thrown up by `vue-tsc` out of the box which I will take on separately.
=> docs: add brief note about how to check types manually

docs/content/3.docs/1.usage/3.meta-tags.md, examples/use-meta/app.vue, packages/nuxt3/src/meta/runtime/components.ts
resolves #1652
In our docs we give an example of `<Head lang="en-GB" />`, which currently doesn't work as vueuse/head doesn't process headAttrs specifically. This PR fixes this by redirecting any props passed to `<Head>` to `htmlAttrs` instead.
We could alternatively create a `<Html>` element but this would leave `<Head>` without purpose except to visually wrap other meta components.
=> feat: add `<Html>` meta component

test/fixtures/bridge/package.json, yarn.lock
…ixture
resolve #1848
I think it's due to the `hoistingLimits` we had in the fixture so the older `std-env` from Nuxt 2 has been hoisted locally. Explicitly adding it solves the problem.
=> chore: explicitly include `std-env` as dep for bridge fixture

packages/bridge/src/app.ts, packages/bridge/src/nitro.ts, test/fixtures/bridge/package.json, test/presets/_tests.mjs, yarn.lock
#1862
Fixing related issue mentioned in #1862. With nuxt 2, we were adding a polyfill for `fetch` (browser and server) but now all browsers (except our friend IE) support it so doesn't make sense to have it. This fixes only usage of `global.` in nuxt 2
=> fix(bridge): disable legacy fetch polyfills

.github/ISSUE_TEMPLATE/bug-report-bridge.yml, .github/ISSUE_TEMPLATE/bug-report-nuxt3.yml
Maybe we should even change the existing issue to this label in batch?
=> chore: use `triage:bug` label in issue template

docs/content/3.docs/1.usage/1.data-fetching.md
https://github.com/nuxt/framework/discussions/1915#discussioncomment-1644298
The [docs for data fetching](https://v3.nuxtjs.org/docs/usage/data-fetching) mention you can use `useAsyncData()` / `useFetch()` in plugins.
Apparently you can't, by design.
=> docs: remove mention of plugins from data fetching

packages/nuxi/src/commands/prepare.ts
resolves #1912
We are clearing buildDir in build/dev commands but we also need to do this for prepare.
=> fix(nuxi): create buildDir before writing types

docs/content/1.getting-started/3.bridge.md, packages/bridge/src/app.ts
resolves https://github.com/nuxt/framework/issues/1831, resolves #1130
Context: https://github.com/nuxt/framework/pull/1861. This PR removes any rewriting of `vue` import (which would otherwise be circular).
Together with adding the following to `~~/tsconfig.json`, type inference is working for me with Volar:
```json
{
"extends": "./.nuxt/tsconfig.json",
"vueCompilerOptions": {
"experimentalCompatMode": 2,
}
}
```
Note that Volar doesn't seem to pick this up if it's added to `.nuxt/tsconfig.json`.
=> fix(bridge): ensure `vue` ts alias points to original vue

packages/nuxt3/src/pages/module.ts, packages/nuxt3/src/pages/runtime/root.vue
resolves #1893
resolves #1344
Context is #750. Even with pages module enabled (which handles suspensible lIt seems we need a top-level `<Suspense>` barrier outside to cover await within `app` and layouts.
=> fix(nuxt3): enable app-level `<suspense>` with pages module

docs/content/3.docs/1.usage/1.data-fetching.md, packages/nuxt3/src/app/composables/asyncData.ts
resolves #1931
This adds the necessary checks to allow use of `useAsyncData` and `useFetch` within a plugin. Note that `lazy: true` has no effect in this case (and probably also doesn't make sense as the plugin runs on app initialisation rather than on component load)...
=> fix(nuxt3): enable `useAsyncData` and `useFetch` usage within plugins

packages/nitro/src/rollup/plugins/externals.ts
Some packages don't have a `package.json` file in their root. For example, Prisma has the package.json in `.prisma/client/package.json` and not under `.prisma`. This leads to the following problem at the end of `nuxt generate`
```
Nuxt Fatal Error                                                                                               │
│                                                                                                                    │
│   Error: ENOENT: no such file or directory, stat 'D:\Programming\JabRefOnline\node_modules\.prisma\package.json' 
```
This is fixed by silently ignore those packages (for prisma this is not a problem as `.prisma/client` is also imported, and thus the `package.json` file is still copied).
I wasn't sure about the coding style since …
=> fix(nitro): skip non existing externals

packages/vite/src/server.ts
Co-authored-by: Ben <bencodezen@users.noreply.github.com>
Found during pairing with @bencodezen 🙌
To reproduce the bug (Vite):
```html
<script setup lang="ts">
import format from 'date-fns/format'
const date = format(new Date(), 'yyyy/MM/dd')
</script>
<template>
<div>
{{ date }}
</div>
</template>
```
which will cause the error of `export` is not a valid syntax. Searching down, the root cause is that the internal module of `date-fns` been externalized but in a `.js` format of ESM in `server.mjs`
This PR adds the conversion to externalize modules under `/esm/` which I believe is a common pattern (`date-fns` is using is at least).
https://unpkg.com/browse/date-fns@2.25.0/esm/_lib/protectedTokens/index.js
=> fix(vite): external modules under`/esm/` pattern

packages/nuxi/src/utils/prepare.ts
This PR fixes an issue with bridge (where there are no nuxt typescript options):
```
❯ yarn nuxi prepare test/fixtures/bridge
Nuxt CLI v3.0.0
ERROR  Cannot read property 'strict' of undefined
at writeTypes (packages/nuxi/src/utils/prepare.ts:17:39)
at Object.invoke (packages/nuxi/src/commands/prepare.ts:21:35)
at async _main (packages/nuxi/src/index.ts:40:7)
```
`<joke>` Ironically this issue would have been avoided if strict were `true` .... `</joke>`
=> fix(nuxi): handle missing typescript options in build

packages/bridge/src/nitro.ts, packages/nuxi/src/commands/prepare.ts
resolves #1946
This sets `dev` when running `prepare` to avoid the build-time generate check in the bridge module setup.
I would also consider removing this check entirely.
=> fix(nuxi): ignore static check with `prepare` command

packages/kit/src/module/container.ts, packages/kit/src/module/utils.ts
ref: #1740, #1965
- Allow chaining routes when using kit's legacy ModuleContainer 
- Separate `extendRoutes` and `extendPages` implementations
Caveats: For Nuxt3, chaining is still not supported anymore even when using legacy ModuleContainer (A warning will be emitted to show when skipping)
=> fix(kit): support chainable `extendRoutes` in container

packages/bridge/src/runtime/app.ts, packages/bridge/src/runtime/capi.legacy.plugin.mjs, packages/bridge/src/runtime/nitro-bridge.server.mjs, packages/nuxt3/src/meta/runtime/lib/vue-meta.plugin.ts, packages/nuxt3/src/meta/runtime/lib/vueuse-head.plugin.ts, test/fixtures/bridge/plugins/setup.js
Improve the typing information for `defineNuxtPlugin`. Before this, `nuxtApp` was of type any.
Also renamed parameter `nuxt => nuxtApp` for consistency.
=> chore(bridge): Improve typing of defineNuxtPlugin function

packages/nuxi/src/utils/prepare.ts
#1920
Currently, the Volar support on Bridge is still broken. I think the root cause is that Volar will use the types from `@vue/runtime-core` to resolve the types but we are forced to alias it. 
I can confirm locally that removing the selected items will make it work.
Repro: 
- https://github.com/antfu/vitesse-nuxt-bridge
- https://github.com/nuxt/modules
=> fix(bridge): exclude bridge alias types to support Volar

packages/nuxt3/src/meta/runtime/components.ts
#2029
If we have multiple meta tags with the same name (e.g. `<meta name="keywords" content="foo"> and <meta name="keywords" content="bar">`) then @vueuse/head will just keep the last meta tag. To avoid that we can add a property key to the meta tag and @vueuse/head will keep both meta tags.
This works fine with the composable useMeta but in the Meta component we need to add the key property to pass it then to useMeta.
=> fix(nuxt3): add missing `key` property to meta components

packages/nuxi/src/commands/usage.ts, packages/nuxi/src/index.ts
resolves #2062
This PR aims to remove duplicated code and calls `usage` command directly (unless there's a reason we weren't doing that already?).
Output: 
```
❯ yarn nuxi usage
Nuxt CLI v3.0.0
Usage: npx nuxi dev|build|analyze|generate|prepare|usage|info|init|create|upgrade [args]
Use npx nuxi [command] --help to see help for each command
```
=> fix(cli): enable `usage` command

docs/components/atoms/Gem.vue
Fixes issue [#1852](https://github.com/nuxt/nuxtjs.org/issues/1852) of nuxtjs.org repository
[#1852](https://github.com/nuxt/nuxtjs.org/issues/1852)
The homepage of the docs of v3 contains a gem, which can be dragged out of view by moving the mouse while pressing right click (or using two fingers on mobile). This PR disables dragging.
Resolves [#1852](https://github.com/nuxt/nuxtjs.org/issues/1852)
=> docs: disable gem dragging

packages/nitro/src/server/dev.ts
#1834 
Resolves #1834 
If there is an error when a new worker is created, the user does not get the specific error message so they cannot fix it.
This simply logs the error to the user.
=> fix(nitro): add error logging to `initWorker`

packages/nitro/src/rollup/plugins/externals.ts
resolves #2083
(likely) resolves #309
Sometimes we have multiple versions of a library (such as `tslib`) with different major versions required for server dependencies. (See #2083 for example.) Previous tracing implementation flattened this out, for a disk space improvement, but risked resolving multiple versions to last-identified nft file.
Example nft results:
```bash
/node_modules/tslib/tslib.js
/node_modules/@azure/ms-rest-js/node_modules/tslib/package.json
/node_modules/@azure/ms-rest-js/node_modules/tslib/tslib.js 
```
Alternatively, we could check package versions, but I think it's safer to respect package manager's judgement on whether to flatten/nest the dependency.
=> fix(nitro): respect fs structure for traced files

packages/nuxt3/src/app/nuxt.ts
In server side, we have to only allow `useNuxtApp` within plugins and render to avoid context sharing but we don't need to disallow it in client-side. This allows use `useNuxtApp` after render lifecycle in composables that being called by user actions.
=> fix(nuxt3): keep `nuxtApp` instance in client-side

docs/content/3.docs/1.usage/6.cookies.md
This PR makes the _cookies_ page available at `docs/usage/cookies` and fixes its table of contents (some section headers were nested one level too deep and weren't included).
=> docs: fix usage/cookies url and table of contents

docs/content/1.getting-started/3.bridge.md
Dangling comma is not valid JSON.
Given the whole section is added, it does not look like `experimentalCompatMode` is added as one of many properties, but it's the only one and then should not have a comma.
=> docs: remove dangling comma from sample `tsconfig.json`

packages/nitro/src/build.ts, packages/nitro/src/utils/index.ts, packages/vite/src/vite.ts
resolves #1192
When building, vite copies `publicDir` contents and places them alongside assets in the `_nuxt` folder. This is an unwanted duplication of assets. (They will never be served from this path.) We can 'fix' this behaviour by simply not copying these files across to `.output/public`.
Ideally we would fix this with a PR to vite itself to allow us to allow js files to be included with `assetsDir` as well, rather than setting vite's `base: '_nuxt'`, which seems like a workaround for our desired nuxt behaviour. (cc: @antfu)
=> fix(vite): don't copy `publicDir` files to `_nuxt`

packages/bridge/src/runtime/composables.ts
=> fix(bridge): fixed reactivity on csr of useState reactive payload

packages/bridge/types.d.ts, packages/nitro/types/index.d.ts, packages/schema/src/types/config.ts
resolves #2126
Follow-up on migration to `@nuxt/schema`. I've also changed NuxtConfig to extend NuxtOptions. But this may have been  intentional; let me know if so (cc: @pi0).
=> fix(schema): extend `NuxtOptions` for nitro & bridge types

docs/content/1.getting-started/5.commands.md, docs/content/2.concepts/3.typescript.md, packages/nuxi/src/commands/index.ts, packages/nuxi/src/commands/typecheck.ts, packages/schema/src/config/_internal.ts
resolves #1825
This adds support for using `vue-tsc` in any nuxt project. It will first generate the types and then run `vue-tsc` on the project.
=> feat(nuxi): add `typecheck` command using `vue-tsc`

packages/bridge/src/runtime/app.plugin.mjs, packages/nuxt3/src/app/composables/asyncData.ts, packages/nuxt3/src/app/nuxt.ts
resolves #2122
resolves #2032
This PR includes pending/error state within the payload. Otherwise a page that (for example) checked `v-if="error"` would fail to hydrate between client/server. Because we're including pending state as well, we can use that to detect whether we need to refetch data on client side.
=> fix(nuxt3): handle hydration for `error` and `pending` state

packages/nuxi/src/commands/upgrade.ts
Add nuxt3 to dev dependencies. Otherwise users on default `nuxt/starter` get something like the following message:
```
Nuxt CLI v3.0.0-27293794.c3b72a6
ℹ Package Manager: yarn 1.22.17
ℹ Current nuxt version: 3.0.0-27293794.c3b72a6
ℹ Upgrading nuxt...
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
warning "nuxt3" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
success Saved 12 new dependencies.
```
=> fix(nuxi): add `nuxt3` to dev deps in upgrade command

packages/schema/src/types/imports.ts
Simply fixes an issue where the `autoImports.dirs` type was set to `[]` instead of `string[]`
=> fix(autoImports): dirs option should be of type `string[]`

packages/bridge/src/app.ts
resolves #2069
resolves #1920
This PR uses the Nuxt 3 components template for adding Volar support for components in the global namespace.
I believe this is the last piece required for proper Volar support with Nuxt Bridge.
=> feat(bridge): generate components declarations

packages/schema/src/config/_app.ts
Currently, `plugins` has `NuxtPlugin[]` as type although the documentation also allows plain strings. This is fixed.
=> fix(schema): allow strings in plugin config

packages/nuxt3/src/app/composables/asyncData.ts
By setting explicitly to null when there's no error we also add asyncData _key_ to payload which can't be deduplicated as the null value can. This PR avoids that cost by only setting errors if they exist.
=> perf(nuxt3): don't include null errors in payload

docs/content/2.concepts/4.esm.md
https://github.com/nuxt/framework/issues/1999#issuecomment-973990234
Add workaround for default imports from CommonJs modules.
=> docs(esm): add notes about default exports

examples/with-components/app.vue, examples/with-components/components/HelloWorld.vue, examples/with-components/components/Nuxt3.vue, examples/with-components/nuxt.config.ts, packages/bridge/src/vite/server.ts, packages/vite/src/dev-bundler.ts, packages/vite/src/server.ts
Reverts nuxt/framework#2067
And also https://github.com/nuxt-contrib/vue-bundle-renderer/pull/21
Fix #2224
We might need to find a better way of doing this later.
=> fix(vite): include dynamic css (revert #2067)

packages/webpack/src/presets/style.ts
resolves #2217
`reloadall` and `hot`  property of `minicssextractplugin.loader` options have been removed. it will cause error when build with webpack If we continue to set them,
=> fix(webpack): remove MiniCssExtractPlugin.loader options (#2217)

packages/kit/src/module/define.ts
resolves #2222
With addition of other virtual templates in Nuxt Bridge (https://github.com/nuxt/framework/pull/2168), a bug in the underlying implementation (https://github.com/nuxt/framework/pull/587) was exposed (splicing array whilst traversing with `forEach` ended up failing to process last item.
=> fix(bridge, kit): don't modify template array whilst traversing it

docs/content/1.getting-started/4.bridge-composition-api.md
resolves #2272
This aligns the recommendation for importing `useRoute`/`useRouter` (and vue functions like `ref`) so when migrating to nuxt 3 things keep working.
=> docs: update 3rd party bridge imports to use `#imports`

packages/nitro/src/runtime/app/render.ts
fix #886
When using `ssr: false`, `server.mjs` doesn't exist, but Rollup gets confused because it thinks `server.mjs` might be imported. To fix this, I added a condition so that Rollup knows that `server.mjs` will never be loaded if `NUXT_NO_SSR` is `true`.
I also added code to handle the new Vite manifest format in `getSPARenderer`.
To test my changes, I added `ssr: false` to `playground/nuxt.config.ts`. Then, I ran `npx yarn run nuxi build playground && node playground/.output/server/index.mjs`.
=> fix(nitro): fix rendering with `ssr` disabled

packages/nitro/src/runtime/server/error.ts
resolves #2268
Set content-type for HTML error response.
=> fix(nitro): set content-type header before html 404

packages/nuxt3/src/meta/runtime/plugin.ts, packages/nuxt3/src/pages/runtime/router.ts
resolves #2329
This adds type definitions for built-in components from the `meta` and `router` packages to the `GlobalComponents` interface which Volar will pick up. By placing them within the relevant plugin, they will only be picked up if the corresponding ad-hoc module is enabled. (They get drawn in to the TS source through `plugins.d.ts`.)
=> feat(nuxt3): add global type definitions for built-in components

packages/nuxt3/src/app/compat/legacy-app.ts
resolves #2375
We shouldn't mock `ctx.req`, `res` or `ssrContext` on client-side, but can early-return with `undefined`, as plugins might legitimately test to see if these exist.
=> fix(nuxt3): don't mock server-only properties on client-side

packages/nuxt3/src/app/composables/component.ts, packages/nuxt3/src/meta/runtime/composables.ts
resolves #2344
The issue in #2344 is caused by importing `computed` from `@vue/reactivity` rather than `vue` - and only reproducible in vite.
The reason is that vite is optimizing imports from `vue`. It's not processing `nuxt3/dist/meta/runtime` which means it's unaware of an import from `@vue/reactivity`. (To see this in action, just add an import of `computed` from `@vue/reactivity` into the repro app; it'll start working.) **Note**: adding this path to `optimizeDeps` fails due to the import from `#app`, or I'd have taken this approach.
The consequence is that `/_nuxt/node_modules/.vite/vue.js` doesn't share any code with `@vue/reactivity` (`/_nuxt/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js`), which is what breaks reactivity.
I'd welcome ideas for å more systemic …
=> fix(nuxt3): import computed from `vue` to preserve reactivity

packages/bridge/src/auto-imports.ts, packages/nuxt3/src/auto-imports/imports.ts, packages/nuxt3/src/pages/module.ts, packages/nuxt3/src/pages/runtime/composables.ts
resolves #2402, resolves #1750
This allows using `useRoute` and `useRouter` within Nuxt plugins in Nuxt 3 (this already works in Bridge). They need to be imported from `#imports` or used via auto-imports. (I've moved them to the `pages` ad-hoc module as it probably doesn't make sense for them to be available unless it's enabled, but if we want them to have the `#app` alias I can move them into the app composables...)
=> feat(nuxt): add wrapped `useRoute` and `useRouter` composables

packages/nuxt3/src/auto-imports/module.ts
This ensures that `imports.d.ts` is included in ts scope (otherwise you'll see red underlines for the nuxt-specific aliases like `vue-demi` and `#meta` if you open the file up). With this change, they are recognised and clickable.
=> fix(nuxt3): add `imports.d.ts` to `nuxt.d.ts`

packages/nitro/types/shims.d.ts
Fix to update the typing for `#assets`. Here's the implementation:
https://github.com/nuxt/framework/blob/a08b435f51a2e054a708eb5dae283f74b8874450/packages/nitro/src/rollup/plugins/assets.ts#L82-L108
=> fix(nitro): correct `#assets` type declaration

packages/bridge/src/vite/vite.ts, packages/vite/src/vite.ts
When user-defined
```ts
{
vite: {
logLevel: 'info' 
}
}
```
it won't work, which makes it a bit hard to debug or gather info from vite.
=> fix(vite): respect users config

packages/nuxt3/src/components/module.ts
resolves #2343
This adds tests to the existing list of exclusions in the components module. Ultimately we are going to want to implement `.nuxtignore` support: https://github.com/nuxt/framework/issues/2163#issuecomment-981612377.
=> fix(nuxt3): ignore tests within components directory

packages/nitro/src/rollup/config.ts
resolves #2377
see also https://github.com/rollup/plugins/issues/1064
Co-authored-by: Matteo Rigoni <matteo.rigoni@atoms.studio>
Generating sourcemap is what seems to be causing the memory spike, and this change respects the existing `sourceMap` nitro option.
All credit to some great detective work from @Rigo-m.
On a large project this change shaved off 60% of ram usage and made the build 40% faster.
=> fix(nitro): pass sourcemap option through to rollup plugins

docs/content/1.getting-started/3.bridge.md, packages/bridge/src/capi.ts, packages/bridge/src/module.ts, packages/bridge/types.d.ts
Previously, even if users had fully migrated to new Composition API, we are still loading in support for keying `ssrRef`, etc. There's a small performance win users can realise by disabling legacy support.
```js
bridge: {
capi: {
legacy: false 
}
}
})
```
=> perf(bridge): allow skipping legacy composition api support

packages/nuxt3/src/pages/runtime/composables.ts, packages/nuxt3/src/pages/runtime/router.ts
resolves #2441, closes #2442
This defines `nuxtApp._route` in the same instance as creating the router itself, rather than on the calling of a composable, which is probably the right location for this.
=> fix(nuxt3): define route in plugin rather than composable

docs/content/3.docs/2.directory-structure/9.pages.md, examples/with-pages/pages/parent.vue, packages/nuxt3/src/pages/runtime/nested-page.vue, packages/nuxt3/src/pages/runtime/router.ts
resolves #2106
This renames `<NuxtChild>` to `<NuxtNestedPage>`, keeping `<NuxtChild>` as an undocumented alias.
=> refactor(nuxt3): rename `<NuxtChild>` to `<NuxtNestedPage>`

packages/bridge/src/nitro.ts, packages/nitro/src/build.ts, packages/nuxt3/src/core/nitro.ts
#2401
This exports `writeTypes` from Nitro, allowing types to be written without building a Nitro server. This allows us to call `writeTypes` within bridge & nuxt3 to generate `nitro.d.ts`.
I would suggest entirely moving the _calling_ of `writeTypes` out of `@nuxt/nitro` and into a Nuxt hook, as it seems more like the right place for the job.
I've created this as a separate PR from the other two related .d.ts PRs as we may pend this until `nitropack` lands. And this is purely additive; that is, the other PRs work fine without it, they just don't generate `nitro.d.ts`.
=> feat(nitro, nuxt3, bridge): expose `writeTypes` and call this within `builder:generateApp`

packages/nitro/src/rollup/config.ts, packages/nitro/src/rollup/plugins/externals.ts
This PR allows manually specifying additional packages that will be traced and copied across to `.output/server/node_modules`, for example if `@vercel/nft` isn't able to detect the requirement.
=> feat(nitro): specify packages to copy to `.output/server/node_modules`

packages/nitro/src/rollup/config.ts, packages/schema/src/config/_common.ts
resolves #2423
By default `defu` doesn't process values that are null or undefined at the top level:
https://github.com/unjs/defu/blob/main/src/defu.ts#L22-L24
But we likely want to preserve these in `runtimeConfig` as this enables the runtime check for the existence of these environment variables.
I've also switched to using `devalue` for Nitro's runtimeConfig as this enables us to preserve `undefined` values.
=> fix(schema): handle null/undefined values in `runtimeConfig`

packages/nuxt3/src/app/composables/cookie.ts
resolves #2480
When unsetting the cookie, we were mutating the options which mean that any subsequent setting of cookie value would have a `maxAge` of `-1`, which would effectively unset the cookie immediately.
https://github.com/nuxt/framework/blob/6a25d3e245a88d3c838dafa643a5210dba625d73/packages/nuxt3/src/app/composables/cookie.ts#L61-L63
This PR clones the options in the serialize function so we don't mutate the original options object.
=> fix(nuxt3): don't mutate options when unsetting cookie

docs/content/1.getting-started/3.bridge.md
Add a disclaimer highlighting that properties specified in `tsconfig.json` will be overwriting all properties extended from `./.nuxt/tsconfig.json`.
[#586](https://github.com/johnsoncodehk/volar/issues/586#issue-1024254907)
Adds a disclaimer highlighting that properties specified in `tsconfig.json` will be overwriting all properties extended from `./.nuxt/tsconfig.json`.
It is/was typical to have to define your own `"compilerOptions.paths"` mappings in `tsconfig.json` when using Nuxt 2.
Now that Nuxt 3/nuxi provides `./.nuxt/tsconfig.json` to extend from (recommended in the docs) it would be useful to mention that previously defined properties will be overwriting the extended properties from `./.nuxt/tsconfig.json` entirely.
Extending a config with the following definition...
```json …
```
=> docs(bridge): add overwriting disclaimer to tsconfig section

docs/content/2.concepts/3.typescript.md
Add a disclaimer highlighting that properties specified in `tsconfig.json` will be overwriting all properties extended from `./.nuxt/tsconfig.json`.
[#586](https://github.com/johnsoncodehk/volar/issues/586#issue-1024254907)
Adds a disclaimer highlighting that properties specified in `tsconfig.json` will be overwriting all properties extended from `./.nuxt/tsconfig.json`.
It is/was typical to have to define your own `"compilerOptions.paths"` mappings in `tsconfig.json` when using Nuxt 2.
Now that Nuxt 3/nuxi provides `./.nuxt/tsconfig.json` to extend from (recommended in the docs) it would be useful to mention that previously defined properties will be overwriting the extended properties from `./.nuxt/tsconfig.json` entirely.
Extending a config with the following definition...
```json …
```
=> docs(concepts): add overwriting disclaimer to tsconfig section

packages/nuxt3/src/core/nuxt.ts
=> fix(nuxt3): properly pass inline options to `installModule`

packages/vite/src/dev-bundler.ts
Fix #2336, @larbish also faced this in his supabase module.
The root cause is that Vite will inject `?v=8888` for updated modules to bypass the cache of the browser. Which in this case, Node won't understand the query, so we remove the query when externalizing the module.
=> fix(vite): remove vite's query for external modules

docs/content/3.docs/2.directory-structure/12.server.md
Issue #2503
This change fixes the paths of the .md links in the server docs, namely `API Routes` and `nuxt.config.js`. They were erroneously linked.
To avoid having the links go to 404.
=> fix(docs): fix broken links in server section

packages/bridge/module.cjs
Fix #2501
I am not very sure if there is a reason for the initial decision to append the module at the beginning, but having that at the beginning caused the other modules relying on the hooks provided by the bridge fail to work.
e.g. in @vueuse/nuxt
We have
```ts
// @vueuse/nuxt
{
setup() {
nuxt.hook('autoImports:sources', () => { /* register the auto imports */ })
}
}
```
Where if the bridge module has been installed before, the hook has already been called, causing the auto-import registration in VueUse never called.
As a temporary workaround, explicitly set the bridge module at the end
```ts
// nuxt.config.js
{
buildModules: [
'@vueuse/nuxt',
'@nuxt/bridge'
]
}
```
=> fix(bridge): install bridge module at the end

packages/bridge/package.json, packages/vite/package.json, packages/vite/src/server.ts, yarn.lock
In Vite 2.6, it introduced a mechanism to pre-transform the direct imports before the browser requests landed. It could improve the response time of waterflow requests. However, when in SSR, we have our custom logic to handle the externalization, which the pre-transform might start transforming the externalized modules, causing some computation power waste.
Refer to https://github.com/vitest-dev/vitest/issues/229#issuecomment-1002685027
=> perf(ssr): disable vite's pre-trasnfroming to improve perf

packages/nuxt3/src/app/composables/component.ts
We implemented legacy Options API asyncData support when useAsyncData returned a reactive object. It now returns a ref. This PR updates the legacy support to handle a ref wrapper - but of course will only work if that wrapper contains an object (so will warn in dev mode if it's lacking).
=> fix(nuxt3): handle legacy `asyncData` (options api) as `ref`

docs/content/1.getting-started/3.bridge.md
By not removing a previous `.nuxt` folder, the `yarn dev` socket might be broken and throw an error on the console.
I added said step in this PR.
=> docs(bridge): advice to stop server before upgrade

packages/bridge/src/vite/server.ts, packages/vite/src/server.ts
https://github.com/vitejs/vite/blob/04016df8beb7110ad2087ada8e1abbefdbd70254/packages/vite/src/node/constants.ts#L3-L7
We have confirmed this works for Vitest and sloved many issues we had.
=> perf(vite): do not resolve `module` field for packages

packages/nitro/src/runtime/entries/server.ts
resolves #1701
This adds support for initialising an HTTPS server (instead of HTTPS) if `NITRO_SSL_CERT` and `NITRO_SSL_KEY` are set. The provisos in issue #1701 stand.
If we're happy with this in general terms I'll go ahead and add documentation for these env variables to the docs on the server preset.
To test:
```bash
openssl genpkey -out nitro.key -algorithm RSA -pkeyopt rsa_keygen_bits:2048
openssl req -text -in nitro.csr -noout
openssl x509 -req -days 365 -in nitro.csr -signkey nitro.key -out nitro.crt
yarn nuxi build
NITRO_SSL_CERT=$(cat nitro.crt) NITRO_SSL_KEY=$(cat nitro.key) node .output/server/index.mjs
```
=> feat(nitro): ssl nitro support in production

packages/bridge/src/vite/vite.ts
resolves #2528
This adds missing `process.` flags present in the base nuxt 2 webpack config.
https://github.com/nuxt/nuxt.js/blob/dev/packages/webpack/src/config/base.js#L180-L186
=> fix(bridge): add missing process flags for vite

packages/nitro/src/rollup/plugins/middleware.ts, packages/nitro/src/runtime/app/render.ts, packages/nitro/src/server/middleware.ts, packages/nitro/src/utils/index.ts, packages/vite/src/utils/index.ts
This PR replaces `.substr` use with `.slice` as the former is deprecated. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr
=> chore: replace `substr` with `slice`

packages/bridge/src/vite/server.ts, packages/vite/src/server.ts
resolves #1367
This PR invalidates the vite server modules that correspond to the vfs templates that are generated in the app.
A possible enhancement could be only invalidating templates that have _changed_ but that would involve slightly more interrelation with the app part of nuxt3, though it's certainly also possible.
Note that this PR fixes vite but a similar issue exists with regard to webpack - see https://github.com/sysgears/webpack-virtual-modules/issues/89
=> fix(vite): invalidate virtual modules when templates are regenerated

docs/content/3.docs/2.directory-structure/12.server.md
#1860 
Adding example of accessing req body in docs
It is not possible to know how to access the req body without an example
Doc link:
https://v3.nuxtjs.org/docs/directory-structure/server
=> docs: add api req helpers example

packages/kit/src/resolve.ts
resolves #2677
We're currently completely ignoring the `@` alias to avoid resolving `@foo/bar` incorrectly. This ensures we'd don't skip the `@` alias in other situations.
**Aside**:
It might be worth considering _only_ resolving aliases with a directory separator afterwards as I imagine there could be some wrong resolutions from the current behaviour (e.g. consider aliases `~` and `~someotheralias`). This would of course be a breaking change.
Alternatively, perhaps we could resolve in reverse length order?
=> fix(kit): don't ignore `@` alias

packages/nuxt3/src/meta/runtime/plugin.ts
resolves #2763
As it's quite tough to do much with a `head()` function without any context, this PR passes `nuxtApp` as an argument to `head()`.
=> feat(nuxt3): pass `nuxtApp` to `head()`

examples/hello-world/nuxt.config.ts, packages/nuxi/src/commands/dev.ts, packages/schema/src/types/hooks.ts
https://github.com/nuxt/framework/issues/2499
- [] ✨ New feature (a non-breaking change that adds functionality)
- [] ⚠️ Breaking change (fix or feature that would cause existing functionality to change) 
The listen hook is a feature from nuxt v2 that is typed in nuxt v3. but nothing calls it (as far as I can tell).
It's a useful hook to expose the server used for local development, giving module authors functionality to see the server address and hook into the server if needed.
Specifically a module I'm working on needs it, this is the equivalent nuxt 2 code.
```ts
nuxt.hook('listen', (ctx) => {
setServerContext({
url: ctx.listeners[0].url,
server: ctx.listeners[0].server,
app: ctx.app,
})
})
```
=> feat(nuxi): call nuxt `listen` hook for dev

docs/content/3.docs/2.directory-structure/10.plugins.md, docs/content/3.docs/2.directory-structure/5.composables.md, packages/kit/src/resolve.ts, packages/nuxt3/src/auto-imports/composables.ts, packages/nuxt3/src/core/app.ts
resolves #2531
This PR proposes a change to how auto registration works for composables & plugins. Rather than detecting only top level composables (as current) or all files in infinite recursion (as plugins), we adopt a new pattern that we register all top level files, and then only indices for any subdirectories.
For example:
```
plugins
| - myPlugin.ts
| - myOtherPlugin
| --- supportingFile.ts
| --- componentToRegister.vue
| --- index.ts
```
Only `myPlugin.ts` and `myOtherPlugin/index.ts` would be registered. This would allow for better code organisation within the plugins directory.
Similarly, for composables:
```
composables
| - useFoo.ts
| - useBar
| --- supportingFile.ts
| --- index.ts
```
Only `useFoo.ts` and `useBar/index.ts` would be searched for imports - and if the latter is a …
=> fix(nuxt3): import top-level files and subdirectory indices

packages/nuxi/src/commands/dev.ts
We should react to changes in a custom pages directory just as we do in the default `pages` dir.
=> fix(nuxi): respect custom pages directory

packages/nuxt3/src/pages/macros.ts, packages/nuxt3/src/pages/module.ts
resolves #2794
This PR hotfixes the issue with vite HMR by not treeshaking out the normal module exports. (We have to solve proper HMR for page meta, which is not yet working, separately.)
=> fix(nuxt3): only treeshake macro exports when building

docs/content/1.getting-started/1.introduction.md, packages/nuxt3/src/app/types/index.d.ts, packages/nuxt3/src/app/types/shims.d.ts, packages/nuxt3/src/core/nuxt.ts, packages/nuxt3/src/core/templates.ts, packages/schema/src/config/typescript.ts
https://github.com/vuejs/create-vue/pull/26
This PR removes the default '*.vue'* shim so that Volar can provide better type inference, such as clicking through directly to the component definition rather than the shim. (It may still be necessary for users of other IDEs  to add the shim themselves.)
=> feat(nuxt3): allow disabling vue type shims

packages/bridge/src/nitro.ts
Once https://github.com/nuxt/nuxt.js/pull/10197 is merged, we don't want to override `baseURL` if it's properly set.
=> fix(bridge): don't override existing `baseURL` property

packages/nuxt3/src/pages/utils.ts
resolves #2822
For Windows systems, we need to normalize paths (or escape `\` characters) if users have insert their own un-normalised values.
=> fix(nuxt3): normalize page paths (for windows support)

docs/content/2.concepts/4.esm.md
Fix typo: "inerop" -> "interop"
https://v3.nuxtjs.org/concepts/esm#default-exports
=> docs(esm): fix typo

docs/content/3.docs/2.directory-structure/9.pages.md, examples/with-pages/app.vue, examples/with-pages/pages/parent/reload-[id].vue, examples/with-pages/pages/parent/static-[id].vue, packages/nuxt3/src/pages/runtime/composables.ts, packages/nuxt3/src/pages/runtime/nested-page.vue, packages/nuxt3/src/pages/runtime/page.vue
resolves https://github.com/nuxt/framework/issues/2309
This PR removes the default keying of routes to the full path, meaning that parent routes won't rerender when child routes change. It also adds support for setting custom keys for child routes, either a string or a function that receives the current route.
The key can either be set in `definePageMeta` or via a prop for `<NuxtNestedPage />`.
Contrary to [my earlier RFC](https://github.com/nuxt/framework/discussions/2468), I now think it makes sense to set the page key via meta as that way we can implement logic in a key function that will handle both child routes and deeply nested child routes (see following note).
**Note**: nested routes which have children themselves [behaved differently in Nuxt …
=> fix(nuxt3): allow customising page keys

packages/vite/src/client.ts, packages/vite/src/plugins/dynamic-base.ts, packages/vite/src/vite.ts
resolves #2777
This PR handles two issues with the recently merged support for dynamic base URLs in Vite.
1. CSS assets are rewritten to use relative imports
2. required assets are rewritten dynamically (we can't replace in transform because of the `__VITE_ASSET` map that is used by vite asset plugin).
=> fix(vite): handle emitted assets with relative urls and dynamic base

packages/nuxt3/src/core/nitro.ts, packages/nuxt3/src/core/nuxt.ts, packages/nuxt3/src/core/plugins/import-protection.ts
resolves #1471
This PR adds a plugin for rollup (Nitro), vite, and webpack to detect common patterns of wrong imports. It then can give helpful warnings (suggestions for better wording welcomed), and returns a proxy so the build doesn't completely fail (in this case the helpful warnings might be obscured by pages of cryptic errors)...
Rather than add the plugin in Nitro, I've added it in nuxt3 as it is protecting _against_ nuxt3 aliases.
=> feat(nuxt3): add import protection patterns

docs/content/3.docs/1.usage/5.runtime-config.md
I'd like to propose an example for using runtime configuration within plugins.
An example plugin that uses the runtime config. This is not well conveyed in the runtime plugins and so I thought this would be nice to have.
=> docs: add example of `useRuntimeConfig()` within a plugin

packages/nuxt3/src/core/nuxt.ts
It gives modules a chance to hook before being called. Currently it was only possible with `buildModules` as built-in modules were being called after them.
=> fix(nuxt3): setup built-in modules as last

docs/content/3.docs/2.directory-structure/6.layouts.md, packages/nuxt3/src/pages/module.ts, packages/nuxt3/src/pages/runtime/composables.ts, packages/nuxt3/src/pages/runtime/page.ts, packages/nuxt3/src/pages/runtime/router.ts
resolves https://github.com/nuxt/framework/issues/2867
This PR:
1. types layout strings in page meta, just as middleware is (that is, adds hints) - this should resolve 
https://github.com/nuxt/framework/issues/2567 and resolve https://github.com/nuxt/framework/issues/2518
2. makes page meta reactive by default - [improving experience for making reactive layouts, for example](https://github.com/nuxt/framework/issues/2867#issuecomment-1019261409)
3. fixes an issue with transitioning to and from pages with layouts (we now render fragments in place of missing transition/layout components rather than omitting the nodes entirely)
=> feat(nuxt3): make layout and other page meta reactive

packages/nuxt3/test/auto-imports.test.ts
The previous test would always pass as it used `"` rather than `'`. (Discovered in #2216 when the quotation changed.)
=> test(nuxt3): fix exclude test

packages/nuxt3/src/app/bootstrap.ts, packages/nuxt3/src/app/components/nuxt-root.vue, packages/nuxt3/src/app/nuxt.ts
resolves https://github.com/nuxt/framework/issues/2938
Our asyncData implementation was dependent on a hook being called within the pages module. This adds a similar hook at `app` level meaning that `asyncData` will work as expected on client-side.
Ideas for better hook naming welcome.
=> fix(nuxt3): add `app:suspense:resolve` hooks

packages/nuxt3/src/components/module.ts
https://github.com/nuxt/framework/discussions/2947
There have been a number of issues with lacking a reference to `components.d.ts` which is likely to do with some inconsistency between when these hooks are being called (ie. we may not have the components fully resolved by the time we're writing the type file). This PR always adds the file to `nuxt.d.ts`, as a hotfix.
=> fix(nuxt3): hotfix for missing components declaration

packages/nuxi/src/commands/upgrade.ts
#2951
The nuxi upgrade now fails with `ENOENT` after this commit: https://github.com/nuxt/framework/commit/6e06d2b4c9c7dd8f59442e93962f48e4a8bb156b#diff-6adc9cccbbc7f61fcf38abdc8a1521338913c2215e3d099d1b71ebadbfc53b9dR47
`rmdir` [has been deprecated](https://nodejs.org/api/fs.html#fspromisesrmdirpath-options) in `v14.14.0` of node 
I have also added a path check beforehand as I got it to fail with `ERROR  ENOENT: no such file or directory, stat 'node_modules/.cache'`
This resolves #2951
=> fix(nuxi): updated rmdir to rm and checked paths exists

docs/content/3.docs/4.advanced/2.modules.md
Broken link out to modules.nuxtjs.org
prefix with https://
- Go to https://v3.nuxtjs.org/docs/advanced/modules/#modules-ecosystem
- Click link to modules.nuxt.org
- See 404
=> docs: add `https://` to link

docs/content/3.docs/2.directory-structure/15.app.md, packages/nuxt3/src/pages/runtime/app.vue, packages/nuxt3/src/pages/runtime/layout.ts, packages/nuxt3/src/pages/runtime/page.ts, packages/nuxt3/src/pages/runtime/utils.ts
resolves #2074
This PR extracts `<NuxtLayout>` from `<NuxtPage>` while preserving its behaviour. (Though we do move the transition into the layout component.)
**Note**: This will mean once we have [aligned the behaviour of route keys between pages/nested pages](https://github.com/nuxt/framework/pull/2976), we can actually replace `<NuxtNestedPage>` with `<NuxtPage>` entirely, which will improve UX for transitions between nested pages.
* Add `<NuxtLayout>` to `app.vue` if you are using layouts:
```diff
<template>
+  <NuxtLayout>
<NuxtPage />
+  </NuxtLayout>
</template>
```
* If you were passing layout manually to `<NuxtPage>`, move this to `<NuxtLayout>` instead:
```diff
<template>
+  <NuxtLayout name="my-layout">
-     <NuxtPage layout="my-layout" />
+     <NuxtPage />
+  </NuxtLayout> …
```
=> refactor!: extract `<NuxtLayout>` from `<NuxtPage>`

packages/kit/src/loader/config.ts
C12 does not load `.env` file by default and it requires `dotenv` config. This changes makes sure that `dotenv` options provides for C12 and `.env` file loads.
close #3017
=> fix(kit): load dotenv if option is missing

packages/nuxt3/src/auto-imports/imports.ts, packages/nuxt3/test/auto-imports.test.ts
These are compiler macros or (in the case of `stop`) conflicting with a global object already available - so they shouldn't be auto-imported.
=> fix(nuxt3): remove existing globals from auto-imports

packages/kit/src/auto-import.ts, packages/kit/src/plugin.ts, packages/nitro/src/rollup/plugins/assets.ts, packages/schema/src/types/compatibility.ts, packages/schema/src/types/components.ts, packages/schema/src/types/imports.ts
This replaces accidentally included constructors with types instead.
=> chore: replace constructors with types

packages/bridge/src/vite/module.ts
resolves #2978
We mock bundleBuilder.build() in nuxi prepare but if vite is enabled in Bridge, we entirely replace webpack builder, meaning we have to run a full build. This avoids replacing the bundle builder if we are running with `nuxi prepare`.
=> fix(bridge): don't instantiate vite builder if only preparing types

packages/kit/src/loader/config.ts, packages/schema/src/types/config.ts
Following up https://github.com/nuxt/framework/pull/3008, this PR renames `layers` to `_extends` to make it consistent with `extends` key. Also fixing type which should be NuxtConfig rather than normalized NuxtOptions
=> refactor: rename `options.layers` to `options._extends`

examples/config-extends/app.vue, examples/config-extends/base/components/BaseButton.vue, examples/config-extends/base/components/FancyButton.vue, examples/config-extends/components/FancyButton.vue, packages/nuxt3/src/components/module.ts, packages/nuxt3/src/components/scan.ts, packages/nuxt3/test/scan-components.test.ts, packages/schema/src/config/_adhoc.ts, packages/schema/src/types/components.ts, playground/nuxt.config.ts
Following up #3008 this PR allows extending `components/` directory for extended config layers
**Breaking change:** Components `level` property is no longer supported. It was a necessary workaround to support [nuxt-extend](https://www.npmjs.com/package/nuxt-extend) but now, layers naturally are ordered and user's config has highest priority.
=> feat!(nuxt3): extends support for `components/` directory

packages/nitro/src/rollup/config.ts
resolves #1997, resolves #2999
We were being a little over-zealous in our replacement. I hope a stray `global.` won't slip through the net, but by adding a specific list of possible values to replace, we can improve things.
An alternative, which is quite tempting, is to write our own rollup plugin that would add a RegExp that's more precisely targeted to this need (vs `@rollup/plugin-replace` which only supports non-RE delimiters).
=> fix(nitro): replace `global.` in fewer instances

docs/content/3.docs/4.advanced/3.kit.md, packages/bridge/src/nitro.ts, packages/kit/src/internal/cjs.ts, packages/kit/src/module/install.ts, packages/kit/src/resolve.ts, packages/nitro/src/server/middleware.ts, packages/nuxt3/src/auto-imports/module.ts, packages/nuxt3/src/components/module.ts, packages/nuxt3/src/core/app.ts, packages/nuxt3/src/core/nitro.ts
Merge `tryResolvePath` and expose as new `resolvePath` utility from `@nuxt/kit`:
- Use nuxt context for default options (`aliases`, `rootDir`, `extensions` and `modulesDir`
- Always return a Promise
- Return original input value (normalized) in case of resolve failing instead of throwing an error or returning `null`
- For performance, case sensitivity is no longer checked based on dir files
A new `findPath` utility was also introduced to search for paths (case sensitive). Internally used for finding `App.vue`.
=> feat(kit)!: expose `resolvePath`

docs/content/3.docs/4.advanced/2.modules.md, docs/content/3.docs/4.advanced/3.kit.md, packages/kit/src/resolve.ts, playground/nuxt.config.ts
A new `createResolver` utility, makes life easier for module authors resolving relative paths.
Usage:
```js
const resolver = createResolver(import.meta.url)
addPlugin(resolver.resolve('runtime/plugin'))
console.log(await resolver.resolvePath('some-lib'))
```
This PR adds some fixes and improvements to `resovlePath` and `resolveAlias` to work when nuxt is not ready yet
=> feat(kit): `createResolver` utility

packages/nitro/src/runtime/app/render.ts
resolves #3041, resolves #2553
When we moved to bootstrap + entry pattern (for module federation support), we inadvertently made the real entrypoint show up in the manifest as a dynamic entrypoint. This fixes that by making all top-level dynamic dependencies of the entrypoint entrypoints too (for SPA renderer).
=> fix(nitro): treat bootrap dep as an entry file

packages/nuxt3/src/pages/runtime/utils.ts
resolves #3113
O Safari, how my heart breaks. [source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#browser_compatibility)
Thankfully the fix is relatively simple.
=> fix(nuxt3): remove lookbehind for safari support

packages/vite/src/client.ts, packages/vite/src/server.ts, packages/vite/src/vite.ts
resolves #2942
Seems that the invalidation needs to happen in both server & client servers. I've also tentatively decided to warm them both up too - but please let me know if this is unnecessary for some reason.
=> fix(vite): invalidate client modules too

packages/bridge/src/nitro.ts
resolves #1968
We weren't passing on any errors when generating pages with Nitro.
This PR (minimally) returns error text, which allows nuxt 2 to respect the `--fail-on-error` flag.
We could _additionally_ always fail on error, which feels safer, and would just be a matter of adding two lines of code here: https://github.com/nuxt/framework/blob/00dea14b4287276caf36c4ca27abe7c6c7ada4a0/packages/bridge/src/nitro.ts#L195-L198
Thoughts welcome.
(**Note**: I also swapped joinURL as the URL being fetched had a double slash.)
=> fix(bridge): respect `--fail-on-error` in generation

packages/nitro/src/runtime/entries/lambda.ts
[AWS Payload 2.0 passes cookies in an array on event](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) rather than within headers. This PR adds them to the headers object.
In addition, I've attempted a type refactor. I've left the runtime code intact, but by annotating with `as` it should help future readers of the code see how the properties related to the payload version, and it means we also will get a compile error if we access a property that exists in one format but not the other unless we specifically annotate that access.
=> fix(nitro): handle incoming cookies on lambda payload format 2.0

packages/schema/build.config.ts, packages/schema/src/config/_common.ts
resolves #3138
`/project` has led to one or two issues with people thinking it's a shortcut to the project path, as also has `<rootDir>` in the nuxtjs.org docs. I think `/path/to/your/app` (or something similar) might help.
=> docs(schema): clarify aliases and use more obvious example path

package.json, packages/vite/package.json, packages/vite/src/client.ts, yarn.lock
Fix #3006, Fix partially #1036
*Thanks a lot for @danielroe's help!*
The root cause of HMR breakage is because in middleware mode of Vite, the HMR port is fixed to 24678. Which means when you have multiple Vite/Nuxt instances running, it causes the later server to connect to the wrong Websocket instance, making the HMR fail to trigger. This PR makes the port dynamic with the currently available ports.
=> fix(vite): assign different hmr port for each instance

docs/content/3.docs/4.advanced/2.modules.md
There was a typo in de docs, instead of running `npm run prepare` you need to run `npm run dev:prepare`.
=> docs: fix typo in prepare command

packages/nuxt3/src/pages/macros.ts, packages/nuxt3/src/pages/runtime/composables.ts
resolves #3175
This follows up on #3150 - I missed the fact that when we early return, we've potentially also changed code. This is also the cause of the new warning people are receiving about using `definePageMeta` outside of setup.
=> fix(nuxt3): re-enable tree-shaking `definePageMeta`

packages/nuxt3/src/meta/runtime/components.ts, test/fixtures/basic/pages/index.vue
resolves #1909
We need to return a render function; default slot isn't always an equivalent function at the time the parent setup is run.
=> fix(nuxt3): return render function for `<Head>`

packages/nuxt3/src/pages/runtime/router.ts
resolves #3186
This is a hotfix for #3186, pending reworking with result of https://github.com/nuxt/framework/discussions/559. It returns an (empty) 401 response.
=> fix(nuxt3): return error page on blocked initial navigation

packages/bridge/src/runtime/app.plugin.mjs, packages/nuxt3/src/meta/runtime/lib/vueuse-head.plugin.ts
https://github.com/nuxt/framework/pull/2419
This PR follows up on https://github.com/nuxt/framework/issues/2337. The issue it solves occurs in the initial render cycle, if there are multiple `useMeta` tags for the same tag type, e.g.:
```js
useMeta({ script: /* ... */ })
useMeta({ script: /* ... */ })
```
In this case, immediately triggering `updateDOM` after the first call causes a mismatch because we haven't yet registered the second script tag yet, and so it's removed. It's then added back, triggering the rerun.
By deferring updateDOM to mounted on the initial render, we give Vue a chance to process all these tags.
As a side effect, we are also more performant because we only trigger a single update, rather than a different one for every different `useMeta` call and meta tag we insert.
=> fix(nuxt3): prevent removing and re-adding tags before mount

packages/bridge/src/auto-imports.ts, packages/bridge/src/runtime/app.plugin.mjs, packages/bridge/src/runtime/app.ts, packages/bridge/src/runtime/composables.ts, packages/nuxt3/src/pages/runtime/composables.ts
This aligns route middleware in Bridge with Nuxt 3, to make it easier for modules which are providing both Bridge + Nuxt 3 support.
It also resolves https://github.com/nuxt/framework/issues/3158, by assuming if we have no nuxt instance we are being called in an async middleware.
=> feat(bridge): support `addRouteMiddleware`, `navigateTo` and `abortNavigation`

packages/nuxt3/src/app/nuxt.ts, packages/nuxt3/src/meta/runtime/lib/vue-meta.plugin.ts
We had an inconsistency in the codebase, although this didn't actually affect the code since it was to a _type_ and the (unused) `vue-meta` implementation:
https://github.com/nuxt/framework/blob/main/packages/nitro/src/runtime/app/render.ts#L133-L144
=> fix(nuxt3): update meta return type to `bodyScriptsPrepend`

packages/nuxt3/src/app/composables/fetch.ts, test/fixtures/basic/tests/types.ts
Resolves #3263
Allow setting custom response type of useFetch using first generic param similar to `$fetch`
Breaking change! If you was already using `useFetch` or `useLazyFetch` with custom type, it needs to be updated:
```diff
--- useFetch<string, ResponseType>(....)
+++ useFetch<ResponseType>(....)
```
=> fix(nuxt3)!: custom response type for `useFetch` using first generic

.eslintrc, packages/nuxt3/src/core/nuxt.ts
I think our internal lint rule was enforcing the opposite of what we meant to though I may have misunderstood the intent. But we are, I think, violating it here:
https://github.com/nuxt/framework/blob/aece3518b541663c1731160e42e26e6ac7c79ce8/packages/nuxt3/src/core/nuxt.ts#L5-L8
This PR is an initial stab meant to highlight the issue - we either need to:
1. amend lint error description to reflect what it's meant to do
2. rethink import approach in core/nuxt.ts
3. remove lint rules
cc: @clarkdo
=> chore: reverse target/from in eslint rule

packages/nuxt3/src/components/module.ts, packages/nuxt3/src/components/templates.ts, packages/schema/src/types/components.ts
resolves https://github.com/nuxt/framework/issues/2237
This change defaults to only using the loader to register components, rather than generating async chunks for every possible component. (This makes a huge difference with component libraries, as we don't need to compile all of their components, just the ones needed.)
This also adds a top-level `components.global` option to set the default value for component dirs which haven't set the global value.
If you were relying on global registration of your components - for example, because you wanted to use a dynamically computed component name (e.g. `<component :is="'icon-' + myIcon" />`) then you can re-enable the previous behaviour by setting `components.global`:
```diff
import { defineNuxtConfig } from 'nuxt3'
export default …
```
=> perf!(nuxt3): disable global components by default

.github/workflows/ci.yml
https://github.com/nuxt/framework/issues/3310
Cache all packages buid dist and restore in ci jobs for saving ci jobs time.
=> chore(ci): cache build packages dist on ci jobs

packages/bridge/src/nitro.ts, packages/nuxi/src/commands/analyze.ts, packages/schema/src/config/build.ts
(https://github.com/nuxt/framework/issues/3216)
When running `nuxi analyze` on bridge mode, we'll see error `Cannot read property 'replace' of undefined` which is because the analyze options is `true` instead of default options object.
This pr is fixing this issue by adding default analyze options in bridge mode
=> fix(config): add analyze plugin options in bridge mode

packages/nuxt3/src/components/module.ts
resolves https://github.com/nuxt/framework/issues/2748
Recently component dirs passed as objects were no longer respected (https://github.com/nuxt/framework/pull/3108). This PR adds a test for object dir syntax.
In addition, because we always added `~/components` to the dirs list, customisations of this root directory were lost. By dropping it from the module options, we _still_ get this added by default (by schema) when the user does not provide input, but allows the user to override or configure this.
=> fix(nuxt3): respect dirs as objects

packages/nuxi/src/index.ts
resolves #2281
In the event that the user is running `nuxi dev --help` we clear the screen. This is probably an exception to our desired default clearing behaviour.
=> fix(nuxi): don't clear screen on `nuxi dev --help`

packages/nuxt3/src/components/module.ts
When renaming a page the following error would be thrown. The cause was that every time the components scan function was running, it was adding another (duplicate) template to the list.
```bash
WARN  [SSR] Error transforming virtual:/framework/playground/.nuxt/plugins/server.mjs: Parse failure: Identifier 'components_515c5644' has already been declared (9:7)
Contents of line 9: import components_515c5644 from "/@id/__x00__virtual:/framework/playground/.nuxt/components.mjs";
Contents of line 9: import components_515c5644 from "/@id/__x00__virtual:playground/.nuxt/components.mjs";
at ssrTransform (packages/vite/node_modules/vite/dist/node/chunks/dep-971d9e33.js:52119:15)
at doTransform (packages/vite/node_modules/vite/dist/node/chunks/dep-971d9e33.js:53036:48)
at processTicksAndRejections …
```
=> fix(nuxt3): don't add superfluous templates

packages/nuxt3/src/app/plugins/router.ts
The warning is only appropriate when navigating, but every time we load a page we navigate on SSR, so best to defer the warning to client-side.
=> fix(nuxt3): only warn about error handlers on client-side

packages/nuxt3/src/app/plugins/router.ts
follow-up on #3345
We will move warning out of the nav handler entirely, and only warn + show error in event of error.
=> fix(nuxt3): only warn within error handling routine

docs/content/3.docs/2.directory-structure/13.server.md
=> docs: remove `await` in front of `useQuery` in example

packages/nuxt3/src/components/module.ts
#3425
Fixes possible infinite loop
=> fix(nuxt3): remove redundant call to `generateApp`

packages/nuxi/src/utils/prepare.ts
This purely improves DX for users. Without it we get this when trying to use `.tsx`:
[**tsconfig docs**](https://www.typescriptlang.org/tsconfig#jsx).
=> feat(nuxi): add jsx option to generated tsconfig

packages/nitro/src/rollup/plugins/timing.ts
split timing.js into it's own file
split up adding timing to globalThis into it's own file. See Issue for more details
=> fix(nitro): #3264

packages/schema/src/types/config.ts, test/fixtures/basic/types.ts
resolves  #3478
This allows untyped keys in `nuxt.config`. (Marking a signature as `@deprecated` has no effect.)
=> fix(schema): allow untyped keys in nuxt config

packages/nuxt3/src/auto-imports/composables.ts, packages/nuxt3/src/auto-imports/module.ts
I've modified the `autoImport` module to update the autoImport context when the `builder:generateApp` hook is called. 
This change allows modules that provide their own autoImports to manage them ( add / remove as needed ) when the `builder:generateApp` hook is triggered.
```ts
// current drawback: only called on initial run in current nuxt3 versions
nuxt.hook('autoImports:extend', (autoimports) => {
console.log('autoImports:extend')
// manage autoImports
})
nuxt.hook('builder:watch', async (_event, path) => {
if (!path.endsWith('.special')) return
// run logic needed when important files are modified
await nuxt.callHook('builder:generateApp')
})
```
Current nuxt3 implementation requires the dev server to be restarted for any changes to autoImports to take effect, because the …
=> feat!(nuxt3): allow modules to manage autoImports on `generateApp`

packages/bridge/src/nitro.ts, packages/bridge/src/vite/utils/fs.ts
resolves #3441
When we moved the static asset dir workaround from nitro -> vite we omitted to do the same in bridge vite implementation.
=> fix(bridge): port nested `_nuxt` dir fix to bridge vite

.eslintrc, package.json, packages/nuxt3/src/meta/runtime/components.ts, yarn.lock
resolves #2213
Upgrades `nuxt/eslint` config to v8. Also removes `key` prop from `Meta` component, which would have been ineffective (and also not in the spec for `<meta>` tags).
=> chore: update to nuxt/eslint-config 8

README.md
If you only want to make documentation, you don't necessarily pay attention to the development section. That's why I have adapted it. I refer to this question from myself https://github.com/nuxt/framework/issues/3550#issuecomment-1061534210
=> docs: add stub instruction to docs README section

packages/vite/package.json, packages/webpack/package.json, yarn.lock
There were a couple of dependencies not being provided in the builder packages where required (rollup & postcss), and magic-string and its dependencies was being inlined.
=> fix(vite, webpack): add missing dependencies

packages/nuxt3/src/auto-imports/module.ts
When `autoImports` are resolved from directories `autoImports:dirs`, the file extensions are NOT stripped when `imports.d.ts` is generated ( though, they are being stripped in `auto-imports.d.ts`)
Stripping the file extension improves DX & Typescript experience .
=> fix(nuxt3): strip file extensions in `imports.d.ts`

packages/bridge/src/app.ts, packages/nitro/src/rollup/config.ts
resolves #3431, resolves https://github.com/nuxt/framework/issues/3329
Previously we were always using the Vue ESM build, which caused memory leaks in production. This PR re-aliases the Vue CJS build in the server build, as well as ensures that `$isServer` is correctly set.
=> fix(bridge): use vue server build

packages/kit/src/plugin.ts, packages/schema/src/types/nuxt.ts
Previously, we actually errored if `src` was provided, e.g. https://github.com/nuxt/framework/blob/e674d0f60d52e26122ce54f6c82a5723f8fc8e23/packages/bridge/src/capi.ts#L26. This PR makes it optional.
=> fix(kit): allow `src` for `addPluginTemplate`

packages/bridge/src/nitro.ts
resolves #3441
Previous PR didn't account for `static` target which has a different Nitro lifecycle.
=> fix(bridge): handle static nested vite dirs

examples/config-extends/app.vue, examples/config-extends/base/plugins/my-plugin.ts, packages/kit/src/loader/config.ts, packages/nuxt3/src/core/app.ts
Following up #3222 (`extends` support progress) this PR allows extending `plugins/` directory for extended config layers
=> feat(nuxt3): extends support for plugins/ directory

docs/content/3.docs/2.directory-structure/13.server.md
#3561 
This PR adds an example that showcases the usage of `next` inside a server middleware.
=> docs(server): add example for early spiking middleware

docs/content/1.getting-started/5.commands.md, docs/content/3.docs/1.usage/8.cli.md
This PR adds a page in the Usage section of the docs to list Nuxi commands and options.
=> docs(usage): add references of nuxi commands and options

packages/nuxt3/src/pages/utils.ts
resolves #3602
This PR adds support for merging user-provided `meta` and meta coming from `definePageMeta`.
=> fix(nuxt3): support extending page metadata

docs/content/3.docs/3.deployment/2.cloudflare.md
So the problem is if you just copy & paste the documentation from https://v3.nuxtjs.org/docs/deployment/cloudflare/
You will be getting into a problem on github actions with 
```
$ /github/workspace/node_modules/.bin/nuxt build
[log] Nuxt CLI v3.0.0-27449808.ac40c97
Error:  Unexpected token '.'
``` 
But when checking the example repo:  
https://github.com/nuxt/nitro-demo/blob/main/wrangler.toml#L13
It was updated. it that make sense cause we are already building the application before in the gitub actions.
=> docs(cloudflare): update build command

packages/nuxt3/src/core/app.ts
#3618 
This PR addresses a regression made in #3462 that caused the dev server to crash when changes are made to `autoImport` directories.
Caused by failing to reassign `plugins` on iterations
=> fix(nuxt3): reassign plugins on iterations

renovate.json
resolves #3644
Re-enables auto-upgrade bridge deps except for vue, vue-router. It's difficult to test this but looks like it should work.
=> chore(ci): re-enable renovate for bridge

playground/nuxt.config.ts
Current non-existent extends is giving an error (unable to read `config.dir.layouts`). I can fix that if we intend to support non-existent extends keys, but thought this was just a mistake.
=> chore: remove non-existent extends

packages/nuxi/src/commands/info.ts
With new `builder` top-level option, vite config is always resolved even if webpack builder is chosen.
This also handles Bridge vite.
=> fix(nuxi): use new `builder` option for vite/webpack info

packages/bridge/src/vite/server.ts, packages/nitro/src/server/dev.ts, packages/nuxi/src/commands/dev.ts, packages/nuxt3/src/core/builder.ts, packages/vite/src/server.ts
resolves #3654
Across the nuxt codebase, this PR uses `debounce` + `debounce.promise` to prevent initialising a new handler before the old one has finished running (which should prevent double access to files, for example, or multiple callbacks pushing the same plugin to `app.plugins`, as in the issue linked above).
At the same time, we drop the timeout from (for example) 300 to 1. This leads to a significant increase in DX as it feels much faster.
This PR also:
* fixes a bug with nuxi dev where any path starting with `.nuxt` was not triggering a reload (such as `.nuxtignore`)
* adds `.env` and `.nuxtrc` files to trigger a full nuxt reload
=> fix(bridge,nitro,nuxi,nuxt3,vite): ensure debounced/async handlers run in order

packages/nuxt3/src/core/templates.ts
resolves https://github.com/nuxt/framework/issues/2664, resolves https://github.com/nuxt/framework/issues/3168
This resolves two significant layout-related bugs. By setting `suspensible` to false, layout children weren't blocking rendering of the app, which meant that `isHydrating` was false by the time these functions ran.
There is still [an upstream bug related to nested suspenses on route changes](https://github.com/vuejs/router/issues/626#issuecomment-1048609550), but it has a different cause.
=> fix(nuxt3): fix layout suspense loading

examples/config-extends/base/server/api/base.ts, examples/config-extends/server/api/hello.ts, packages/nitro/src/build.ts, packages/nitro/src/context.ts, packages/nuxt3/src/core/nitro-legacy.ts
Following up #3222 (`extends` support progress) this PR allows extending `server/` directory for extended config layers
=> feat(nuxt3): extends support for server/ directory

examples/with-test/package.json, package.json, yarn.lock
fixes issue with yarn when releasing edge (renaming not supported)
=> chore: avoid workspace resolution for `@nuxt/test-utils`

.github/workflows/ci.yml, .github/workflows/docs.yml
Not sure if there is a reason for the current behaviour, but thought it would save some CI minutes.
This skips `build-release` job rather than just a step in the job, and doesn't run full test suite for docs changes (and vice versa).
=> ci: reduce ci running

docs/content/3.docs/2.directory-structure/10.pages.md, packages/schema/src/config/router.ts, packages/schema/src/index.ts, packages/schema/src/types/pages.ts, packages/schema/src/types/router.ts
Expose proper types from schema for router options in `app/router.options.ts` (`RouterOptions`) and possible values of `router.options` in `nuxt.config` (`RouterConfigOptions`)
Instead of `pick`, we could exclude function options but this seems safer to only pick allowed ones.
=> feat(schema): expose `RouterOptions` and `RouterConfigOptions`

docs/content/3.docs/1.usage/1.data-fetching.md, examples/use-async-data/app.vue, examples/use-async-data/server/api/hello.js, packages/nuxt3/src/app/composables/asyncData.ts
This PR adds a new `watch` option to `useAsyncData` that triggers refrash on reactivity detection. In next steps, we shall improve it using watchEffect to discover more dependencies of handler. 
Watcher is only enabled on client-side when `options.watch` is set and stop when instance (if any) unmounts.
=> feat(nuxt3):  `watch` option for `useAsyncData` to auto refresh

packages/nuxt3/src/core/app.ts
Allow overriding Vue root component (builtin: https://github.com/nuxt/framework/blob/main/packages/nuxt3/src/app/components/nuxt-root.vue) for fine-grained control over Suspense behavior.
**Note:** This is advanced functionality and experimental, use with caution! (meaning might be dropped in the final version of Nuxt 3)
Similar to Nuxt 2, we  might find a better way to allow overriding any built-in component for debugging and making Nuxt completely hackable making edge cases possible (example [nuxt-community/nuxt7](https://github.com/nuxt-community/nuxt7): It uses a completely different router and app handling still leveraging the power of Nuxt!)
Also, we could extract setup logic out of built-in `<NuxtRoot>` as a composable. Making it easier to override component, yet using Nuxt logic.
=> feat(nuxt3): allow overriding root component using `app.root.vue`

packages/schema/src/config/webpack.ts
Whilst working on https://github.com/nuxt/framework/issues/3437, I discovered the following syntax is invalid in webpack:
```vue
<style>
.app {
background-image: url('/logo.svg');
}
</style>
```
But we want this to be preserved (i.e. not included in build assets).
[**Documentation**](https://webpack.js.org/loaders/css-loader/#url)
=> fix(webpack): support absolute urls in webpack css url/import

packages/kit/src/loader/config.ts, packages/kit/src/loader/nuxt.ts, packages/test-utils/src/nuxt.ts
resolves #3262
related https://github.com/nuxt/framework/pull/3693#discussion_r828560787
If NODE_ENV is set to anything other than `development`, `nuxi dev` will build for production! This issue was because we weren't setting `dev` override and nuxt falling back to std-env to detect it.
As to fix the root-cause, kit purely depends on C12 config types to avoid creating confusing interfaces that made this issue happen.
Options of `loadNuxt` changes (rootDir => cwd, config => overides) but preserved as backward compatibility.
=> fix(kit): avoid behavior change based on NODE_ENV

examples/with-test/tests/basic.test.ts, packages/nuxi/src/commands/test.ts, packages/test-utils/build.config.ts, packages/test-utils/src/context.ts, packages/test-utils/src/nuxt.ts, packages/test-utils/src/run.ts, packages/test-utils/src/server.ts, packages/test-utils/src/types.ts
Rework of #3693
Allow testing nuxt build in development mode:
- Add new `dev` option to test utils
- Support `--dev` and `--watch` to `nuxi test`
- Add new `isDev()` utility from `@nuxt/test-utils` to check if testing in development environment
- Directly use nitro server listener
- (prod) Inherit stdio for process
To be improved: Wating for loading is via a loop to fetch and check payload. We could improve state management (hooks are unreliable for this since both nitro and vite need to be done) (~> #730)
Try: `yarn nuxi test examples/with-test --dev`
=> feat(test-utils): test in development mode

packages/nuxt3/src/core/builder.ts
resolves #3759
This adds a better error when `@nuxt/webpack-builder` can't be resolved in the project.
```
ERROR  Cannot start nuxt:  [nuxt] Could not load @nuxt/webpack-builder. Is it in your project dependencies?        09:42:31
at bundle (packages/nuxt3/src/core/builder.ts:64:13)
at async build (packages/nuxt3/src/core/builder.ts:30:5)
at async Promise.all (index 1)
at async load (packages/nuxi/src/commands/dev.ts:53:9)
at async Object.invoke (packages/nuxi/src/commands/dev.ts:97:5)
at async _main (packages/nuxi/src/cli.ts:37:7)
```
=> fix(nuxt3): warn if builder can't be loaded

packages/nitro/src/build.ts
Regression in https://github.com/nuxt/framework/pull/3717. Root package server dir was included twice here (though removed elsewhere).
=> fix(nitro): don't include current project's layer twice

packages/nuxt3/src/components/loader.ts, packages/nuxt3/src/components/scan.ts
resolves #3678, resolves https://github.com/nuxt/framework/issues/3739
* Vue can call resolveComponent more than once when kebab + pascal case are both used in template. This deduplicates imports with a Set.
* We also convert to pascal case when resolving as there is an edge case with numbers and the following are all valid ways of referring to the same component in Vue: `<Oscars2022>`, `<oscars-2022>` and `<oscars2022>`
* I also spotted an opportunity to use the helper function from Vue 3 rather than a copy of it.
=> fix(nuxt3): improve component loading behaviour

docs/content/3.docs/2.directory-structure/10.pages.md
resolves #3797
This PR adds a couple of links to the Vue API for details on what can be passed to keepalive & transition props.
=> docs: add links to vue api for transitions + keepalive props

docs/content/3.docs/2.directory-structure/4.components.md, packages/schema/src/config/_common.ts
resolves #3829
There is now no concept of runtime vs build-time module, so it makes sense to deprecate `buildModules` as an option in Nuxt config for Bridge and Nuxt 3. Possible future enhancement - use schema
=> docs: deprecate `buildModules` in schema

docs/content/3.docs/2.directory-structure/4.components.md, packages/nuxt3/src/auto-imports/presets.ts, packages/nuxt3/src/components/loader.ts, packages/nuxt3/src/components/templates.ts, packages/schema/src/config/_adhoc.ts
for example, https://github.com/nuxt/framework/issues/3672 - though not marking as resolving it as we may also wish to globally register `NuxtLink`
This PR:
* adds components and autoImports keys to `nuxt.config` documentation
* supports auto-loading `Lazy`-prefixed components
* adds type-hinting for `Lazy`-prefixed components
* supports custom resolving components with `resolveComponent` (to allow users to do more elaborate dynamic components without needing to set `global: true`, which can have a negative performance effect). See https://github.com/nuxt/framework/issues/3672 for example.
=> feat(nuxt3): support auto-loading lazy and custom-resolved components

packages/vite/src/plugins/dynamic-base.ts, packages/vite/src/server.ts, packages/vite/src/vite.ts
Regression from https://github.com/nuxt/framework/pull/3757. Prints out the following harmless warning:
```bash
WARN  [SSR] Error transforming virtual:/playground/.nuxt/paths.mjs: Failed to resolve import "#_config" from "virtual:/playground/.nuxt/paths.mjs". Does the file exist?
at formatError (node_modules/vite/dist/node/chunks/dep-9c153816.js:38098:46)
at TransformContext.error (node_modules/vite/dist/node/chunks/dep-9c153816.js:38094:19)
at normalizeUrl (node_modules/vite/dist/node/chunks/dep-9c153816.js:69819:26)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async TransformContext.transform (node_modules/vite/dist/node/chunks/dep-9c153816.js:69959:57)
at async Object.transform (node_modules/vite/dist/node/chunks/dep-9c153816.js:38334:30)
at async doTransform …
```
=> fix(vite): resolve '#_config' in base plugin

packages/nuxt3/src/core/templates.ts
This is an oversight from https://github.com/nuxt/framework/pull/3757 - we are not using this import.
=> fix(nuxt3): avoid `#_config` app import in dev mode

docs/content/1.getting-started/3.bridge.md, packages/bridge/src/runtime/app.plugin.mjs
resolves #2037
resolves https://github.com/nuxt/framework/issues/3431
This PR adds some protections against double installing plugins, components, etc. - and also a warning to avoid this usage in bridge without adding protection.
=> fix(bridge): don't double-install plugins when using compat `vueApp.use`

packages/nuxt3/src/core/app.ts, packages/nuxt3/src/pages/utils.ts
Improves types for the `uniqueBy` utility function, enabling autocompletion on second parameter `key` 😎
@pi0 This utility being used at two places in the same package (**nuxt3**), I'll let you refactor it to only define it once somewhere :)
=> fix(nuxt3): improve types of `uniqueBy` utility

packages/nuxt3/src/pages/utils.ts, test/basic.test.ts, test/fixtures/basic/pages/another-parent.vue, test/fixtures/basic/pages/another-parent/index.vue, test/fixtures/basic/pages/parent.vue, test/fixtures/basic/pages/parent/index.vue
Uniqueness by `name` was a mistake has multiple routes may have `name === undefined` (parents of sub routes).
Routes must be unique by their `path`.
Resolves #3892
=> fix(nuxt3): use `path` for uniqueness of routes when resolving

packages/bridge/src/app.ts, packages/bridge/src/runtime/capi.plugin.mjs, packages/bridge/src/runtime/vue2-bridge.d.ts, packages/bridge/src/runtime/vue2-bridge.mjs, packages/bridge/src/vite/vite.ts, packages/bridge/src/vue-compat.ts, packages/nitro/src/rollup/config.ts, test/bridge.test.ts, test/fixtures/bridge/pages/index.vue
partially: https://github.com/nuxt/framework/issues/3221
We've had a number of issues associated with re-aliasing `vue` itself. This PR instead uses a transform plugin to ensure that code like `import Vue, { ref } from 'vue'` will continue to work.
We also add types via module augmentation of `vue`, which should be a more resilient approach (e.g. https://github.com/nuxt/framework/issues/1831).
This also would be more compatible with moving `vue` to an external (which we may do subsequently).
=> refactor(bridge): provide vue2 compat with a transform plugin

packages/nuxt3/src/meta/runtime/plugin.ts
follow up on https://github.com/nuxt/framework/pull/3898
this defines the meta mixin outside the plugin so we can add the installed flag in bridge...
=> fix(bridge): define mixin outside plugin, to avoid memory leak

packages/nuxt3/src/meta/runtime/plugin.ts
resolves  #3904
We don't need to call `useNuxtApp` (and indeed cannot) if there is no instance.
=> fix(bridge): don't call nuxt app if instance is inaccessible

docs/content/3.docs/2.directory-structure/10.pages.md, packages/schema/src/config/router.ts, packages/schema/src/types/router.ts
Resolves #3960
- Use `Omit` instead of `Exclude`
- Make interface partial as is only for config
- Use `RouterConfig` instead of `RouterOptions` to follow convention we use for partial configs. (`RouterOptions` deprecated)
- Rename internal `RouterConfigOptions` to `RouterConfigSerializable` for clarity
- Update docs
=> fix(schema): fix RouterConfig types

packages/vite/src/runtime/server.mjs, packages/vite/src/vite-node.ts
#3598
- Use process.env to pass server URLs instead of file replacement. 
- Improved manifest generation. 
- Fix root options for vite node runner
=> fix(vite-node): improve server.mjs

docs/content/3.docs/1.usage/8.cli.md, packages/nuxi/src/commands/dev.ts
resolves https://github.com/nuxt/framework/issues/3958
Although not strictly a bug, it can be confusing for users for dev + server to have different env variables affecting port + host.
=> fix(nuxi): respect `NUXT_PORT` and `NUXT_HOST` vars in dev mode

packages/vite/src/runtime/server.mjs
Fixes https://github.com/nuxt/framework/pull/3974#issuecomment-1084166442
`process.server` was `undefined` so it resolved to the client entry and caused loaded app is an function instead of a server-rendered app. 
This only happens on the stub mode of development, but not the production build.
TBH I am not sure why it's happening and if this is the correct fix.
=> fix(vite-node): wrong entry been resolved in stub mode

docs/content/3.docs/1.usage/1.data-fetching.md, packages/nuxt3/src/app/composables/asyncData.ts, packages/nuxt3/src/app/composables/fetch.ts, playground/app.vue
Both `useFetch` and `useAsyncData` avoid fetching twice at the same time when a promise is running but skip any value in payload cache for **initial refrash**. A simple way to reproduce behavior:
```vue
<script setup lang="ts">
await useFetch('http://icanhazip.com', { key: 'test' })
await useFetch('http://icanhazip.com', { key: 'test', server: false })
</script>
```
The script above, causes another client-side fetching on initialization, despite the fact that we already have the same key in payload cache. There are other situations where this happens as well, including fetching in multiple components when a race-condition can happen for fast fetches.
This PR changes the default behavior to **use payload cache for initial fetch** when exists. Running the above example, will not cause …
=> feat(nuxt)!: use paylod cache for initial data fetching by default

packages/vite/src/vite.ts
Current new builds are failing with white screen & hydration error (but only on the first run of Nuxt). This is because vite doesn't know to optimize vue so the vue imported by `@nuxt/ui-templates/templates/welcome.vue` is a different vue from the one used in the rest of the app. After the first run, vue is optimized and you have to delete `node_modules/.vite` to trigger error again.
Reproducible https://stackblitz.com/edit/github-ndg68p?file=package.json&terminal=dev
=> fix(vite): optimise `vue` by default

packages/nuxi/src/commands/dev.ts
resolves https://github.com/nuxt/framework/issues/3675
resolves https://github.com/nuxt/framework/issues/3883
may resolve some of the issues reported in https://github.com/nuxt/framework/issues/3147, for example https://github.com/nuxt/framework/issues/3147#issuecomment-1060124361
Previously we were checking a string like `C:\\test\\.nuxt\\somefile.js` against `C:\\test\\.nuxt/` which would of course never match, meaning on Windows dev servers were immediately interrupting themselves and restarting when they noticed changes in `.nuxt`.
=> fix(nuxi): ignore buildDir on windows too

docs/content/3.docs/1.usage/8.cli.md, packages/nuxi/package.json, packages/nuxi/src/commands/preview.ts, yarn.lock
resolves https://github.com/nuxt/framework/issues/3621
This loads `.env` in `nuxi preview`.
=> feat(nuxi): load `.env` when previewing builds

packages/bridge/src/auto-imports.ts
https://github.com/nuxt/framework/issues/3904#issuecomment-1085717954
Seems we neglected to add `defineNuxtLink` to unsupported autoimports in Bridge.
=> fix(bridge): remove `defineNuxtLink` from auto-imports

packages/kit/src/context.ts, packages/kit/src/ignore.ts, packages/kit/src/module/define.ts, packages/kit/src/resolve.ts
Usage of `useNuxt()` was unguarded in nuxt kit about context unavailability. Introducing new `tryUseNuxt` for guarded places and directly throwing an error for `useNuxt` when context is unavailable to avoid cascading issues.
Upstream improvement: https://github.com/unjs/unctx/issues/6
=> fix(kit): ensure `useNuxt` returns nuxt instance

packages/bridge/src/transpile.ts, packages/bridge/src/vite/server.ts, packages/nuxt3/src/core/modules.ts
resolves  #3221
Having looked at this, #3221 is not actually a shortcoming in `externality`. It's more that `@nuxt/bridge` (which is what we add to the transpile array) is a stub that re-exports `@nuxt/bridge-edge`. pnpm doesn't nest this under `@nuxt/bridge` so there's nothing to match against.
So this PR isn't a workaround as such, but probably the correct solution.
=> fix(bridge): transpile `@nuxt/bridge-edge`

packages/nuxt3/src/app/composables/asyncData.ts
resolves https://github.com/nuxt/framework/issues/4053
resolves https://github.com/nuxt/framework/issues/4027
We never run the refresh if we already have data present, meaning previously `pending` was getting stuck in the true position.
=> fix(nuxt3): set pending to false when using cached data

packages/nuxt3/src/pages/runtime/router.ts
resolves #4086, resolves https://github.com/nuxt/framework/discussions/2459
This PR does two things:
1. correctly resolves the route for use within plugins (previously `useRoute()` did not return the correct route until the plugin lifecycle had fully run)
2. creates a 'suspended' route that mirrors the behaviour of the page component - so it does not resolve to the new route until the page component resolves
I would especially welcome testing on this given the nature of the change.
=> fix(nuxt3)!: sync route object to currently resolved page

packages/vite/src/utils/warmup.ts
The original warm-up will only warm up the entry module, due to two issues:
- `server.moduleGraph.urlToModuleMap.get(url)` does not hit because we are warm-up with unresolved URLs, while `urlToModuleMap` stores resolved absolute URL. Use `getModuleByUrl(url)` will let Vite handles the normalization and matching.
- Since the introduction of VFS for internal modules, the URL gets appended with `/@id/__x00__` for browser compatibility, while the plugin still expects the id starts with `\0`, causing the `transformRequest` to return `undefined` and failed to identify it's dependencies (that means, all Vue components and user code)
This PR improves the warm-up logic, and also fixes the FOUC problem of `vite-node` and #3968
=> fix(vite): improve warmup

packages/nuxt3/src/components/loader.ts
resolves #3849
resolves #3340
We use `?macro` for HMR updates to components. This PR ensures that we apply the components transform to these HMR updates just as we do for auto-imports:
https://github.com/nuxt/framework/blob/cb6a4e97c1146ab9e35e979837b6d8aa30de8390/packages/nuxt3/src/auto-imports/transform.ts#L13-L28
=> fix(nuxt3): parse macro queries for components

packages/vite/src/plugins/dynamic-base.ts, packages/vite/src/server.ts
This tidies up the following generated code:
```diff
- const logo = buildAssetsURL("/__NUXT_BASE__/logo.148d9522.svg".replace("/__NUXT_BASE__", ""));
+ const logo = buildAssetsURL("logo.148d9522.svg");
- const _imports_1 = `${publicAssetsURL()}public.svg`;
+ const _imports_1 = publicAssetsURL(`public.svg`);
```
(We can't do this in the transform step as vite does a straight replacement of the asset id after this point.)
=> fix(vite): clean up dynamic paths

docs/content/3.api/1.composables/use-async-data.md, packages/nuxt3/src/app/composables/asyncData.ts, test/fixtures/basic/types.ts
Let `useAsyncData()` return value that `error` can defined type by generics, like below:
```ts
const { data, error } = useAsyncData<TData, TError>(() => fetch('url'))
```
=> feat(nuxt3): let `useAsyncData()` return value that `error` can defined type by generics

packages/nuxt3/src/core/builder.ts
resolves #4030
Yet another issue triggered by `\` vs `/`. Source issue is here:
https://github.com/nuxt/framework/blob/dda0cebc761c00042ad82bb4c2a47b679581755a/packages/nuxt3/src/pages/module.ts#L40-L43
But I've fixed by normalising upstream (before we call nuxt hook), to help avoid similar issues in future.
=> fix(nuxt3): normalize watched paths

packages/bridge/src/app.ts
resolves #4094
Previously with npm (but not yarn or pnpm) vue@3 was being resolved by the import in `vue2-bridge` (see https://github.com/nuxt/framework/pull/3886), because vue@3 was being installed, nested under `@nuxt/bridge` in `node_modules`. This PR instead moves that template to `.nuxt` so we can benefit from resolving `vue` from the user's root (that is, vue@2).
=> fix(bridge): resolve vue from `.nuxt`, not `node_modules`

docs/content/2.guide/3.directory-structure/6.layouts.md
=> docs: add note that layout root cannot be `<slot />`

packages/kit/src/server.ts, packages/vite/src/vite-node.ts
This PR will improve compatibility with Nitropack and internal usage of `addServerMiddleware` .
As Nitropack uses `route` and `handler` for middleware, I assume `path` and `handle` will be deprecated.
=> fix(kit): use `route` instead of `path` in `ServerMiddleware`

packages/bridge/src/auto-imports.ts
resolves #4120
Imports from presets weren't being passed at `autoImports:extend` as this was only for dynamic imports.
=> fix(bridge): exclude unsupported imports via `autoImports:sources`

packages/nuxt3/src/app/composables/cookie.ts
resolves #4018
This defaults cookie path to app's baseURL (though we could instead set it to `/` by default if there's a reason)
=> fix(nuxt3)!: add default cookie path to `/`

packages/webpack/src/presets/style.ts
As css-loader documentation says, for css modules pre-rendering with `mini-css-extract-plugin` we should use `modules.exportOnlyLocals: true` in server build.  
https://webpack.js.org/loaders/css-loader/#exportonlylocals
=> fix(webpack): add `exportOnlyLocals: true` for css modules options in server build.

docs/content/3.api/3.utils/abort-navigation.md
#4104 
This PR documents the `abortNavigation()` API
=> docs(api): specify abortNavigation API

packages/nuxi/src/cli.ts, packages/nuxi/src/commands/dev.ts, packages/nuxi/src/commands/index.ts, packages/nuxi/src/commands/test.ts
In order to avoid hanging CLI due to open listeners, this change will force close CLI's process after invocation is done. `dev` and `test` commands opt out by returning `true` as invocation result.
=> fix(cli): close process by default after command invokation

packages/nuxt3/src/head/runtime/lib/vueuse-head.plugin.ts
resolves #4258
This resolves the regression for computed metadata (which worked before https://github.com/nuxt/framework/pull/4221).
=> fix(nuxt3): re-enable computed metadata in useHead

packages/nuxt3/src/app/nuxt.ts, packages/nuxt3/src/core/runtime/nitro/renderer.ts
With changes of #4254, we introduced `.public` to the runtime config but it was being flattened when using `useRuntimeConfig` on the client-side. This makes `useRuntimeConfig` returned interface identical between client-side and server-side.
Previously (client-sie code)
```js
// nuxt.config
publicRuntimeConfig: {
test: 123
}
```
```js
// usage
useRuntimeConfig().test
```
Using new `runtimeConfig`:
```js
// nuxt.config
runtimeConfig: {
public: {
test: 123
}
}
```
```js
// usage
useRuntimeConfig().public.test
```
=> fix(nuxt3)!: preserve runtime-config structure for client-side

packages/bridge/src/runtime/composables.ts, packages/nuxt3/src/app/nuxt.ts
…n client
Context: https://github.com/nuxt/framework/pull/4254, https://github.com/nuxt/framework/pull/4267
This PR allows `useRuntimeConfig()` in the client-side to be used with compatible access from top-level keys to read or update public config. Data will be asynced with `.public` namespace.
=> fix(bridge, nuxt3): backward compatibility to access runtime config in client

docs/content/2.guide/1.concepts/1.introduction.md
The page https://v3.nuxtjs.org/guide/concepts/introduction/ has "Server engine: @nuxt/nitro" linked to https://github.com/nuxt/framework/tree/main/packages/nitro which doesn't exist anymore. The repo is now available at https://github.com/unjs/nitro (thanks daniel for guiding me there)
Not sure if we should change the url text to "Server engine: unjs/nitro" as well?
=> docs: update url to new unjs/nitro repo

docs/content/3.api/1.composables/use-fetch.md
This PR applies the same structure to `useFetch` API reference than to `useAsyncData`:
- Type
- Params
- Return Values
- Example
=> docs(api): apply use-async-data page structure to use-fetch

packages/nuxt3/src/pages/module.ts, packages/schema/src/config/_adhoc.ts
resolves #2277
This PR allows manually setting `nuxt.options.pages` to `true` or `false` to force enable or disable the ad-hoc module.
=> feat(nuxt3): allow manually enabling/disabling the ad-hoc pages module

docs/content/3.api/1.composables/use-async-data.md, docs/content/3.api/1.composables/use-cookie.md, docs/content/3.api/1.composables/use-state.md, packages/nuxt3/src/app/composables/asyncData.ts, packages/nuxt3/src/app/composables/cookie.ts, packages/nuxt3/src/app/composables/state.ts, packages/nuxt3/src/app/composables/utils.ts, test/fixtures/basic/types.ts
resolves #2210
This PR allows the default values for `useCookie`, `useState`, `useAsyncData` and `useFetch` to return a ref, which will be reused in the composable rather than recreated.
So, for example:
```js
const someRef = ref('test value')
const cookie = useCookie('value', () => someRef)
console.log(someRef === cookie) // true
```
However, this is to enable advanced use cases only and users should not assume that the factory function will be run. In many cases the factory function is not run, such as when state is deserialized from payload.
=> feat(nuxt3): allow providing a ref as default value

package.json, packages/nuxi/build.config.ts, yarn.lock
There was a recent bug with cjs bridge feature of unbuild (fixed by https://github.com/unjs/mlly/pull/43) but I also found we no longer require mocking __filename/__dirname/require for nuxi bundle output thanks to more esm dependencies. It is safer to disable this.
=> fix(cli): disable cjs bridge

packages/nuxi/src/commands/dev.ts
resolves #3835
This is a tricky one. Current behaviour is that the `listen` hook only runs once, and it's called by `nuxi`. Even when Nuxt restarts, the same listener persists, so on one level, it makes sense to call it once.
However, modules and other nuxt context re-initialises so it probably makes sense to re-call this hook on each reinitialisation of nuxt.
We might also consider adding functionality to allow users to hook into the Nitro dev server, which might mean this PR is unneeded.
Context: https://github.com/nuxt/framework/pull/2772
=> fix(nuxi): call listen on each nuxt restart

packages/nuxt3/src/core/nitro.ts
Nitro adds `/` to the routes list by default (https://github.com/unjs/nitro/blob/ba3323e07fa8429f88b8d55ae5e61d4131c584f1/src/prerender.ts#L13) but if we add a custom prerender route, this will be disabled. 
This PR makes sure that with `nuxi generate` we always crawl `/` route. Also only includes (legacy) `generate.routes` for generate command not for normal `nuxi build` as hybrid routes.
=> fix(nuxt3): always generate `/` route

packages/nuxt3/src/pages/runtime/page.ts
This wraps the suspense for child routes into it's parent, which means `page:finish` is now accurate (it means all route components have been fully resolved). However, it's a breaking change in that the hook is now only called _once_, with the top-level route component.
The `page:start` and `page:finish` hooks are now only called _once_, with the top-level route component rather than any nested route components.
=> fix(nuxt3)!: include route children in parent suspense

packages/nuxt3/src/pages/runtime/router.ts
resolves #4417
`ssrContext.req.url` displays the full error handler URL rather than the cleaned-up version. This PR changes it to use the path that the error handler is invoked for.
=> fix(nuxt3): initialise router with normalised url

packages/schema/src/config/_common.ts, packages/schema/src/config/build.ts, packages/schema/src/config/generate.ts, packages/schema/src/config/router.ts
resolves #4112
This PR resolves an issue accessing the default value of `app.buildAssetsURL`.
=> fix(schema): use entire object for `app` properties

packages/nuxt3/src/app/composables/cookie.ts, packages/nuxt3/src/app/composables/router.ts, packages/nuxt3/src/app/nuxt.ts, packages/nuxt3/src/app/plugins/router.ts, packages/nuxt3/src/pages/runtime/router.ts
resolves #4244
This PR improves a number of things around cookies + redirect lifecycle:
1. it always sets a cookie value (not only if the value has changed) - let me know if I should revert this @pi0 but it seems that I would expect `useCookie('test', { default: () => 'value' })` to set a value on the initial SSR load.
2. it adds an additional `app:redirected` hook for setting final headers etc. in case of redirect (in which case there is no `app:rendered` to hook into
3. we use `navigateTo` helper within router plugins so there's a central place for setting the redirect
4. we accept an optional `redirectCode` via `navigateTo` options (defaulting to 301, which is a technical change from h3 default value of 302, but the same as the previous router plugin implementation)
=> fix(nuxt3): improve redirect lifecycle

packages/nuxt/src/components/loader.ts
resolves #4445
Issue was the _order_ of the component loader plugin vs auto-imports plugin. But it's safer not to depend on auto-imports within components loader, so added explicit import instead.
=> fix(nuxt3): don't rely on auto-imports for `defineAsyncComponent`

docs/content/2.guide/2.features/10.runtime-config.md
resolves #4458
https://github.com/nuxt/framework/pull/4459#discussion_r854185877
=> docs: add note about runtime config fallback

packages/nuxi/src/commands/analyze.ts
We need to return 'wait` in order for Nuxt to not kill the analyze command starting a server.
=> fix(nuxi): don't kill analyze command

packages/nuxt/src/core/nitro.ts
https://github.com/nuxt/bridge/pull/316
We hard-coded `public` when processing layers.
=> fix(nuxt3): respect custom public dir in layers

docs/content/1.getting-started/2.migration.md
The last icon from "Static sites" and "Nuxt 3" the "Experimental" text was missing
In the docs of migration a text was missing. When I read it, the "experimental" features was not clear so I just add the text of "Experimental" to make it clear. Like it is 2 line above.
=> Docs: "Experimental" text was missing

packages/vite/src/plugins/virtual.ts
resolves  #454, resolves #2635
Starting the prefix with `\0` seems to short-circuit the vite/rollup transform process, meaning future transform plugins weren't being run. This change means we can process virtual files in the same way we can the rest of source materials for the build.
=> fix(vite): transform virtual templates

docs/content/3.api/1.composables/use-async-data.md
delete the duplicated `default` parameter description.
=> docs: remove duplicate entry for `default` option

docs/content/3.api/1.composables/use-cookie.md, docs/content/3.api/2.components/4.nuxt-link.md
This PR updates a few broken links for examples on StackBlitz
=> docs: update StackBlitz example links

docs/content/2.guide/5.deploy/providers/netlify.md
=> docs: improve netlify deployment

packages/nuxt/src/auto-imports/module.ts, packages/nuxt/src/auto-imports/transform.ts, packages/nuxt/src/components/loader.ts, packages/nuxt/src/components/module.ts, packages/nuxt/src/core/nitro.ts, packages/nuxt/src/core/nuxt.ts, packages/nuxt/src/core/plugins/unctx.ts, packages/nuxt/src/pages/macros.ts, packages/nuxt/src/pages/module.ts, packages/schema/src/config/build.ts, packages/vite/src/plugins/dynamic-base.ts, packages/vite/src/vite.ts, packages/webpack/src/webpack.ts
This PR disables sourcemap generation for our various transform plugins when building. (I would also be open to adding a `build.sourceMap` option that allows configuring sourcemap generation.)
I've seen one or two reports of memory issues when building, and have previously resolved this with turning off magic string sourcemaps. For context:
* https://github.com/nuxt/bridge/issues/151
* https://github.com/rollup/plugins/issues/1064
* https://github.com/Rich-Harris/magic-string/issues/195
=> feat: allow disabling sourcemap generation

packages/nuxt/src/pages/runtime/router.ts
Fix https://github.com/nuxt/framework/issues/3242
The server crashes because of uncaught promise rejection.
=> fix(nuxt): await for `router.push` on ssr

docs/content/3.api/1.composables/use-async-data.md
Fix typo and remove pick option since api will return and array of mountains
=> docs(api): fix `useAsyncData` example

docs/content/2.guide/3.directory-structure/6.layouts.md
resolves #4592
Adds the other half of the example.
=> docs: add layout to match custom header example

packages/nuxi/src/utils/prepare.ts
resolves #4572
Previously we were stripping anything extension-like from a path, which also covered directories like `app.com`. This PR strips file extensions only if it's not a directory.
When we bump minimum node version to 14.17 then we could also use `throwIfNoEntry: false`.
=> fix(nuxi): don't strip file extensions from dirs in `tsconfig`

docs/content/2.guide/1.concepts/2.vuejs-development.md
Changes the phrasing of a sentence on the 'Vue.js development' page in the 'concepts' section to be more grammatically correct.
=> docs(concepts): change phrasing

docs/content/2.guide/1.concepts/1.introduction.md, docs/content/2.guide/1.concepts/2.vuejs-development.md, docs/content/2.guide/1.concepts/3.rendering.md
N/A
While going through the Nuxt 3 docs today I came across a few minor typos.
=> docs: fix some minor typos

docs/content/2.guide/1.concepts/2.vuejs-development.md
According to [https://vuejs.org/guide/scaling-up/sfc.html](https://vuejs.org/guide/scaling-up/sfc.html)
=> docs: fix typo

docs/content/2.guide/2.features/4.head-management.md
- [ x] 📖 Documentation (updates to the documentation or readme)
I was confused when trying the second "function form" of the `titleTemplate` as follows:
```vue
useHead({
title => `My App - ${title}`
})
```
Which obviously make no sense, but it took a while to get head (Pun intended!) around the current documentation.
Maybe my change makes it clearer for others?
=> docs: make titleTemplate function form example clearer

docs/content/2.guide/3.directory-structure/10.pages.md
The rest of documentations after "Dynamic Routes" are disappeared
=> docs: fix edge alert syntax

docs/content/migration/8.runtime-config.md
The migration guide still mentioned the deprecated `publicRuntimeConfig` and `privateRuntimeConfig`, this is changed to the new `runtimeConfig`.
=> docs(migration): update to use new `runtimeConfig`

docs/content/2.guide/1.concepts/2.vuejs-development.md, docs/content/2.guide/5.deploy/providers/netlify.md, docs/content/2.guide/6.going-further/5.esm.md, docs/content/5.community/3.contribution.md, docs/content/migration/20.module-authors.md
`~/docs/content/2.guide/1.concepts/2.vuejs-development.md`
-With Vue 3 and Nuxt 3, a focus has been put on bundle size reduction. With version 3, most of Vue’s functionality, including template directives and built-in components, is tree-`shakeable`. Your production bundle will not include them if you don’t use them.
+With Vue 3 and Nuxt 3, a focus has been put on bundle size reduction. With version 3, most of Vue’s functionality, including template directives and built-in components, is tree-`shakable`. Your production bundle will not include them if you don’t use them.
=> docs: fix typos

packages/nuxt/src/pages/runtime/page.ts
resolves https://github.com/nuxt/framework/issues/4556
Context: https://github.com/nuxt/framework/pull/4422.
This PR amends that behaviour. Initial load still includes children in the parent's suspense, but further navigation wraps child pages in suspense (which is required if not reloading the parent on further nav).
**Note**: `isHydrating` is not reactive so it doesn't trigger a rerender.
=> fix(nuxt): use suspense for child pages on client-side navigation

docs/content/2.guide/2.features/10.runtime-config.md
https://github.com/nuxt/framework/discussions/4682#discussioncomment-2662151
Small note that `.env` is not read in production
=> docs: add note that `.env` is not read in production

packages/nuxt/src/head/module.ts, packages/nuxt/src/head/runtime/plugin.ts
resolves #4426, resolves https://github.com/nuxt/framework/issues/4630
In general using reactive objects outside of a Vue context is dangerous. This PR marks the nuxt configuration head inserted by Nuxt as non-reactive, which avoids a memory leak, as well as tidying up a bit of leftover bridge compatibility.
There seems ample space here for future improvement as well, including:
* identifying if there's something in `vueuse/head` implementation (or in our practice of reffing up the head values)
* detecting if `useHead` is being called outside of a vue context (that is, in a plugin) and marking entries as non-reactive if they aren't already refs/reactive.
=> fix(nuxt): mark config head as non-reactive

packages/nuxt/src/core/runtime/nitro/error.ts
createError does not return data #4728
The current error `errorhandler` implementation does not put the data object into the response. By adding the `data` object received from the `_error` object to the `errprObject` we can add the data to the response. This fixes #4728.  
It is not required to check if the object exists, as it will automatically not be appended to the `errorObject` if it is undefined.
=> fix(nuxt): preserve `error.data` in response

packages/nuxt/src/app/composables/router.ts, packages/nuxt/src/pages/runtime/router.ts
#4778
Reproduction: https://stackblitz.com/edit/nuxt-starter-mc3z36
We detect redirection happens when after router middleware, initialURL is mismatching current route's fullPath. While initialURL from req.url is `/`, `fullPath` is an empty string due to a vue-router bug. Additionally, I've added `''` to `'/'` fallback for `navigateTo` to ensure this issue won't happen in other places when calling `router.resolve` 
Other than workaround for upstream issue, this PR tries to improve path compare to avoid unnecessary navigations.
=> fix(nuxt): ensure url is not empty string

packages/nuxt/src/core/nitro.ts
resolve #4829 
rollup config is undefined and the import plugin registration is trying to push the plugin into an empty array [here](https://github.com/nuxt/framework/blob/2cc336d3a38cf748073241cb0f27f631c44a27fa/packages/nuxt/src/core/nitro.ts#L118).
fixed by setting 
````ts
rollupConfig: {
plugins: []
}
````
into `nitroConfig` at `package/nuxt/core/nitro.ts`
=> fix(nuxt) : add default value for `nitro.rollupConfig.plugins`

docs/content/2.guide/6.going-further/2.hooks.md
N/A
- The App Hooks (runtime) [Usage WIth Plugins](https://v3.nuxtjs.org/guide/going-further/hooks#usage-with-plugins) example is syntactically invalid (missing brackets etc)
- I have updated the example with one which is valid and can be copied and pasted.
=> docs: fix example runtime hook plugin syntax

packages/nuxt/src/app/plugins/router.ts, packages/nuxt/src/pages/runtime/router.ts
currently `route.fullPath` is `/` on server and `http://localhost:3000/` on client. This implements same behaviour as on router, which also fixes an issue where baseURL wasn't being correctly handled with universal router:
https://github.com/nuxt/framework/blob/ebc27ce997c80f5c30fc56ad82b02785fdf482bc/packages/nuxt/src/pages/runtime/router.ts#L30-L49
=> fix(nuxt): normalise window location for universal router

packages/nuxt/src/auto-imports/transform.ts, packages/nuxt/src/components/loader.ts, packages/schema/src/types/components.ts, packages/schema/src/types/imports.ts
Allowing auto import / components to work with custom extension files.
=> feat(auto-import): custom include option

docs/content/2.guide/2.features/5.data-fetching.md
* The [Refreshing Data](https://v3.nuxtjs.org/guide/features/data-fetching#refreshing-data) example talks about `useFetch()` composable not `useAsyncData()` composable.
* The return value that indicates the pending status is `pending` not `loading`.
I suggest if we add some words that say we can use `refresh` method returned from all data fetching composable. It will help provide better understanding, the first time I read the example, I thought the `refresh` method is returend only by `useFetch()` 😉
The docs example would be like:
> You can make use of the `refresh()` method returned from the  `useFetch`, `useLazyFetch`, `useAsyncData` and `useLazyAsyncData` composables to refresh the data with different query parameters:
=> docs(data-fetching): fix and improve example

packages/nuxt/package.json, packages/nuxt/src/core/nitro.ts, yarn.lock
- Add missing `@nuxt/devalue` dependency (was implicit dependency of nitropack 0.3.x)
- Register `serverMiddleware` from nuxt config as middleware handlers (this can be a breaking change if you was depending on routing using serverMiddleware)
- Check out [unjs/nitro@v0.4.0](https://github.com/unjs/nitro/releases/tag/v0.4.0) release notes. There are internal breaking changes.
=> feat(nuxt)!: upgrade `nitropack` to `0.4.x`

packages/nuxt/src/core/templates.ts, packages/schema/src/types/config.ts
resolves #4550
This PR restores the `PublicRuntimeConfig` interface, as a vehicle for augmenting types for runtimeConfig['public'] which otherwise can't really be done. (Otherwise each augmentation would completely override the type of `public`.)
Particularly value your input @pi0 as you touched this last.
=> fix(schema): add back `PublicRuntimeConfig` interface for augmentation

packages/nuxt/src/core/nitro.ts, packages/vite/src/server.ts
resolves #4901
We shouldn't need nitro to transpile these (or we actually end up with duplicates in the server bundle.
=> fix(nuxt): configure vite to transpile nuxt

packages/nuxt/src/app/composables/router.ts, packages/nuxt/src/app/plugins/router.ts, test/basic.test.ts, test/fixtures/basic/pages/navigate-to.vue
resolves #4932
This PR:
* uses baseURL when pushing with universal router (fixing an unreported error)
* uses baseURL when sending a redirect
=> fix(nuxt): respect baseurl when redirecting (and universal router)

packages/nuxt/src/pages/runtime/router.ts
resolves #4865 
This PR moves 404 handling to _after_ user middleware runs, meaning the user has a chance to redirect or handle it in other ways.
=> fix(nuxt): check for 404s after user middleware

packages/vite/package.json, packages/vite/src/vite.ts, yarn.lock
#1922, closes #4916
This PR replaces references to `global` with `globalThis` for ESM compatibility, following the implementation in Nitro (e.g. https://github.com/unjs/nitro/pull/155 - which makes it safer to do this).
This is currently a draft pending more testing (e.g. for AWS Amplify).
=> feat(vite): replace `global` with `globalThis`

packages/nuxi/src/commands/dev.ts
resolves #4898
At the moment the creation of any `pages`, `composables` or `components` directory will trigger a reload, even deeply nested.
This PR resolves them to ensure we're not needlessly reloading nuxt.
=> fix(nuxi): only reload for top level dirs

packages/vite/src/vite-node.ts
=> fix(vite): add `file://` protocol to `vite-node` entry file path

packages/schema/src/config/_common.ts, packages/schema/src/config/server.ts
resolve #4987
Correction of parentheses for auto-generated documentation.
=> docs: add missing parentheses in  the `alias` example

docs/content/2.guide/2.features/5.data-fetching.md
https://github.com/nuxt/framework/discussions/3414
This adds a brief note to answer what the difference is b/t useFetch and useAsyncData, and switches the order of them in the docs.
=> docs(data-fetching): add note about difference between `useFetch` and `useAsyncData`

docs/content/3.api/1.composables/use-fetch.md
Added useFetch API documentation for **Request body** option.
Changed useFetch Params documentation for **Options** to mention which types it extends.
=> docs(api): improve `useFetch` docs for body type and additional ohmyfetch options

docs/content/1.getting-started/1.quick-start.md
In regard to the Node.js version - will 'version 14 or above' be sufficient to state (depends on whether v17 and v18 is officially supported)?
=> docs: minor improvements for the quick start section

docs/content/2.guide/3.directory-structure/7.middleware.md
Related and resolves partially: #5041
Adds info about the `NavigateToOptions` for `navigateTo`. Also removes the info that it can only be called on client side.
=> docs(middleware): add `navigateTo` options

examples/composables/use-state/app.vue
Add another counter instance with the same id and show that they change in parallel
=> docs: demonstrate the multiple `useState` with same key

packages/nuxt/src/pages/runtime/router.ts
resolve #4920 
#4920 
Using the force option on router replace make vue router use the name key in priority to match and retrieve the router location object resulting in a redirection such as the one described in the linked issue. We should just remove the name key from the object passed to router.replace when using force: true
=> fix(nuxt): fix router redirection on aliased page

packages/schema/src/config/_app.ts
When setting up CDN configuration Nuxt parses the value of `NUXT_APP_CDN_URL`, but documentation is incorrectly showing the variable as `CDN_URL`.
https://github.com/nuxt/framework/blob/cd37a21c2e98d99fd7c944986e42f2b3964da6ec/packages/schema/src/config/_app.ts#L70
> If you spot an area where we can improve documentation or error messages, please do open a PR - even if it's just to fix a typo!
Implies no issue required.
=> docs(config): correct naming of `NUXT_APP_CDN_URL` environment variable

packages/nuxt/src/head/runtime/components.ts
resolves https://github.com/nuxt/framework/issues/4779
A straightforward fix - attrs aren't meant to be passed on for these meta components.
=> fix(nuxt): allow passing extraneous attrs to meta components

packages/nuxt/src/head/runtime/plugin.ts
https://github.com/nuxt/framework/issues/4984
Previously a `titleTemplate` would only be used if there was also a `title` set (even if empty). This PR adds a basic empty title that can be overridden, meaning that titleTemplate works.
=> fix(nuxt): add default empty title to trigger `titleTemplate`

docs/content/2.guide/6.going-further/6.nuxt-app.md
N/A
Updates the nuxt app docs ~~as the link went to a 404, on closer look it seems this isn't being caught by https://github.com/nuxt/framework/blob/0cbc9cb7cdf4491fcc016138399a886867575648/docs/static/_redirects#L27~~
Update: Seems navigating through the app itself gives a 404, but going directly to the link redirects me.
1. Go to https://v3.nuxtjs.org/guide/going-further/nuxt-app/
2. Click **Read more about plugins**.
3. It 404's.
4. If you refresh the page at the 404, it'll redirect you.
=> docs: fix nuxt app guide linking to a 404 page

packages/schema/src/types/meta.ts
In fact, these properties already work but were not in the type declarations
=> fix(schema): add missed types `title`, `bodyAttrs`, `htmlAttrs`

packages/nuxt/src/app/composables/router.ts
https://github.com/nuxt/framework/issues/5041#issuecomment-1133861788
On SSR we can directly redirect within middleware when user calls `navigateTo`, which will also mean we can respect the user's options.
=> fix(nuxt): respect `navigateTo` options using server middleware in server-side

docs/content/2.guide/3.directory-structure/6.layouts.md
We ran into problems with a new Nuxt 3 project where `definePageMeta` was not working with a custom layout and we had to add `<NuxtLayout>`. I believe this was missing from the documentation, so I added it.
=> docs(guide): add use of `NuxtLayout` in `app.vue` with pages

packages/nuxi/src/commands/init.ts
see https://github.com/nuxt/framework/pull/923 & https://github.com/nuxt/framework/pull/1052
The issue was identified when using `nuxi init`, I modified the arguments incorrectly and got an error that wasn't helpful.
The PR https://github.com/nuxt/framework/pull/923 introduced a try/catch for degit cloning, it correctly showed when a user required `git` if they didn't have it installed.
The switch to tiged https://github.com/nuxt/framework/pull/1052 changed what was being caught. Tiged works without git, it will download the tarball if git isn't available. So the error message is actually catching when the repo isn't valid.
The output will now look like this:
=> refactor(nuxi): provide better advice on failing clone

docs/content/2.guide/2.features/9.server-routes.md
N/A
While reading through the documentation for Nuxt 3, I caught a small typo in the `Catch-all route` section. It's not much, but that'll be one less that the team has to find!
> For ~~Example~~ **example**, creating a file ~~in the~~ **named** `~/server/api/foo/[...].ts` will register...
[Location](https://v3.nuxtjs.org/guide/features/server-routes#catch-all-route)
=> docs: small typo in the "catch-all route" description

packages/nuxt/src/pages/runtime/page.ts
resolves #5271
This PR adds support to NuxtPage for features present in RouterView:
* updating typing to allow passing custom props (e.g. for child routes: #5271)
* passing explicit name/route props to render a specific view
It also allows RouterView to handle attrs for consistency.
=> fix(nuxt): support `RouterView` props in `NuxtPage`

docs/content/migration/7.component-options.md
Just a small typo I noticed while reading the migration docs: `${paramsÌ.id}` -> `${params.id}`.
=> docs: fix typo in component migration guide

docs/content/2.guide/3.directory-structure/10.pages.md
- [X ] 📖 Documentation (updates to the documentation or readme)
Description text for Programmatic Navigation referenced a method called "navigation", while the example method was named "navigate". Updated the description text to match the example.
=> docs: fix typo in programmatic navigation

packages/nuxt/src/app/composables/ssr.ts, packages/nuxt/src/app/entry.ts, packages/nuxt/src/app/nuxt.ts, packages/nuxt/src/core/runtime/nitro/renderer.ts
resolves #5330
This adds types to `ssrContext` (with req/res deprecated).
Relevant code changes: it also removes `redirected` (Nuxt 2, not otherwise used in Nuxt 3 codebase) and doesn't pass an empty object to initialise server entry.
=> fix(nuxt): add `ssrContext` types on `NuxtApp`

packages/nuxt/src/app/composables/asyncData.ts
Use `Pick<T, K>` only when necessary to make the type cleaner
Before
Or 
After
=> fix(types): tidy types for `useAsyncData`

docs/content/2.guide/2.features/13.modules.md, docs/content/2.guide/2.features/9.server-routes.md, docs/content/3.api/2.components/5.nuxt-error-boundary.md, docs/content/3.api/5.commands/init.md, packages/kit/src/compatibility.ts, packages/kit/src/module/define.ts, packages/nuxt/src/core/nuxt.ts, packages/vite/src/vite-node.ts, packages/webpack/src/utils/postcss.ts, packages/webpack/src/webpack.ts
It's been a while since I changed framework code, so I'm taking some time to carefully understand the latest changes, and while reading, I found some typos and very minor changes, please feel free to close this pr if it's not relevant.
=> refactor: fix typo and code improvements

packages/nuxt/src/core/plugins/import-protection.ts
resolves #5354
This removes import protection outside of `~/server/api/` and `~/server/middleware/` directories, for shared utilities.
=> fix(nuxt): relax server import protections

docs/content/2.guide/3.directory-structure/6.layouts.md
https://github.com/nuxt/framework/issues/5291
This adds a warning against using `<NuxtLayout>` as root element in page. (In this case we have a transition within a transition, which fails.)
=> docs: add warning against layout as root element

packages/vite/src/runtime/vite-node-shared.mjs
=> chore: clean up jsdoc

packages/vite/src/plugins/dynamic-base.ts, test/basic.test.ts, test/fixtures/basic/pages/assets.vue
resolves #5329
This resolves an issue where an escaped quotation was terminating a regexp wrongly.
=> fix(vite): don't terminate with escaped delimiters

docs/content/2.guide/3.directory-structure/7.middleware.md
On the https://v3.nuxtjs.org/guide/directory-structure/middleware page the links for 301 and 302 are broken.
The link was broken in the documentation 
- [* ] 📖 Documentation (updates to the documentation or readme)
- [ *] 🐞 Bug fix (a non-breaking change that fixes an issue)
The page https://v3.nuxtjs.org/guide/directory-structure/middleware shows the 302 and 301 links broken as seen below on the photo.
=> docs: fix mdn links for 301 and 302 http status

packages/nuxt/src/auto-imports/transform.ts, packages/nuxt/src/core/nuxt.ts
resolves https://github.com/nuxt/framework/issues/5414
This fixes a regression introduced by https://github.com/nuxt/framework/pull/5042, by:
1. only adding layers within `node_modules` to autoImports include.
2. not force-transforming all files in `include` but only the ones that match the test for file time
=> fix(nuxt): exclude non-cwd auto-imports and don't process _all_ files

docs/content/2.guide/3.directory-structure/4.components.md, packages/nuxt/src/components/loader.ts
resolves #5419
In some cases users may insert whitespace or a trailing comma; this updates the regexp to account for that. I've not tried to handle comments but have added a warning to the docs.
=> fix(nuxt): ignore whitespace and commas within `resolveComponent`

packages/nuxt/src/pages/macros.ts
Resolves #3488
The query `lang.jsx` of id should be at the end of id, according to https://github.com/vitejs/vite/issues/8473#issuecomment-1148715786
However `&macro=true` is added at the end so that the `lang` query is not parsed expectedly in vite plugins.
=> fix(nuxt): don't add macro query to the end of id

docs/content/5.community/4.roadmap.md
=> docs: update roadmap

docs/content/2.guide/1.concepts/2.vuejs-development.md
I've re-worded a note in the docs to flow a little nicer, and to keep it concise.
=> docs: rewrite note wording

packages/nuxt/src/core/nuxt.ts
resolves #5257
This normalises any string transpiles added by modules/user (particularly relevant for Windows support).
=> fix(nuxt): normalize string transpile paths for windows

packages/kit/src/server.ts
resolve #5020 , opened after https://github.com/unjs/nitro/pull/252 being closed  
allow the addServerHandler() helper to use the method suffix of the file path, NitroEventHandler.method will overwrite the method if defined
=> feat(kit): allow addServerHandler to use method suffix of the file path

docs/content/2.guide/2.features/4.head-management.md
https://v3.nuxtjs.org/guide/features/head-management#title-templates
=> docs: align value for defaulting the page's title with type declaration

packages/vite/src/server.ts
resolves #5109
Typo fix - it was not being added to vite config. 🤦
=> fix(vite): add typecheck to _vite_ plugins

docs/content/2.guide/6.going-further/7.testing.md
Resolves https://github.com/nuxt/framework/issues/5538
Missing `async` keyword.
=> docs(testing): fix async/await

docs/content/3.api/1.composables/use-fetch.md
N/A
To reactive re-fetch using `useFetch`, one have to use `watch` option, which is available in the code base, but not available in the document.
=> docs(api): add watch parameter in `useFetch` options

docs/content/migration/8.runtime-config.md
#5567
(alreadly closed)
There were breaking changes in runtime config specification at Nuxt3 RC.
The following page have been already fixed.
https://v3.nuxtjs.org/guide/features/runtime-config
On the other hand, the following page was not fixed, so corrected.
https://v3.nuxtjs.org/migration/runtime-config/#runtime-config
=> docs: update usage about runtime config and environment variables

packages/schema/src/config/postcss.ts
=> fix(schema, postcss): cssnano is enabled if not dev

docs/content/2.guide/1.concepts/3.rendering.md
No linked issue since it's just a minor and opinionated wording change. Feel free to close PR if you don't agree with the changes 👍 
Reading the docs, the original wording of that sentence confused me at first. I changed it to avoid repeating `to` and make it (imho) slightly simpler.
=> docs: minor wording improvements

docs/content/2.guide/1.concepts/2.vuejs-development.md
Line 103:  the route ' /api/composables/ ' results in error 404.
Suggest replacing it with ' /api/composables/use-async-data ' - it is the first page in the list of composables (see https://v3.nuxtjs.org/api/composables/use-async-data).
=> docs: replace invalid link to composables.

packages/vite/src/server.ts
Add `nuxt.ignore` list into Vite's `rollupOptions.watch.exclude` to prevent those files from being watched.
https://rollupjs.org/guide/en/#watchexclude
=> fix(vite): do not watch ignored pathes

docs/content/2.guide/2.features/4.head-management.md
Added warning about definePageMeta macro only working in pages in pages/ directory
=> docs: clarify that `definePageMeta` only works in the pages directory

packages/nuxt/src/app/components/client-only.mjs
Currently props for a client-only component (e.g. `~/components/SomeComp.client.vue`) aren't getting passed properly, because the Vue 2 signature was being used.
=> fix(nuxt): pass attrs and props to client-only components

docs/content/2.guide/1.concepts/2.vuejs-development.md
=> docs: update vuejs-development

docs/content/2.guide/2.features/10.runtime-config.md
=> docs: add full stop

packages/webpack/src/presets/base.ts
resolves #5549
We need to transpile `vue-demi` as webpack otherwise tries to resolve this externally.
=> fix(webpack): transpile `vue-demi`

packages/nuxt/src/app/composables/ssr.ts
resolves #5746
This explicitly adds `undefined` as a possible value of the return type. This will only have effect if users are using TypeScript in strict mode, as is best practice.
=> fix(nuxt): `useRequestHeaders` type should allow for undefined values

packages/nuxt/src/app/composables/fetch.ts
resolves #5690
This slightly extends the warning for `useFetch` options to include _any_ function passed to it, or also any Blob. (Though `ohash` will also throw an error if a Blob is passed.)
=> fix(nuxt): update `useFetch` key warning to include any function or blob

packages/nuxt/src/app/composables/fetch.ts
Hello.
https://github.com/unjs/destr/issues/9
This fix needed to provide custom `$fetch()` options, like a providing custom `parseResponse()` function to fix the memory leak caused by `destr()` function:
```ts
import type { FetchOptions } from 'ohmyfetch';
/**
* Parse response
* @description Replace of `destr()` function to prevent memory leak
* @param responseText
*/
const parseResponse: FetchOptions['parseResponse'] = (responseText) => {
// Send empty string if zero length
if (responseText.length === 0) {
return '';
}
try {
return JSON.parse(responseText);
} catch (_e) {
return responseText;
}
};
// Example of usage
useFetch('/', {
parseResponse,
};
```
Best wishes,
Sergey.
=> feat(nuxt): allow passing custom fetch options to `useFetch`

packages/nuxt/package.json, renovate.json, yarn.lock
for example, https://github.com/nuxt-community/sanity-module/issues/458
this is a hotfix for current vue-router build that includes `@vue/devtools-api` in its node build (see test failure in https://github.com/nuxt/framework/pull/5712).
cc: @posva
=> fix: pin vue-router to 4.0 minor branch

packages/nuxt/src/pages/module.ts
resolves #4879
This PR adds all non-dynamic routes to the prerenderer by default, as we can't always rely on the crawler to fetch every page.
=> feat(nuxt): prerender all pages by default

packages/nuxt/src/core/nitro.ts, packages/nuxt/src/core/runtime/nitro/renderer.ts
resolves https://github.com/nuxt/framework/issues/5013
resolves https://github.com/nuxt/framework/issues/4784
When server-side rendering is disabled, we do not generate `.nuxt/dist/server/index.mjs`. A guard with `NUXT_NO_SSR` environment variable was being used but it does not always works and makes issues with rollup that tries to eagerly parse the import statement.
=> fix(nuxt): use virtual server stub with `ssr: false`

packages/nuxt/src/core/plugins/tree-shake.ts
Fixes a bug introduced in composable tree-shaking regexp. Also implemented in #5750 but if that's pending we should merge this hotfix sooner.
=> fix(nuxt): don't return stub function from tree-shaken composables

packages/test-utils/src/run.ts
=> fix(test-utils): upate vitest import path with `.mjs`

packages/nuxt/src/core/plugins/tree-shake.ts
This further restricts the tree-shaking of composables, requiring nothing on the line before it to reduce the chance of false positives. (So this will no longer treeshake something like `const cb = onMounted()`.)
=> fix(nuxt): only tree-shake composables on their own lines

packages/nuxt/src/core/nitro.ts, packages/nuxt/src/core/plugins/import-protection.ts
https://github.com/nuxt/content/pull/1346#issuecomment-1180431720
While investigating https://github.com/nuxt/content/pull/1346#issuecomment-1180431720 (resolved with https://github.com/unjs/nitro/pull/335), I think it doesn't make sense to add this in a hook when we can add it directly. Additional plus is that users get the plugin in `nitro:config` hook.
=> refactor(nuxt): add import protection to nitro config

packages/nuxt/src/core/nitro.ts, packages/nuxt/src/core/runtime/nitro/renderer.ts
`process.dev` is undefined in the npm build (while it works in the local playground). Since `NUXT_VITE_NODE_OPTIONS` will only be injected in dev, I guess it's safe to remove it
=> fix(nuxt): replace `process.dev` in nitro bundle

packages/nuxt/src/app/nuxt.ts
Following https://github.com/nuxt/framework/pull/5630, plugins which take a second argument for `inject` will silently fail. This at least adds a warning if they are being used. Example: https://github.com/moritzsternemann/vue-plausible/blob/main/src/nuxt-plugin.ts ([hotfix PR](https://github.com/moritzsternemann/vue-plausible/pull/21)).
=> fix(nuxt): warn about legacy and invalid plugins

packages/nuxt/package.json, packages/nuxt/src/core/nitro.ts, renovate.json, yarn.lock
Resolves #4325
- Rollup build fails with ESM proxy mocks. Using cjs entry allows ESM syntax import.
- Updated nitro to respect `development` and `production` export conditions used by latest `vue-router`
=> fix(nuxt): fix issues with `vue-router` and `@vue/devtools-api` bundling

packages/vite/src/vite.ts
resolves https://github.com/nuxt/framework/issues/5657
We continue watching files during the vite build process, and if (due to a race condition) `tsconfig.json` is written after vite build starts it can trigger a vite error from the esbuild plugin.
=> fix(vite): close vite watcher before building

docs/content/2.guide/2.features/10.runtime-config.md
Made the nuxt.config.ts example using .env, a little more explicit.
=> docs: improve runtimeConfig example

docs/content/2.guide/2.features/10.runtime-config.md
Add an example to clarify this.
=> docs: add way to pass `.env` variables to nuxt app in production

docs/content/3.api/1.composables/use-fetch.md
Related to https://github.com/nuxt/framework/issues/5907
=> docs: add missing `initialCache` to `UseFetchOptions`

packages/kit/src/build.ts
There's an outstanding issue with kit RC 5 that may break plugins that rely on being shared between client + server vite configs. (see https://github.com/unocss/unocss/pull/1276 for an upstream hotfix). This PR ensures that if client/server flags aren't set, we will call the function only once.
=> fix(kit): only call `viteExtendConfig` callback once if possible

packages/nuxt/src/app/components/nuxt-error-page.vue, packages/nuxt/src/app/components/nuxt-root.vue
Currently `error-dev` is being bundled and not tree-shaken. This change uses a dynamic import for dev errors which allows vite to tree-shake it out of the final build.
=> fix(nuxt): lazy load and tree-shake error templates

docs/content/2.guide/3.directory-structure/4.components.md, packages/nuxt/src/components/module.ts, packages/schema/src/config/experimental.ts, test/fixtures/basic/nuxt.config.ts
Since we plan to release RC.6 sooner than expected as a hotfix release, moving the new performance enhancement from #5750 behind a flag to test until the next RC.7 release.
=> refactor(nuxt): add `treeshakeClientOnly` experimental flag

packages/vite/src/server.ts, packages/vite/src/vite.ts
Resolves #5899
A regression was introduced in rc.5 with #5632 by adding `build.watch` key. The change likely only unrevealed an issue in vite. When this key exists for production, the server build promise succeeds but no output is generated! Removing `watch` key from production seems to solve this issue. This PR also refactors config placement to the shared one for more readability.
=> fix(vite): unset `build.watch` options for production build

packages/vite/src/dev-bundler.ts
Resovles #5954
With #1172 we added a workaround for absolute paths converting them into relative but it was ignoring any file containing "entry" as part of this path.
=> fix(vite): use more strict app entry check in dev-bundler

packages/vite/src/plugins/dynamic-base.ts
resolves https://github.com/nuxt/framework/issues/5975
https://github.com/nuxt/framework/pull/5398 also resolves this issue and this PR is a hotfix if that PR needs to be delayed for some reason.
=> fix(webpack): do not resolve `#internal/nitro` alias internally

packages/nuxt/src/app/components/nuxt-error-page.vue
We are currently providing errorCode as string, which is counter intuitive. I think it should probably be a number instead. However, this is a breaking change if people are checking it directly.
=> fix(nuxt)!: change `statusCode`  type to number for error page template

packages/kit/src/resolve.ts, packages/nuxt/src/components/scan.ts, scripts/bump-edge.ts
The order of the result from `globby` is not reliable. This will potentially cause the order of installed plugins/modules to be unstable across multiple builts or on different machines. We should always sort them to make it stable.
=> fix(kit, nuxt): always sort globby results

packages/nuxt/src/pages/macros.ts, test/fixtures/basic/pages/no-auth.vue
resolves #5862
This PR fixes an oversight in the original code, which followed nesting within quotes.
=> fix(pages): ignore expression delimiters within quotes

packages/nuxt/src/core/nitro.ts
resolves #6024
If users are checking types on build, we should write `nitro.d.ts` then as well.
=> fix(nuxt): always write nitro types when building

packages/kit/src/plugin.ts
resolves #5822
The test in https://github.com/nuxt/framework/blob/8c2c80e43e80cd8f1c4246d7563214fa695a3e98/packages/nuxt/src/core/plugins/unctx.ts#L17 relies on an absolute path. It probably makes sense to resolve plugin paths to absolute when normalizing though, and this resolves the other issue too.
=> fix(kit): resolve aliases in plugin src

packages/vite/src/vite.ts
resolves #5766, resolves https://github.com/nuxt/framework/issues/5888.
Regression from https://github.com/nuxt/framework/pull/4512. When I changed the virtual prefix, I didn't update this hook.
=> fix(vite): invalidate virtual files when changed

packages/kit/src/internal/template.ts, packages/nuxt/src/core/templates.ts
To make the build hash consistent and avoid leaking the full path of user workspace.
=> fix(nuxt): use relative path to generate plugin variables

docs/components/atoms/StabilityEdge.vue, docs/content/2.guide/2.features/7.error-handling.md, docs/content/3.api/3.utils/create-error.md
`createError` should be imported from `h3` otherwise Nuxt will throw an error:
```
[nuxt] [request error] createError is not defined
```
=> docs: add explicit `createError` import

docs/content/migration/7.component-options.md
=> docs: grammar fix

packages/nuxt/src/components/scan.ts
We were only testing for prefix, so `~/components/test` would mean `~/components/tests` would be silently ignored.
=> fix(nuxt): don't ignore components dirs with same prefix

packages/vite/src/server.ts
https://github.com/nuxt/framework/issues/6064
=> fix(vite): resolve `tsconfig.json` for vue-tsc type checker

packages/nuxi/src/commands/dev.ts, packages/nuxi/src/commands/preview.ts
resolves https://github.com/nuxt/framework/issues/6118
We load `.env` for `nuxi preview` and even later in the process, so it seems reasonable to read it in before starting the dev server, allowing host/port to be defined there when developing.
=> fix(nuxi): load `.env` file before starting dev server

packages/vite/src/client.ts, packages/vite/src/server.ts, packages/vite/src/vite.ts
resolves #6078
This fixes a regression in upgrade to Vite 3. Our client config should only contain what we want to override the basic user config, and HMR is probably in the list of things that should be configurable.
=> fix(vite): allow overriding client hmr options

packages/vite/package.json, yarn.lock
resolves #6126
Likely an upstream issue to fix in `unbuild` also (can track in https://github.com/unjs/unbuild/issues/97 - cc: @pi0). But we should not be inlining `pkg-types` in any case (introduced in https://github.com/nuxt/framework/pull/6069).
=> build(vite): add missing `pkg-types` dependency

docs/content/3.api/5.commands/cleanup.md, packages/nuxi/src/commands/cleanup.ts, packages/nuxi/src/commands/index.ts, packages/nuxi/src/commands/upgrade.ts, packages/nuxi/src/utils/fs.ts
Resolves #6123
Introduce a new `nuxi cleanup` command that removes commonly generates nuxt files and caches.
This PR also improves `nuxi upgrade` by reusing new logic including more directories.
(after merge) It can be tested via `npx nuxi-edge@latest cleanup`
=> feat(nuxi): `nuxi cleanup` command

packages/vite/src/runtime/vite-node.mjs
#5018
Otherwise, the cache will be preseved across builds
=> fix(nuxt): clear `vite-node` runner cache after each render

packages/nuxt/src/app/components/nuxt-error-boundary.ts
#6140 Get warning when v-on:error event handler is set to NuxtErrorBoundary
add `emits.error` declaration to NuxtErrorBoundary to prevent prevent getting warning message.
=> fix(nuxt): add emits.error declaration to NuxtErrorBoundary component

docs/content/3.api/1.composables/use-head.md, packages/nuxt/src/head/runtime/components.ts, packages/schema/src/config/_app.ts, packages/schema/src/types/meta.ts
#4646 
Following @danielroe & @pi0 recommendations I'm adding typings for the meta feature noscript
=> feat(nuxt, schema): add `<NoScript>` component and `noscript` typings

docs/content/2.guide/1.concepts/3.rendering.md
=> docs: update link to configuration

packages/schema/src/config/_app.ts
https://github.com/nuxt/framework/pull/6139
Missed line of code. (I couldn't push to upstream branch on PR or would have added it there.)
=> fix(schema): add empty noscript array
