nuxt/framework

- packages/nitro/src/build.ts
resolves #399
We should be more specific with the replacement in case `app.` exists in the fully resolved directory name.
> fix(nitro): narrow replace call for template name

- docs/content/3.docs/1.usage/1.data-fetching.md
Close script tag, and rename `montain` to `organization`
> docs: fix data fetching example

- packages/kit/src/config/load.ts
#1611
resolve #1611
Add new feature to support async function as nuxt.config like v2.
> feat(nuxt3): support async function as nuxt.config

- packages/bridge/bin/nuxt.mjs
- packages/bridge/package.json
- yarn.lock
resolves  #1597
resolves  #1617
resolves  #1590
This is a follow-up on https://github.com/nuxt/framework/commit/b24c9348f75d7311438111d55c550b3f114b65eb
> fix(bridge): expose `nuxi` command

- packages/nuxi/src/commands/init.ts
Update help information for the `init` command:-
- Add `create` alias.
- The `dir` argument is optional.
> chore(nuxi): update help information

- packages/nuxt3/src/meta/runtime/components.ts
> fix(nuxt3): pass css text into children props

- packages/kit/src/module/utils.ts
> chore: remove duplicate camelCase import

- docs/content/1.getting-started/3.bridge.md
- packages/bridge/src/module.ts
> docs(bridge): add notes about feature flags

- .eslintignore
- docs/.eslintrc
- docs/components/app/AlgoliaSearchBox.vue
- docs/components/app/AsideNavigation.vue
- docs/components/atoms/logo/LogoVercel.vue
- docs/components/molecules/HomeHero.vue
- docs/docus.config.ts
I'm not sure if there is any specific reason for disable linting on docs files, this pr is adding it back and fixing all issues so that components in doc can be update to latest vue recommended rules.
> chore(lint): enable linting on docs files

- docs/content/3.docs/2.directory-structure/4.components.md
in the doc to create a module the nuxt/kit import is missing
> docs: add kit import

- packages/nuxt3/src/core/templates.ts
Reuse the plugins filtering result
> refactor: plugin templates

- packages/vite/src/dev-bundler.ts
resolves #1424
resolves #1593
This PR sets the id to a fully resolved path rather than a relative one (but only if it exists, which should protect us from vite plugins that have their own aliases).
> fix(vite): remove relative vite workaround

- packages/kit/src/nuxt.ts
> fix(kit): use closest nuxt package for `loadNuxt`

- docs/content/1.getting-started/5.commands.md
- packages/kit/src/config/schema/server.ts
- packages/nuxi/src/commands/dev.ts
#1667
Support using `nuxi dev --https` to run a server with a self-signed certificate. Also updated docs.
> fix(nuxi): allow starting `nuxi dev` with self signed certificate

- docs/content/3.docs/3.deployment/5.pm2.md
> docs: update pm2 start script

- docs/content/1.getting-started/1.introduction.md
I think the version of Vue used is one of the biggest differences of Nuxt Bridge vs Nuxt 3, so I've added it to the comparison table.
> docs: add version of vue in comparison table

- packages/nitro/src/server/vfs.ts
This bumps monaco editor version.
> chore: bump monaco version

- examples/with-extendRoutes/modules/addRoutes/index.ts
- examples/with-extendRoutes/modules/addRoutes/pages/children/childrenone.vue
- examples/with-extendRoutes/modules/addRoutes/pages/children/childrentwo.vue
- examples/with-extendRoutes/modules/addRoutes/pages/parent.vue
- examples/with-extendRoutes/modules/addRoutes/pages/test.vue
- examples/with-extendRoutes/nuxt.config.ts
- examples/with-extendRoutes/package.json
- examples/with-extendRoutes/pages/hello.vue
- examples/with-extendRoutes/tsconfig.json
- packages/kit/src/types/hooks.ts
- packages/kit/src/utils/resolve.ts
- packages/nuxt3/src/pages/utils.ts
- yarn.lock
https://github.com/nuxt/framework/pull/1740
Now the extend Routes is working via module. I added a project example that add routes and children.
Also update typing as children in NuxtRoute can be optional and we just put an empty array during the check
@danielroe
> Add example for using modules extendRoutes and add / update some typing

- package.json
- packages/bridge/src/runtime/vue2-bridge.mjs
- test/presets/_tests.mjs
A simple change to enable eslint on mjs files.
> chore(lint): enable eslint on mjs

- docs/yarn.lock
- packages/kit/src/config/schema/_app.ts
close https://github.com/nuxt/framework/issues/1647
Improve meta documentation with an example.
@danielroe I think I may have an error with style;
I am using the hello-world example.
```js
import { defineNuxtConfig } from 'nuxt3'
meta: {
meta: [
{
name: 'viewport',
content: 'test content'
}
],
script: [{ src: 'https://awesome-lib.js' }],
style: ['background-color: red;'],
link: [{ href: 'awesome-lib.css', rel: 'stylesheet' }]
}
})
```
When I use the array of object it add attributes to style as expected
If you confirm that's an error I can work on it.
> docs: update doc meta

- docs/content/3.docs/2.directory-structure/5.composables.md
fixes typo in the documentation.
> docs: fix typo in composables 

- docs/content/3.docs/1.usage/1.data-fetching.md
- docs/content/3.docs/1.usage/2.state.md
- docs/content/3.docs/2.directory-structure/10.plugins.md
- docs/content/3.docs/2.directory-structure/17.tsconfig.md
- docs/content/3.docs/2.directory-structure/4.components.md
- docs/content/3.docs/2.directory-structure/7.node_modules.md
- docs/content/3.docs/2.directory-structure/9.pages.md
Some typos and consistency revise.
> docs: improvements

- packages/bridge/src/runtime/capi.legacy.mjs
resolves #1870
this is a holdover from the previous bridge context refactor
> fix(bridge): update `useContext`

- packages/nuxt3/src/auto-imports/imports.ts
`withAsyncContext` unexposed from Vue.
> fix(nuxt3): remove unexposed auto imports

- docs/content/3.docs/1.usage/2.state.md
> docs: add note for `useState` usage

- docs/content/3.docs/1.usage/1.data-fetching.md
Maybe we should add a hint to let ppl know about this limitation ?
> docs: add note for `useFetch` usage

- docs/content/3.docs/1.usage/1.data-fetching.md
- docs/content/3.docs/1.usage/4.nuxt-app.md
- docs/content/3.docs/1.usage/5.runtime-config.md
> docs: add note for usage

- packages/bridge/src/vite/vite.ts
Close #1923
Vite Issue: https://github.com/vitejs/vite/issues/5688
> fix(bridge): revert optimization exclusion for `vue-demi`

- docs/content/3.docs/1.usage/1.data-fetching.md
resolves #1580
This PR adds the types and a few lines of information about what is returned from `useAsyncData` (and hence `useFetch`)
> docs: add documentation on data fetching return types

- docs/content/3.docs/1.usage/2.state.md
- examples/use-state/app.vue
- examples/use-state/composables/states.ts
- examples/use-state/plugins/locale.server.ts
#1857, #1803
Explain and advice using `useState` with auto imported compostables that can guaranteed type safety
> docs: improve `useState` with shared composable

- docs/content/2.concepts/3.typescript.md
- packages/kit/src/config/schema/index.ts
- packages/kit/src/config/schema/typescript.ts
- packages/nuxi/src/utils/prepare.ts
- Support `options.typescript`
- `strict` (default is false)
- `tsConfig` (allow overriding generated tsconfig defaults)
- [placeholder] `typeCheck` (#1818)
- Strict mode is disabled by default allowing users to progressively update their codebase and learn ts
- Add note about strict typechecking in concepts > typescript
> feat: `typescript` options

- docs/content/3.docs/1.usage/2.state.md
- examples/use-state/app.vue
- examples/use-state/plugins/locale.server.ts
- Use tabs for code example
- Add a link to Stackblitz demo
> docs: improve useState docs and add example

- docs/content/3.docs/1.usage/2.state.md
> docs: useState improvements

- .eslintrc
- docs/components/atoms/Gem.vue
- packages/bridge/src/runtime/app.ts
- packages/nitro/src/rollup/plugins/externals.ts
- packages/nitro/src/runtime/server/static.ts
- packages/nuxt3/src/meta/runtime/components.ts
- packages/nuxt3/src/pages/runtime/page.vue
- packages/vite/src/plugins/analyze.ts
- packages/webpack/src/utils/babel-preset.cjs
- packages/webpack/src/webpack.ts
- Improve no-unused-vars rule by adding argsIgnorePattern and ignoreRestSiblings
- Remove eslint disable comments
- Fix some lint errors
> chore(lint): improve no-unused-vars rule

- docs/components/app/AppHeader.vue
- docs/components/app/AsideHeaderNavigation.vue
- packages/bridge/src/runtime/app.ts
- packages/nitro/src/rollup/config.ts
- packages/nitro/src/rollup/plugins/assets.ts
- packages/nuxi/src/commands/info.ts
Changes in this pr are all tiny refactorings which are removing unnecessary optional chaining for data that is not empty.
> refactor: remove unnecessary optional chaining

- docs/content/3.docs/2.directory-structure/4.components.md
Documentation was referring to old `<Nuxt/>` component to render page content in the examples provided. Update with  v3 way of `<slot/>`
> docs: use slot component components example

- docs/content/1.getting-started/4.bridge-composition-api.md
- packages/bridge/src/runtime/capi.legacy.mjs
resolves #1993
This adds docs links to capi warnings/deprecations and re-enables global deprecation warning now that we have `useMeta` & data fetching composables.
> fix(bridge): add docs links and warnings for data composables

- docs/package.json
- docs/scripts/gen-docs.ts
- docs/scripts/make-schema.sh
- packages/kit/src/config/schema/index.ts
#501
- Build docs from latest schema (cost is installing all monorepo deps without cache which is something we need to wait for docus v2 migration)
- Improve Markdown formatting by hiding empty default values and `any` type
- Improve vite config schema to be rendered (#2033)
> docs: improve schema generation

- examples/use-async-data/app.vue
> doc(examples): fix typo

- docs/scripts/nuxt.config.md
resolves #1811
Add a `defineNuxtConfig` wrapper to the `nuxt.config` docs.
> docs: update `nuxt.config` introduction

- docs/content/1.getting-started/3.bridge.md
resolves #1894
This switches to `nuxi`, which is probably useful at this point.
> docs: update command in bridge migration

- docs/content/3.docs/1.usage/6-cookies.md
- examples/use-cookie/app.vue
> docs: improve cookies section

- packages/schema/build.config.ts
- packages/schema/src/config/_app.ts
issue and mention its number as #123 -->
An unneeded import from `nuxt3`, missed out in https://github.com/nuxt/framework/pull/2103
> fix(schema): remove stray `nuxt3` import

- docs/content/3.docs/1.usage/5.runtime-config.md
This updates the docs to use schema, not kit, for augmenting runtime config.
> docs: update runtimeconfig augmentation

- packages/schema/src/types/components.ts
> docs: fix typo

- packages/nuxt3/src/app/composables/cookie.ts
> feat(useCookie): support default value

- docs/content/1.getting-started/3.bridge.md
resolves #2161
This adds a note for Bridge users about composable usage within plugins
> docs: add note for bridge users about `defineNuxtPlugin`

- docs/content/1.getting-started/3.bridge.md
#1920
With https://github.com/johnsoncodehk/volar/commit/85f9c4a9a925cf5fab7dab1433bc493501ed8439, we should now not need to add top-level configuration of `vueCompilerOptions` 🥳
> docs: remove need to add `vueCompilerOptions` at top-level `tsconfig.json`

- packages/nuxt3/src/auto-imports/transform.ts
Update RegExp from unplugin-auto-import
https://github.com/antfu/unplugin-auto-import/commit/a4b82d223be433988a7d5b68b20fcef8989a9080
https://github.com/antfu/unplugin-auto-import/commit/84e14a835b671581e8aa75ceac49e2331e9a5a75
https://github.com/antfu/unplugin-auto-import/commit/91f3ab4f00dc97f8b661bc3455cb66e3ddbf0f01
Tests are already done by unplugin-auto-import
> fix(auto-import): improve auto-import regex

- packages/nuxt3/src/auto-imports/module.ts
- packages/nuxt3/src/auto-imports/utils.ts
> feat: support importing from `#imports`

- packages/bridge/src/app.ts
resolves #2245
Because of differences in hook order, this wasn't being called on Bridge.
> fix(bridge): always add `components.d.ts` reference

- packages/schema/src/types/global/vite.ts
resolves #2240
Typo - see https://github.com/vitejs/vite/blob/main/packages/vite/types/importMeta.d.ts to confirm
> fix(schema): fix typo for `import.meta.globEager`

- packages/nuxt3/src/app/composables/cookie.ts
resolves #2248
`_opts` might be undefined
> fix(nuxt3): use resolved options for `useCookie`

- docs/content/3.docs/1.usage/1.data-fetching.md
> docs(useFetch): add available options

- docs/content/3.docs/2.directory-structure/12.server.md
Took me over 2 hrs of googlefu to realise there was more information to be had as to how this works....
Link to documentation in nuxt.config.js for Api/server middleware documentation
> docs: link to documentation in `nuxt.config.js`

- packages/schema/build.config.ts
- packages/schema/src/config/render.ts
resolves #2286
Adds type for `render.compressor` (only relevant for Bridge).
> fix(schema): type `render.compressor`

- packages/bridge/src/vite/templates.ts
resolves #2221
This PR normalises strings in router middleware for the purposes of `middleware.js` template (for example, from `@nuxtjs/auth`).
Note that this doesn't entirely fix issue in reproduction in original issue as there are some issues in `@nuxtjs/axios` that will need to be handled upstream.
> fix(bridge): normalize strings in vite middleware template

- packages/vite/src/dev-bundler.ts
#2418
Error message is rendering as:
```
WARN  [SSR] Error transforming /private/tmp/Primeblocks-Nuxt3-Primevue/pages/index.vue: [object Object]
```
This PR changes it to:
```
WARN  [SSR] Error transforming /pages/index.vue: Custom directive is missing corresponding SSR transform and will be ignored.
at Object.createCompilerError (node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:19:19)
at createSSRCompilerError (node_modules/@vue/compiler-sfc/node_modules/@vue/compiler-ssr/dist/compiler-ssr.cjs.js:145:24)
at Array.ssrPostTransformElement (node_modules/@vue/compiler-sfc/node_modules/@vue/compiler-ssr/dist/compiler-ssr.cjs.js:589:41)
at traverseNode (node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2203:19)
at traverseChildren …
```
> fix(vite): log error object

- docs/content/3.docs/2.directory-structure/9.pages.md
Add an example for how to use a dynamic route with Composition API
> docs: add composition api example for dynamic routes

- docs/content/1.getting-started/2.installation.md
I was getting started to NuxtJS but already opened another project in a text editor like VScode. Following along the installation guide, I lost the VScode window in which I was working on another project.
Therefore, I would like to open a new window of vs code instead of forcing to open a project in an already opened window.
`code --help` says : 
```bash
Visual Studio Code 1.63.2
Usage: code [options][paths...]
To read from stdin, append '-' (e.g. 'ps aux | grep code | code -')
Options
...
-n --new-window                   Force to open a new window.
-r --reuse-window                 Force to open a file or folder in an already opened window.
...
```
<br />
Hence, I changed the `Open nuxt3-app folder in visual studio code` part : 
```diff
- code -r nuxt3-app
+ code -n nuxt3-app
```
<br /> …
> docs: open project in a new window of vs code

- docs/content/3.docs/2.directory-structure/5.composables.md
The example using default export should use the imported `useState` just like the previous example using named export.
> docs: fix example consistency

- packages/webpack/src/presets/esbuild.ts
Resolves #2372, #2457
Related: https://github.com/privatenumber/esbuild-loader/issues/232
> fix(webpack): import `esbuild-loader` as commonjs

- packages/bridge/src/nitro.ts
resolves #2334
This PR respects custom `app.html` in a Nuxt Bridge context. (I've left supporting/whether to support in Nuxt 3 until we stabilise nitropack.)
> fix(bridge): respect custom `app.html`

- packages/nuxt3/src/app/composables/ssr.ts
> fix(nuxt3): remove undefined headers in useRequestHeaders

- docs/content/3.docs/3.deployment/5.pm2.md
> chore: fix `pm2` link

- docs/content/1.getting-started/4.bridge-composition-api.md
> docs: remove extra spaces

- packages/nitro/src/runtime/server/index.ts
resolves #2539
`createFetch` signature has changed and now needs `Headers` constructor to be passed (which will be used to add headers automatically to post requests).
> fix(nitro): pass `Headers` to `createFetch`

- packages/vite/src/dev-bundler.ts
With the fix of #2521, it removes all queries regardless. Which breaks the usage of Vite's `?raw`, `?url`, `?worker` etc. This PR changes the behavior by only removing the `?v=123` query.
> fix(vite): only remove version query

- docs/content/3.docs/1.usage/1.data-fetching.md
- [ x] 📖 Documentation (updates to the documentation or readme)
> docs: minor grammar tweak on v3 data fetching page

- packages/bridge/package.json
- packages/bridge/src/setup.ts
- yarn.lock
Fixes the error in https://github.com/nuxt/framework/pull/2676
> feat(bridge): upgrade unplugin-vue2-script-setup

- examples/use-async-data/app.vue
Solves `Invalid prop: type check failed for prop "showTips". Expected Boolean, got String with value "true".`
> docs(examples): prop "showTips" should be a boolean instead of a string

- packages/vite/src/dev-bundler.ts
resolves #2050
If a node built-in is imported, we shouldn't try to convert it to a path URL.
> fix(vite): don't convert node builtins to path URLs

- docs/content/3.docs/3.deployment/99.presets/server.md
resolves  #2754
This adds details about the environment variables that the server preset supports.
> docs: add the environment variables server preset supports

- packages/nitro/src/rollup/plugins/externals.ts
close #2758
Allow possibility to inline subpath of externals
> fix(nitro): allow inlining subpath of externals

- packages/nuxt3/src/auto-imports/transform.ts
resolves #2762
We can ignore comments for testing the presence of `require(` to tell us we're in a CJS context.
> fix(nuxt3): ignore comments for testing cjs context

- packages/nitro/src/server/middleware.ts
resolves #2721
This includes dotfiles in Nitro's middleware/routes detection scan.
> fix(nitro): detect routes and middleware starting with dots

- packages/bridge/src/nitro.ts
- packages/nitro/src/context.ts
resolves #2790
We changed `basePath` to `baseURL` which is undefined in Nuxt Bridge - we'll need to update [this PR too](https://github.com/nuxt/nuxt.js/pull/10197).
> fix(bridge): set `app.basePath`

- docs/content/3.docs/2.directory-structure/6.layouts.md
> docs: fix layout meta example

- docs/content/4.community/2.reporting-bugs.md
Fix Nuxt Bridge CodeSandBox URL
> docs: correct bridge codesandbox

- packages/webpack/build.config.ts
- packages/webpack/package.json
- yarn.lock
These implicit externals crept in in the `definePageMeta` PR, and should be removed.
> chore(webpack): prevent implicit externalising

- packages/schema/src/config/_common.ts
resolves  #2630
This updates modules/buildModules type to allow inline options
> fix(schema): support inline module options

- packages/schema/src/config/build.ts
Related to https://github.com/nuxt/nuxtjs.org/pull/1993
> docs(schema): fix typo

- examples/README.md
- examples/with-plugins/app.vue
- examples/with-plugins/nuxt.config.ts
- examples/with-plugins/package.json
- examples/with-plugins/plugins/my-plugin.ts
- examples/with-plugins/tsconfig.json
- yarn.lock
None
Adds an example about plugins, showing the basic implementation of a plugin and how it is auto-imported.
> chore(examples): add `plugins` example

- docs/content/1.getting-started/6.migration.md
A few updates. I think Options API `fetch()` should not be supported as it requires accessing component instance, which we don't have in setup. But as `asyncData` runs in components as well, I don't think we are losing out on functionality.
> docs(migration): update comparison table

- docs/content/3.docs/1.usage/3.meta-tags.md
conversation  - https://github.com/nuxt/framework/issues/2899
> docs: add example of inlined css for `<Style>` component

- packages/vite/src/plugins/dynamic-base.ts
resolves #2888
A bit embarrassing - we were converting binary files to string. I've also further restricted the relative url fix to `.css` files.
> fix(vite): only apply relative url fix to css assets

- packages/nuxi/src/commands/upgrade.ts
resolves  #2935
Clears vite cache on upgrade.
> feat(nuxi): clear cache on upgrade

- docs/content/3.docs/4.advanced/2.modules.md
Minor change in code example of nuxt module doc page, in the `modules/example.ts` code example, `console.log(moduleOptions.token)` should be `console.log(inlineOptions.token)`
> docs: minor nuxt module doc change

- docs/content/3.docs/4.advanced/3.kit.md
None
The docs on Nuxt Kit had a broken link, and I fix it in this PR.
> docs: fix broken link in docs/advanced/kit

- docs/content/3.docs/4.advanced/1.nuxt.md
change link to not be localhost
> docs: fix localhost link

- docs/content/3.docs/2.directory-structure/10.pages.md
There is a missing `</script>` in the code example.
> docs: add missing `</script>` tag

- packages/vite/src/server.ts
resolves #2882
When `ssr: false` the config we've set earlier doesn't apply.
> fix(vite): externalize `#config` at rollup, not ssr level

- docs/content/2.concepts/1.introduction.md
The github issues seem to be hovering at 230 or so, and when one gets resolved, another few open up. It may be a good idea to motivate readers to take a stab at contributing, and perhaps consider a "Are You Nuxt?" campaign. If enough people contribute, the burn rate should improve greatly. If the merch were designed cool enough (hats / shirts /hoodies) it may motivate people.
Added a subsection to motivate people to contribute. (Side note: it may be a good idea to use "good first issue" label on some issues so newcomers can know where to start)
> docs: add "Are you courageously Nuxt" subsection

- docs/content/1.getting-started/6.migration.md
This adds `Static builds` to the feature comparison table and adds links to current discussions/RFCs for global store, error pages and route caching rules
> docs: add links to discussions for work-in-progress

- packages/nuxi/src/commands/analyze.ts
#3021 
- [ x ] 🐞 Bug fix (a non-breaking change that fixes an issue)
Fixes typo in `npx nuxi analyze` output.
Resolves #3021. 
- [ x ] I have linked an issue or discussion.
> docs: fix typo in nuxi analyze output

- packages/bridge/src/nitro.ts
This aligns bridge with nuxt3 in terms of hooks exposed:
https://github.com/nuxt/framework/blob/7553849371c4fa8fe574fe1a36411b0afb4fa145/packages/nuxt3/src/core/nitro.ts#L19-L24
> fix(bridge): add `nitro:generate` hook

- docs/content/2.concepts/1.introduction.md
- docs/content/3.docs/1.usage/1.data-fetching.md
- docs/content/3.docs/1.usage/2.state.md
- docs/content/3.docs/2.directory-structure/10.pages.md
- docs/content/3.docs/2.directory-structure/15.app.md
- docs/content/3.docs/2.directory-structure/4.components.md
- docs/content/3.docs/2.directory-structure/7.middleware.md
- docs/content/3.docs/4.advanced/1.nuxt.md
- docs/content/3.docs/4.advanced/4.hooks.md
- docs/content/index.md
- packages/schema/src/config/_app.ts
This updates links to their new destinations on vuejs.org
> docs: update links to new vuejs.org site

- docs/content/3.docs/2.directory-structure/10.pages.md
- packages/nuxt3/src/pages/runtime/composables.ts
https://github.com/nuxt/framework/discussions/2426#discussioncomment-2123601
This adds missing docs and updates types to reflect the fact that `true` is accepted as a valid prop:
https://github.com/nuxt/framework/blob/083f90b719e0af6a60bc34e8ef347db422fc2db5/packages/nuxt3/src/pages/runtime/utils.ts#L9-L11
> docs: add `keepalive` docs

- docs/content/3.docs/3.deployment/6.vercel.md
Update the deployment docs for Vercel. Related to https://github.com/nuxt/nuxtjs.org/pull/2004 for v2.
> docs: Update Vercel deployment documentation.

- .github/ISSUE_TEMPLATE/bug-report-bridge.yml
The link provided didn't work for me, probably since the branch in the starter repo has been renamed.
> chore: update link to codesandbox in the issue template

- packages/nuxt3/package.json
- yarn.lock
> chore(nuxt3): add implicit `fs-extra` dependency

- packages/vite/src/client.ts
- packages/vite/src/vite.ts
> fix(vite): hmr port priority

- packages/bridge/src/runtime/composables.ts
This allows us to call `useNuxt2Meta` in plugins when seeking to add metadata in Nuxt Bridge. Otherwise, authors would have to manually access `ctx.app.head`, etc.
Example can be found in https://github.com/nuxt-community/color-mode-module/pull/118/files#diff-2139019c09168a10222ac1ada5b0209112c5d2a5e1b4e761aaf948e742fcc323R14-R20.
> feat(bridge): add support for `useNuxt2Meta` in plugins

- packages/bridge/package.json
- yarn.lock
Upgrades vite so we don't have a mismatch within monorepo.
> chore(bridge): upgrade vite

- packages/bridge/src/app.ts
Although generating and writing schema, we weren't adding reference in Bridge. 🙈
> fix(bridge): add schema.d.ts to nuxt.d.ts

- packages/bridge/src/auto-imports.ts
- packages/bridge/src/module.ts
It is otherwise impossible for modules to add their own auto imports or configure vite on a Bridge install.
> fix(bridge): add modules with hooks after all other modules

- packages/bridge/src/runtime/composables.ts
The metaInfo we get is a funciton which needs to be executed.
> fix(bridge): execute metaInfo function

- test/examples/hello-world.test.ts
- vitest.config.ts
> chore: use `@nuxt/test-utils` to import test utils

- packages/nuxt3/src/meta/runtime/lib/vueuse-head.plugin.ts
#3256, #3267
- fixes a bug where absolutely no meta changes (including on initial render) were applied while `ssr: false`.
- allow changes to meta tags via `useMeta` or `Meta Components` to be properly applied after initial render. Meta tags were only applied on initial render, but were ignored on subsequent client-side navigation because `updateDOM` was never called again.
Resolves #3256, #3267
> fix(nuxt3): apply changes to meta tags and updateDOM accordingly

- docs/content/3.docs/1.usage/1.data-fetching.md
None
- Rename handler function.
- Show that the Nuxt context is available in the `handler` function.
- Include the behavior of the `refresh` function.
- Include new headlines for "Params" and "Return values".
- Consistent paragraph capitalization.
> chore(docs): improve `useAsyncData` docs

- docs/content/2.concepts/4.auto-imports.md
[composable auto import improvements](https://github.com/nuxt/framework/issues/1273)
> docs: auto imports don't work in `server/api` 

- examples/README.md
Each example needs to have an online playground
> docs(examples): Add playground for `with-universal-router`

- examples/with-universal-router/app.vue
> docs(example): fix typo on with-universal-router

- package.json
- packages/test-utils/src/server.ts
- packages/test-utils/src/setup/index.ts
- packages/test-utils/src/types.ts
- test/basic.test.ts
- test/fixtures/basic/composables/foo.ts
- test/fixtures/basic/composables/useBar.ts
- test/fixtures/basic/pages/index.vue
> test: add more tests

- packages/vite/package.json
- yarn.lock
Required by schema postcss options - other plugins are already deps in both vite/webpack builders.
> fix(vite): add cssnano dependency

- docs/content/3.docs/1.usage/1.data-fetching.md
resolves  #3401
Add examples for `useLazyFetch` and `useLazyAsyncData`.
> docs: add examples for `useLazyFetch` and `useLazyAsyncData`

- packages/schema/src/config/postcss.ts
It should be possible to add new plugins to the object, for example.
> fix(schema): make postcss plugins a record type

- packages/nuxt3/package.json
- packages/nuxt3/src/components/loader.ts
- yarn.lock
> fix: sourcemap support for `nuxt:components-loader`

- packages/nuxt3/package.json
- packages/nuxt3/src/pages/macros.ts
- yarn.lock
> fix: support sourcemap for `nuxt:pages-macros-transform`

- docs/components/molecules/HomeHero.vue
- docs/content/1.getting-started/1.introduction.md
- docs/content/4.community/4.roadmap.md
Add project roadmap to the community section and link from landing.
Preview: https://deploy-preview-3448--nuxt3-docs.netlify.app/community/roadmap
> docs: add project roadmap

- docs/content/4.community/4.roadmap.md
> docs: add roadmap description

- packages/vite/src/server.ts
resolves #3468 
This narrows the test for inlining files so folders named `nuxt3` don't get included.
> fix(vite): narrow nuxt3 inlining config

- packages/nuxt3/package.json
- packages/nuxt3/src/components/loader.ts
- packages/nuxt3/src/pages/macros.ts
- packages/vite/package.json
- packages/vite/src/plugins/dynamic-base.ts
- yarn.lock
> chore: migrate to `magic-string`

- packages/test-utils/src/browser.ts
resolve #3470
This is a workaround for dynamic import of `playwright`. See: https://github.com/nuxt/framework/issues/3470#issuecomment-1057224699
> fix(test-utils): workaround playwright dynamic import issue with Vite

- packages/vite/src/plugins/dynamic-base.ts
resolves https://github.com/nuxt/framework/issues/3469
This PR fixes the typo that caused #3469. We then have to take a slightly different approach to the final replace stage to avoid replacing text that has already been replaced.
> fix(vite): handle base in `vite/preload-helper`

- docs/content/3.docs/3.deployment/99.presets/server.md
- packages/nitro/src/rollup/plugins/timing.ts
resolves #24
This changes Cold Start -> Nitro Start for clarity as to what it is measuring.
> fix(nitro): rename cold start -> nitro start

- packages/bridge/src/runtime/app.ts
- test/fixtures/bridge/plugins/setup.js
resolves #2014
This aligns plugins on bridge & nuxt3 for auto-injections.
> feat(bridge): auto-inject based on `provide` key from plugins

- packages/nitro/src/rollup/plugins/static.ts
- packages/nitro/src/runtime/server/static.ts
resolves #3530
Incoming requests that are URI-encoded aren't getting decoded. This PR adds them to a list of alternative options to resolve, as we can't assume that all incoming requests will be URI encoded.
> fix(nitro): handle decoding static filenames

- docs/content/3.docs/3.deployment/4.netlify.md
Add short description on how to add custom redirects when deploying with netlify.
> docs: add custom redirects for netlify deployment

- docs/content/1.getting-started/2.installation.md
> docs(install): add 3rd tab for using `pnpm`

- docs/content/3.docs/1.usage/8.cli.md
This PR specifies commands that interact with NODE_ENV and the way to override them.
> docs(cli): specify commands that interact with node-env

- packages/webpack/src/presets/style.ts
> chore: remove extra space

- packages/nitro/src/rollup/config.ts
This allows using `process.dev` within server code.
> fix(nitro): support `process.dev`

- packages/schema/src/config/_common.ts
See https://v3.nuxtjs.org/docs/directory-structure/nuxt.config. Reported on [discord](https://ptb.discord.com/channels/473401852243869706/897487139888062506/951835715237478421).
> fix(schema): set static alias correctly

- packages/schema/src/types/hooks.ts
- packages/webpack/src/webpack.ts
> feat(webpack): add `webpack:devMiddleware` and `webpack:hotMiddleware` hooks

- packages/bridge/package.json
- yarn.lock
resolves #3636
Upgrades unplugin-vue2-script-setup.
> chore: upgrade `unplugin-vue2-script-setup`

- docs/content/4.community/4.roadmap.md
> docs: fix url

- .github/ISSUE_TEMPLATE/bug-report-nuxt3.yml
- docs/content/4.community/2.reporting-bugs.md
This PR adds a link to this Vite + Vue 3 + SSR reproduction playground: https://stackblitz.com/edit/vue3-ssr-playground.
Ideally when we are triaging Vue 3 issues it would be good if users can first check whether this is a bug in Nuxt or elsewhere.
> docs: add vue 3 ssr starter

- docs/content/2.concepts/4.auto-imports.md
> docs(concepts): small improvement regarding auto import on server

- docs/content/3.docs/1.usage/9.nuxt-link.md
- docs/content/3.docs/2.directory-structure/10.pages.md
- docs/yarn.lock
- Renamed `Routing` in **Usage** to `NuxtLink`
- Improved the content of the `pages/` directory in **Directory Structure**
> docs(routing): improvements

- playground/package.json
- yarn.lock
The latest @nuxt/ui bumps the version of @vueuse/nuxt which dismissed the warning from unimport
> chore: upgrade @nuxt/ui

- docs/content/3.docs/2.directory-structure/10.pages.md
RouterOptions requires some values that users probably shouldn't be providing.
> docs: use partial `RouterOptions` interface

- packages/nuxt3/src/app/composables/fetch.ts
> fix(nuxt3): update types for `useLazyFetch`

- packages/nuxi/src/utils/prepare.ts
follow up on https://github.com/nuxt/framework/pull/3737#issuecomment-1072171838
Schema hasn't processed options so `experimental` doesn't exist.
> fix(bridge): handle missing `experimental` key on bridge

- packages/nuxt3/src/app/components/nuxt-error-page.vue
- packages/nuxt3/src/app/components/nuxt-root.vue
resolves #3723
Typescript within Vue SFC in `node_modules` was causing an issue for webpack users.
> fix(nuxt3): do not use ts in internal components

- examples/use-cookie/app.vue
- examples/use-meta/app.vue
- examples/use-state/app.vue
- examples/with-components/app.vue
This PR replaces the `NLink` component by `NuxtLink` in examples
> docs(examples): replace nlink by nuxtlink

- packages/vite/src/css.ts
related: #3624
We have some code to add `cssnano` & `autoprefixer` last in webpack. This adds a similar effect for vite:
https://github.com/nuxt/framework/blob/73ba30fb69b91a25ee595daa447f3d6988b4dc8c/packages/webpack/src/utils/postcss.ts#L8-L26
> fix(vite): sort postcss plugins to add autoprefixer & cssnano last

- docs/content/1.getting-started/6.migration/3.meta.md
#3769
Provided is documentation with examples showing how to migrate meta tags from Nuxt 2 to Nuxt 3. Let me know if you need any changes or provide more examples.
> docs: migrating meta tags

- docs/content/1.getting-started/6.migration/9.minor-upgrades.md
#3769 
This file is a suggestion for all of the small upgrades that take place from Nuxt 2 to Nuxt 3. Features that are now composables instead of global variables, component names, etc. Features that don't warrant an entire page. If you like this approach, I can add a lot of these smaller upgrades as I get to them. Just let me know and no rush!
> docs: minor upgrades

- docs/content/3.docs/2.directory-structure/4.components.md
> docs: use `path` in examples

- docs/content/1.getting-started/6.migration/8. Fetching Data.md
- docs/content/1.getting-started/6.migration/8.data-fetching.md
#3769 
This is a start to all of the different options provided by Nuxt 3 for data fetching. I wrote this up to where I was with the migration of our app. I know there is a ton more that we will have to touch on.
@danielroe : The big question I came across when migrating our app from Nuxt 2 to Nuxt 3 was how to design reusable functions that call an API through fetch. For example, if I were to make an API endpoint that accepted a `search` term or a `pagination` term, what would be the best way to abstract that? Interface with the provided `$fetch` object? If you have a good example of this, I'll submit a PR to the docs as well. I noticed a few questions in the discussion forum asking this as well.
I'll keep updating this as …
> docs: added data fetching migration

- test/basic.test.ts
Dynamic paths tests were accidentally nested inside another test.
Thanks @kevinmarrec for spotting it!
> test: extract dynamic paths test from within other test!

- docs/content/3.docs/4.advanced/4.hooks.md
no issue
i think this shoud change to `Plugins`
> docs: update hooks

- docs/content/3.docs/1.usage/1.data-fetching.md
`useAsyncData` not have response value that `watch`, and add `watch` to the argument that `options`
> doc: fix useAsyncData documentation error

- packages/bridge/src/runtime/app.ts
resolves #3868
We have implemented a subset of the Nuxt 3 runtime hooks in Bridge; this adds types for them.
> fix(bridge): add implemented runtime nuxt hooks

- test/basic.test.ts
- test/fixtures/basic/extends/bar/components/ExtendsOverride.vue
- test/fixtures/basic/extends/bar/layouts/override.vue
- test/fixtures/basic/extends/bar/pages/override.vue
- test/fixtures/basic/extends/foo/components/ExtendsFoo.vue
- test/fixtures/basic/extends/foo/components/ExtendsOverride.vue
- test/fixtures/basic/extends/foo/composables/foo.ts
- test/fixtures/basic/extends/foo/layouts/default.vue
- test/fixtures/basic/extends/foo/layouts/override.vue
- test/fixtures/basic/extends/foo/middleware/foo.ts
- test/fixtures/basic/extends/foo/middleware/override.ts
- test/fixtures/basic/extends/foo/pages/foo.vue
- test/fixtures/basic/extends/foo/pages/override.vue
- test/fixtures/basic/extends/foo/pages/with-middleware-override.vue
- test/fixtures/basic/extends/foo/pages/with-middleware.vue
- test/fixtures/basic/extends/foo/plugins/foo.ts
- test/fixtures/basic/extends/foo/server/api/foo.ts
- test/fixtures/basic/extends/foo/server/middleware/foo.ts
Following up #3222 (`extends` support progress) this PR add tests for each `extends` feature we implemented so far.
> test: add test suites for extends features

- packages/schema/src/config/_common.ts
resolves #3891
This clarifies that functions will only run in development mode. Also updated syntax of example to ESM (might be worth changing the example too 🤔).
> docs: update `serverMiddleware` to add warning on function and make example esm

- packages/vite/src/server.ts
resolves #3861
With `ssr: false`, we were ignoring the external config.
> fix(vite): externalise `#_config` in `ssr: false`

- docs/content/3.docs/1.migration/2.pages-and-layouts.md
#3769 
Added detailed instructions on how to migrate your Nuxt 2 pages to Nuxt 3. Also included information on how to access dynamic route data.
> docs: add migration for pages

- packages/nuxt3/src/core/nitro-nitropack.ts
> fix(nitropack): respect custom output dir

- docs/content/3.docs/1.usage/8.cli.md
Mentioned by @hecktarzuli on Discord
> docs(cli): fix typo (exsits -> exists)

- docs/content/5.community/4.roadmap.md
> docs: update roadmap

- examples/advanced/config-extends/pages/index.vue
- examples/advanced/module-extend-pages/layouts/default.vue
- examples/app/error-handling/app.vue
- examples/app/plugins/app.vue
- examples/auto-imports/components/app.vue
- examples/auto-imports/composables/app.vue
- examples/composables/use-async-data/app.vue
- examples/composables/use-cookie/app.vue
- examples/composables/use-fetch/app.vue
- examples/composables/use-meta/app.vue
- examples/composables/use-state/app.vue
- examples/experimental/reactivity-transform/app.vue
- examples/experimental/wasm/app.vue
- examples/other/locale/app.vue
- examples/routing/layouts/pages/index.vue
- examples/routing/middleware/app.vue
- examples/routing/nuxt-link/app.vue
- examples/routing/pages/app.vue
- examples/routing/universal-router/app.vue
Fix broken links to Github in examples after moving them to sub-folders
> fix(examples): add sub-folder to github examples path

- docs/content/3.docs/3.migration/2.configuration.md
https://github.com/nuxt/framework/issues/2041#issuecomment-1085840699
Add `pages:extend` migration to `nuxt.config` section.
> docs: add `router.extendRoutes` example to migration docs

- README.md
Setting up a dev environment no longer uses the `npx yarn play` command. It now uses `npx yarn dev`. I've updated the readme to reflect this change to help guide future contributors.
> fix(docs): readme now reflects updated dev command

- docs/content/3.docs/3.migration/7.component-options.md
> docs: fix small typo

- packages/nuxt3/src/app/composables/asyncData.ts
- packages/nuxt3/src/app/composables/fetch.ts
resolves https://github.com/nuxt/framework/issues/4021
I'll follow up with a PR to fix the test suite, which should have caught this.
> fix(nuxt3): use inferred type for `useFetch`

- docs/content/5.community/4.roadmap.md
We got some delay but we shall have a version ready for end of April 🤞
> docs: update Nuxt Content v2 expected date

- docs/content/3.docs/2.directory-structure/13.server.md
A comment in the accessing req data example states that `useBody` can only be used for `POST` requests.
I've updated the comment to reflect the supported methods listed [here](https://github.com/unjs/h3/blob/main/src/utils/body.ts#L9)
> docs: update `useBody` comment to reflect usable methods

- docs/content/5.community/3.contribution.md
> docs: fix spelling for steps

- test/basic.test.ts
- test/utils.ts
https://github.com/nuxt/framework/issues/3198
> test: enable browser tests

- packages/schema/src/config/_app.ts
> docs(schema): update environment variable name for overriding `baseURL`

- docs/content/2.guide/2.features/7.error-handling.md
> docs(guide): fix links to error utils

- docs/static/_redirects
- packages/bridge/src/runtime/capi.legacy.mjs
> docs(bridge): fix bridge composition api link

- docs/content/1.getting-started/1.quick-start.md
resolves #3925
Remove instructions to use `yarn dlx` (which does not currently work as yarn doesn't seem to support executing esm binaries). (context: https://github.com/nuxt/framework/pull/3559)
> docs: remove `yarn dlx` instruction

- docs/content/3.api/2.components/5.nuxt-error-boundary.md
#4104
This PR describes `<NuxtErrorBoundary>` component's API.
> docs(api): specify nuxt-error-boundary events and slots

- docs/content/migration/8.runtime-config.md
related to #4157
Incomplete documentation on server api part
- [ x] I have linked an issue or discussion.
- [ x] I have updated the documentation accordingly.
> docs: update runtime config migration

- packages/bridge/src/nitro.ts
resolves #4158
Applies fix from https://github.com/nuxt/framework/pull/4157 to bridge.
> fix(bridge): inline bridge dist files

- packages/bridge/package.json
- yarn.lock
We were inlining `get-port-please` and `fs-memo` as a result.
> fix(bridge): add missing dependency

- docs/content/2.guide/2.features/10.runtime-config.md
> docs: add missing config variable in example (server api)

- packages/nuxi/src/utils/templates.ts
This PR updates `nuxi add api` behavior to match the direction detailed in unjs/h3#73 and documented in #4174.
> fix(nuxi): update `api` template to h3 event format

- packages/bridge/package.json
- yarn.lock
We moved it to a dynamic import in nuxi so we need a dependency in bridge.
> fix(bridge): add ui-templates dependency

- docs/content/2.guide/5.deployment/1.azure.md
- docs/content/2.guide/5.deployment/2.cloudflare.md
- docs/content/2.guide/5.deployment/3.firebase.md
- docs/content/2.guide/5.deployment/4.netlify.md
We now support Azure SWA again, so we can move this to the top of the azure instructions as our recommended approach for Azure!
> docs: update deployment urls & azure instructions

- packages/nuxt3/src/head/runtime/composables.ts
Improve DX as it will take a while to move from `useMeta` -> `useHead`...
> fix(nuxt3): remove useMeta warning

- docs/content/2.guide/1.concepts/4.auto-imports.md
> docs: fix broken link

- docs/content/2.guide/3.directory-structure/10.pages.md
#4208
Small note to help end users avoid falling in my same pitfall
> docs: improve single root element note about comments

- docs/content/2.guide/2.features/10.runtime-config.md
- docs/content/migration/8.runtime-config.md
#4267 
- [ x ] I have linked an issue or discussion.
- [ x ] I have updated the documentation accordingly.
> docs: update runtimeConfig section

- docs/content/3.api/3.utils/throw-error.md
> docs: fix a typo and link

- packages/bridge/README.md
- packages/nuxi/README.md
- packages/schema/src/config/_adhoc.ts
Updates links in the generated `nuxt.config` page.
> chore: update links for new sitemap

- packages/bridge/src/runtime/composables.ts
- packages/nuxt3/src/app/nuxt.ts
Following https://github.com/nuxt/framework/pull/4254, proxy is not working on SSR
> fix(nuxt3): as backward compatible runtime config for server side

- packages/bridge/package.json
- packages/nuxt3/package.json
- yarn.lock
fix https://github.com/nuxt/ui/issues/91
upstream pr https://github.com/vueuse/head/pull/61
> fix(deps): upgrade @vueuse/head

- docs/content/5.community/4.roadmap.md
> docs: update release schedule

- docs/content/2.guide/2.features/7.error-handling.md
- docs/content/2.guide/2.features/9.server-routes.md
- docs/content/3.api/3.utils/clear-error.md
> docs: fix clearError type and server route prefix

- docs/content/2.guide/1.concepts/1.introduction.md
> docs: broken @nuxt/bridge link fix

- test/fixtures/basic/pages/head.vue
https://github.com/nuxt/framework/pull/4260#pullrequestreview-938069707
Missing test case from https://github.com/nuxt/framework/pull/4260.
> test(nuxt3): add test case for computed head

- packages/schema/src/config/webpack.ts
resolves #3495
Updates code examples to use correct top-level key (webpack, not build).
> docs: update webpack code examples

- docs/content/2.guide/1.concepts/4.server-engine.md
> docs: fix typo and `unjs/nitro` link

- packages/vite/src/dev-bundler.ts
Fix https://github.com/nuxt/framework/issues/4366
> fix(vite): interop CJS

- docs/content/2.guide/3.directory-structure/18.nuxt.config.md
This add a note about how nuxt distinct full restart and partial update and add an example on how to benefit from full restart (to split configuration file)
Based on: https://github.com/nuxt/framework/blob/main/packages/nuxi/src/commands/dev.ts#L87-L89
> docs: add note about nuxt full restart feature

- packages/webpack/src/configs/server.ts
resolves #2447
We weren't transpiling css/sass/scss on server side.
> fix(webpack): add css, sass, scss to asset patterns to transpile

- packages/vite/package.json
- yarn.lock
> build(vite): don't inline `h3`

- docs/content/2.guide/3.directory-structure/9.node_modules.md
NA
Adds `pnpm` as option to npm and yarn as package manager.
> docs: include pnpm package manager

- docs/content/2.guide/1.concepts/6.typescript.md
- docs/content/3.api/5.commands/typecheck.md
- packages/schema/src/config/typescript.ts
- packages/vite/package.json
- packages/vite/src/server.ts
- packages/webpack/package.json
- packages/webpack/src/configs/server.ts
- yarn.lock
resolves #1818
This PR enables async/non-blocking type checking for dev/build for both vite & webpack builders. Usage:
```js
import { defineNuxtConfig } from 'nuxt3'
builder: 'webpack',
typescript: {
typeCheck: true // or 'build' for build-time-only type checking
}
})
```
> feat(vite,webpack): build/dev typechecking

- docs/content/3.api/2.components/4.nuxt-link.md
> docs: fix defineNuxtLink property name

- examples/advanced/config-extends/package.json
- examples/advanced/module-extend-pages/package.json
- examples/app/error-handling/package.json
- examples/app/plugins/package.json
- examples/app/teleport/package.json
- examples/auto-imports/components/package.json
- examples/auto-imports/composables/package.json
- examples/composables/use-async-data/package.json
- examples/composables/use-cookie/package.json
- examples/composables/use-fetch/package.json
- examples/composables/use-head/package.json
- examples/composables/use-state/package.json
- examples/experimental/reactivity-transform/package.json
- examples/experimental/vite-node/package.json
- examples/experimental/wasm/package.json
- examples/other/locale/package.json
- examples/routing/layouts/package.json
- examples/routing/middleware/package.json
- examples/routing/nuxt-link/package.json
- examples/routing/pages/package.json
- examples/routing/universal-router/package.json
- examples/server/routes/package.json
- package.json
- packages/nuxt3/package.json
- yarn.lock
Update to use stable and non edge version of `@nuxt/ui` and `@nuxt/ui-templates` for nuxt 3 and all examples.
> build: update nuxt ui to ^0.1.0

- docs/content/2.guide/5.deployment/99.presets/lambda.md
- docs/content/2.guide/5.deployment/99.presets/server.md
- docs/content/2.guide/5.deployment/99.presets/service-worker.md
#4432
Resolves #4432 
Now follows nitro presets as documented in https://github.com/unjs/nitro/blob/ba3323e07fa8429f88b8d55ae5e61d4131c584f1/docs/guide/presets.md
> docs: fix nitro preset names in examples (#4432)

- packages/nuxt/src/app/entry.ts
https://github.com/nuxt/framework/pull/4423
follow up to https://github.com/unjs/nitro/pull/122
baseurl should be set in client as well as server
> fix(nuxt3): default client-side fetch to use baseURL

- docs/content/2.guide/2.features/9.server-routes.md
> docs: remove useless `:`

- packages/nuxt/src/core/nitro.ts
> fix(nuxt): skip server build with generate

- packages/nuxi/src/commands/generate.ts
>  chore(nuxi): add notice for generate deployment

- docs/content/2.guide/5.deploy/2.static-hosting.md
Add link to our hybrid rendering RFC
> docs: add link to hybrid rendering RFC

- docs/content/2.guide/2.features/4.head-management.md
> docs: simplify example of Head components

- docs/content/2.guide/6.going-further/5.esm.md
> docs: fix `alias` usage

- .github/issue-up.yml
- .github/upissues.yml
https://github.com/antfu/issue-up
To enable it, we need to install [the app](https://github.com/apps/issue-up) for both Nuxt and UnJS org
> chore: setup IssueUp

- docs/nuxt.config.ts
This PR updates the documentation social card to reflect RC status
> chore(docs): update social card

- docs/content/2.guide/2.features/10.runtime-config.md
fix wrong `environment variables` in example
> docs: update environment variable in example

- packages/vite/src/plugins/dynamic-base.ts
In diagnosing another issue, I hit an edge condition that this resolves.
> fix(vite): don't match across newlines

- docs/components/atoms/LinkExample.vue
> docs: add full stop in `<LinkExample>`

- docs/components/atoms/StabilityEdge.vue
- docs/content/2.guide/3.directory-structure/10.pages.md
- docs/content/2.guide/6.going-further/8.edge-channel.md
- Add a dedicated page explaining about opting-in and opting out from edge channel.
- Add a badge to indicate features from the documentation waiting for next release with possibility of beta testing them earlier.
- Add note for optional params (resolves #4634)
> docs: add note and banner about edge channel

- docs/content/2.guide/1.concepts/6.typescript.md
Explaining how to activate stricter types should be more visible.
> docs(typescript): typos

- docs/content/2.guide/2.features/3.assets.md
#4104 
This PR completes the `guide/features/assets` page of the documentation.
Preview : https://deploy-preview-4563--nuxt3-docs.netlify.app/guide/features/assets
> docs(features): complete assets page

- packages/nuxi/src/commands/init.ts
> fix(nuxi): typo in init message

- docs/content/2.guide/3.directory-structure/5.composables.md
Simple typo fix.
```
export default const useBar () {
}
```
> docs: fix incorrect function declaration in composables

- docs/content/2.guide/2.features/5.data-fetching.md
> docs: make `useFetch` example consistent with others

- packages/schema/src/config/_common.ts
> docs: fix typo in environment variable

- examples/composables/use-state/app.vue
> docs: remove semicolon

- docs/content/2.guide/6.going-further/3.modules.md
> docs: typo

- packages/schema/src/config/vite.ts
> fix(schema, vite): resolve `mode` config correctly

- docs/content/2.guide/3.directory-structure/10.pages.md
Add information about adding types for PageMeta
> docs(pages): add information for typing page metadata

- docs/content/migration/6.pages-and-layouts.md
https://github.com/nuxt/framework/issues/5309
Typo fix.
> docs: update keepalive key name

- packages/kit/src/resolve.ts
resolves #5374
We were not passing the full path to the `isIgnored` test so weren't properly ignoring files.
> fix(kit): pass resolved path to `isIgnored`

- packages/nuxt/src/pages/utils.ts
- packages/nuxt/test/pages.test.ts
This reverts commit b31186b65883ac30f5a07a733d4169af9963557d.
https://github.com/nuxt/framework/pull/5383#issuecomment-1152112195
No need for hotfix any more 🎉
> revert(nuxt): revert router hotfix #4983

- docs/content/3.api/1.composables/use-cookie.md
> docs: update cookie example with `defineEventHandler`

- packages/nuxi/src/utils/env.ts
Updated the warning message to provide some insights to the developers about the fact that he did not do something wrong per se, but many libraries would not be behaving correctly.
Related to https://github.com/nuxt/framework/commit/a9c061cd2e459a0a9485df3d48d0f4890fd93664#commitcomment-75926157 and https://github.com/nuxt/framework/issues/5196.
> refactor(nuxi): improve env update message

- docs/content/5.community/4.roadmap.md
Added absolute URL to nuxt/image issue.
> docs: fix link to `nuxt/image` issue

- packages/kit/src/build.ts
We support client/server flags for `addWebpackPlugin`; this allows us to do the same for `addVitePlugin`
> feat(kit): support client and server flags for `addVitePlugin`

- docs/content/1.getting-started/1.quick-start.md
> docs: update `pnpm` usage

- docs/content/3.api/2.components/1.nuxt-page.md
Added API documentation for `NuxtPage` component page
> docs(api): add docs for `<NuxtPage>` component

- docs/content/3.api/5.commands/analyze.md
- docs/content/3.api/5.commands/build.md
- docs/content/3.api/5.commands/dev.md
https://github.com/nuxt/framework/issues/5736
Updates documentation following merge of https://github.com/nuxt/framework/pull/5417.
> docs(api): update commands with new `NODE_ENV` behavior

- packages/vite/package.json
- yarn.lock
fix: https://github.com/nuxt-community/color-mode-module/pull/154
by: https://github.com/vitest-dev/vitest/pull/1609
Confirmed working by in https://github.com/nuxt/modules/pull/342/commits/fd6a16542d19a38c6bbf895aa3aefb78a9bc266b
> fix(vite): fix `vite-node` circular reference

- docs/content/4.examples/4.routing/nuxt-link.md
> docs: update `nuxt-link.md`

- packages/schema/src/types/global/vite.ts
1. Vite glob import should accept 2 arguments
2. Sync types of [v2.9.x](https://github.com/vitejs/vite/blob/v2.9.14/packages/vite/types/importMeta.d.ts)
> feat(schema): sync types of vite v2.9.x

- docs/content/2.guide/6.going-further/7.testing.md
> docs(testing): add missing import

- packages/nuxi/package.json
fix nuxi forget export dts in package.json 😀
> fix(nuxi): add missing `types` field

- docs/content/3.api/2.components/4.nuxt-loading-indicator.md
Fixes a typo in the <NuxtLoadingIndicator> example. https://v3.nuxtjs.org/api/components/nuxt-loading-indicator/
> docs: fix typo in <NuxtLoadingIndicator> example

- docs/content/2.guide/5.deploy/2.static-hosting.md
> docs: grammar fix

- packages/test-utils/src/server.ts
None
The current error message in test-utils has a typo
> chore(test-utils): error message typo

- packages/schema/src/types/config.ts
> chore(schema): update vite config

- docs/content/3.api/2.components/2.nuxt-layout.md
Added API documentation for `NuxtLayout` component
> docs(api): add `<NuxtLayout>` component docs

- packages/nuxt/src/app/composables/router.ts
> fix(nuxt): type `useRoute` return

- docs/content/3.api/1.composables/use-router.md
> docs(composables): add a missing period on `hasRoute`

- packages/schema/src/types/components.ts
> docs(schema): add a missing period in `ScanDir` Interface

- packages/schema/src/config/_adhoc.ts
> docs(schema): add a missing period in nuxt telemetry.

- packages/vite/package.json
- packages/vite/src/server.ts
- yarn.lock
#6405
Add hotfix to revert the effect of https://github.com/nuxt/framework/pull/5506 introduced in RC.5 only for the netlify build platform until we can investigate the issue.
> fix(vite): add hotfix for netlify deployments

- packages/nuxt/package.json
- packages/vite/package.json
- packages/webpack/package.json
- yarn.lock
Resolves https://github.com/nuxt/framework/issues/6413
This is a hotfix for an issue introduced with an unplugin upgrade. If we merge this PR, we can then create an issue to track upgrading unplugin specifically.
> fix(nuxt): revert unplugin upgrade

- packages/nuxt/src/app/composables/asyncData.ts
https://github.com/nuxt/framework/issues/5795
> fix(nuxt): handle immediate errors when calling `useAsyncData`

- package.json
- yarn.lock
https://github.com/johnsoncodehk/volar/issues/1688
> chore: downgrade `vue-tsc`

- package.json
- yarn.lock
New unbuild upgrades esbuild to 0.15.x, is safer to automatically fail CI on warnings by default (https://github.com/unjs/unbuild/pull/98) and also has MJS exports in stub mode using static analyzes.
@nuxt/framework After this, please run new stub. We now have named mjs exports 🚀
> build: upgrade to unbuild 0.8.x

- scripts/release-edge.sh
- scripts/release-rc.sh
#6516
Use npx to use predicable and tested version of npm to publish packages.
> build: use `npm@8.10.0` to publish packages

- docs/content/2.guide/3.directory-structure/5.composables.md
problem source: https://github.com/nuxt/framework/issues/6614
solve source: https://github.com/nuxt/framework/pull/6025
> docs(composables): add more examples for `autoImports`

- test/fixtures/basic/types.ts
> test: update type assertion tests to strict equality

- packages/vite/package.json
- packages/vite/src/runtime/vite-node.mjs
- packages/vite/src/vite-node.ts
- yarn.lock
See https://github.com/vitest-dev/vitest/pull/1872
> fix(vite): improve `vite-node` module invalidation

- docs/content/2.guide/2.features/9.server-routes.md
- docs/content/3.api/1.composables/use-cookie.md
No linked issue as it is a simple change.
`useCookie` is deprecated in h3 as seen [here](https://www.jsdocs.io/package/h3#useCookie)
> docs: use updated h3 utils

- packages/nuxt/package.json
- packages/nuxt/src/imports/module.ts
- yarn.lock
Manually update bookable to `0.2.x` (there were regressions and hell of rebase issues when trying renovate)
> chore(deps): update hookable to `2.x`

- packages/nuxt/src/app/composables/asyncData.ts
Looks like we weren't covering the condition of `ssr: false` & `lazy: true`. Reported in chat.
> fix(nuxt): lazy composables shouldn't block setup in `ssr: false`

- packages/nuxt/src/core/nitro.ts
> chore(nuxt): fix typo

- docs/content/3.api/5.commands/add.md
Fix the extension of the new layout file from .ts to .vue.
> docs(api): fix the layout file extension in cli example

- packages/schema/src/config/_common.ts
- packages/schema/src/config/build.ts
- packages/schema/src/config/generate.ts
- packages/schema/src/config/webpack.ts
> style(schema): lint

- .github/ISSUE_TEMPLATE/bug-report.yml
Resolves #7082
Remove a superfluous backtick in the bug template.
> chore(repo): remove backtick-type in bug issue-template

- docs/content/3.api/index.md
> docs(api): navigate to first item in list

- docs/content/2.guide/2.features/10.app-config.md
> docs: rename `AppConfig` to `AppConfigInput`

- docs/content/3.api/1.composables/use-fetch.md
> docs(api): fix typo in use-fetch

- packages/vite/src/runtime/vite-node.mjs
We were always showing fallback with `[check console]` by throwing inside try/catch 😮‍💨
> fix(vite): show formatted vite-node errors

- packages/nuxt/src/core/runtime/nitro/renderer.ts
closes #7548
[7548](https://github.com/nuxt/framework/issues/7548#issuecomment-1248003267)
> fix(nuxt): remove modulepreload for spa fallback routes with `ssr:true`

- examples/experimental/wasm/nuxt.config.ts
https://github.com/nuxt/framework/issues/7632
Fixes a typo in the nitro options for wasm example.
> docs: fix typo in nitro options in wasm example

- docs/content/5.community/5.roadmap.md
> ### ❓ Type of change
> * [x]  📖 Documentation (updates to the documentation or readme)
> * [ ]  🐞 Bug fix (a non-breaking change that fixes an issue)
> * [ ]  👌 Enhancement (improving an existing functionality like performance)
> * [ ]  ✨ New feature (a non-breaking change that adds functionality)
> * [ ]  ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
> 
> ### 📚 Description
> 📖 Summer is over unfortunately.
> 
> ### 📝 Checklist
> * [ ]  I have linked an issue or discussion.
> * [x]  I have updated the documentation accordingly.
> docs(roadmap): update the release times for v2 and v3

- docs/content/2.guide/2.directory-structure/3.nuxt.config.md
Link is not correct so page is not found. But maybe we need to change the filename instead
> docs: fix path of nuxt config

- docs/public/_redirects
This PR fixes some bad redirects in the netlify config file
> docs: fix netlify redirects

- docs/content/1.getting-started/1.introduction.md
Changed installation path to correct one.
> fix(docs): link to installation section

- docs/content/2.guide/2.directory-structure/1.server.md
- examples/app/error-handling/server/middleware/error.ts
- examples/composables/use-fetch/server/api/[...hello].ts
- examples/experimental/wasm/server/api/sum.ts
> docs(example): replace useQuery to getQuery

- packages/schema/package.json
resolves #8061
We use `untyped` in schema but weren't specifying a dependency - this likely caused https://github.com/nuxt/framework/issues/7227 and https://github.com/nuxt/framework/issues/7758.
> fix(schema): declare `untyped` dependency

- docs/content/2.guide/2.directory-structure/3.nuxt.config.md
Fixed a typo in Docs guide/directory-structure, nuxt.config.ts File.
Link : https://v3.nuxtjs.org/guide/directory-structure/nuxt.config
> docs: fix typo in guide/directory-structure, nuxt.config.ts

- docs/content/3.api/4.advanced/1.hooks.md
> docs: update line number for `NuxtHooks` source

- docs/package.json
- docs/yarn.lock
https://github.com/nuxt/framework/pull/8131
This bumps the docus version to resolve an issue with the 404 page.
> docs: fix 404 page

- docs/content/3.api/3.utils/define-page-meta.md
resolves #8192 
- updates the link to route middleware from
> docs: update route middleware link

- docs/content/1.getting-started/5.seo-meta.md
[#8208](https://github.com/nuxt/framework/issues/8208)
[the example here](https://v3.nuxtjs.org/getting-started/seo-meta#example-1) is currently broken, this PR adds the missing quote to fix the code example.
Resolves #8208
> docs: add missing quote to the example code on 5.seo-meta.md

- packages/nuxt/package.json
- packages/nuxt/src/core/runtime/nitro/renderer.ts
- packages/schema/package.json
- pnpm-lock.yaml
Update route rules imports to follow latest nitropack-edge...
> refactor: use `getRouteRules`

- .stackblitz/config.json
This adds a start command for [Codeflow support](https://stackblitz.com/codeflow).
> chore: add start command for stackblitz codeflow

- packages/nuxt/src/app/composables/preload.ts
This is seemingly not compiled down 🤔 and is [not compatible](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment#browser_compatibility) with Node 14.
> fix(nuxt): don't use or assignment

- package.json
- packages/test-utils/package.json
- pnpm-lock.yaml
- renovate.json
> chore: upgrade vitest to 0.24

- docs/content/1.getting-started/5.transitions.md
https://github.com/nuxt/framework/issues/8384
> docs: add missing `app` key for transitions

- docs/content/6.bridge/1.overview.md
Added warnings to useHead and added verbiage to let users know @vueuse/head needs to be added to package.json
> docs: updated bridge migration guide

- docs/content/2.guide/2.directory-structure/1.pages.md
https://github.com/nuxt/framework/issues/8460
> docs: mention use case for `<KeepAlive>` in `definePageMeta`

- renovate.json
We disabled `@vueuse/head` updates at some point but it would be useful to have these again.
> chore: reenable auto-upgrades for vueuse/head

- docs/content/5.community/5.roadmap.md
> docs: update roadmap for november

- examples/advanced/config-extends/package.json
- examples/advanced/jsx/package.json
- examples/advanced/module-extend-pages/package.json
- examples/advanced/testing/package.json
- examples/app-config/package.json
- examples/app/error-handling/package.json
- examples/app/plugins/package.json
- examples/app/teleport/package.json
- examples/auto-imports/components/package.json
- examples/auto-imports/composables/package.json
- examples/composables/use-async-data/package.json
- examples/composables/use-cookie/package.json
- examples/composables/use-fetch/package.json
- examples/composables/use-head/package.json
- examples/composables/use-state/package.json
- examples/essentials/hello-world/package.json
- examples/experimental/reactivity-transform/package.json
- examples/experimental/vite-node/package.json
- examples/experimental/wasm/package.json
- examples/other/locale/package.json
- examples/routing/layouts/package.json
- examples/routing/middleware/package.json
- examples/routing/nuxt-link/package.json
- examples/routing/pages/package.json
- examples/routing/universal-router/package.json
- examples/server/routes/package.json
This PR upgrades Nuxt version to RC 13 in the `examples/` directory
> chore(examples): bump nuxt version

- packages/nuxt/src/app/plugins/router.ts
> style(nuxt): lint `Route` interface

- docs/content/3.api/4.advanced/2.kit.md
https://github.com/nuxt/framework/issues/3209
This adds a stub entry in API for `extendPages`.
> docs: add entry for `extendPages`

- packages/nuxi/src/commands/upgrade.ts
> fix(nuxi): upgrade with `latest` tag

- README.md
> chore: update badges in readme to latest

- docs/content/1.docs/1.getting-started/11.upgrade.md
- docs/content/1.docs/6.bridge/1.overview.md
- docs/content/1.docs/6.bridge/2.bridge-composition-api.md
- docs/content/1.docs/6.bridge/index.md
- docs/content/1.docs/7.migration/1.overview.md
- docs/content/1.docs/7.migration/2.configuration.md
- docs/content/1.docs/7.migration/20.module-authors.md
- docs/content/1.docs/7.migration/3.auto-imports.md
- docs/content/1.docs/7.migration/6.pages-and-layouts.md
- docs/content/1.docs/7.migration/7.component-options.md
- docs/content/1.docs/7.migration/index.md
#9047
This PR fixes the errors when accessing the migration guides on the website
> docs: fix paths to migration guides

- docs/content/v3.md
> chore(typo): link fix

- docs/content/1.docs/1.getting-started/3.configuration.md
- docs/content/1.docs/2.guide/1.concepts/5.modules.md
- docs/content/1.docs/3.api/1.composables/use-fetch.md
- docs/content/1.docs/3.api/1.composables/use-runtime-config.md
- docs/content/1.docs/3.api/4.advanced/1.hooks.md
- docs/content/1.docs/3.api/4.advanced/2.kit.md
- docs/content/1.docs/4.examples/6.advanced/module-extend-pages.md
- docs/content/1.docs/4.examples/6.advanced/testing.md
Fix broken paths with /docs/ prefix
> docs: fix broken paths

- docs/content/1.docs/1.getting-started/11.upgrade.md
Change the stability of Nuxt 3 in the Feature Comparison table accordingly.
[Feature Comparison](https://nuxt.com/docs/getting-started/upgrade#feature-comparison)
> docs: set nuxt stability to stable

- docs/content/1.docs/6.bridge/1.overview.md
I'm not sure if `nuxt-bridge` will work with `@nuxt/content` 🤔, but I'd thought I'd update the reference here. If it does not work with `nuxt-bridge`, we should communicate that folks will need to adopt nuxt3 if they want to use the content module.
> docs: update reference to @nuxt/content

- docs/public/robots.txt
This PR adds a `robots.txt` file with default rules
> docs(seo): add robots file

- examples/advanced/config-extends/package.json
- examples/advanced/jsx/package.json
- examples/advanced/module-extend-pages/package.json
- examples/advanced/testing/package.json
- examples/app-config/package.json
- examples/app/error-handling/package.json
- examples/app/plugins/package.json
- examples/app/teleport/package.json
- examples/auto-imports/components/package.json
- examples/auto-imports/composables/package.json
- examples/composables/use-async-data/package.json
- examples/composables/use-cookie/package.json
- examples/composables/use-fetch/package.json
- examples/composables/use-head/package.json
- examples/composables/use-state/package.json
- examples/essentials/hello-world/package.json
- examples/experimental/reactivity-transform/package.json
- examples/experimental/vite-node/package.json
- examples/experimental/wasm/package.json
- examples/other/locale/package.json
- examples/routing/layouts/package.json
- examples/routing/middleware/package.json
- examples/routing/nuxt-link/package.json
- examples/routing/pages/package.json
- examples/routing/universal-router/package.json
- examples/server/routes/package.json
Update nuxt versions in examples
> chore: update example nuxt versions

- docs/content/1.docs/2.guide/4.going-further/11.edge-channel.md
> docs: Update edge-channel-docs with non-rc nuxt version

- docs/content/1.docs/3.api/5.commands/add.md
> docs: fix typo in `commands/add`

- docs/content/1.docs/1.getting-started/6.data-fetching.md
- docs/content/1.docs/3.api/3.utils/define-nuxt-component.md
Since Nuxt 3 is stable, we can remove these warnings.
> docs: remove stable release warning regarding options api

- docs/content/0.index.md
> docs: correct grammar/typo in modules section on index page

- docs/content/1.docs/1.getting-started/6.data-fetching.md
just added a space before "Here's a list of..." for a better reading experience
> docs: add space between sentences

- docs/content/1.docs/5.community/4.framework-contribution.md
Update MDC VSCode extension link in Contribution guide
> docs: update link to mdc extension

- docs/package.json
- docs/yarn.lock
Bump website theme version to 0.1.11 to fix fetching error on Jobs
> docs: bump website theme to 0.1.11

- docs/content/1.docs/5.community/5.roadmap.md
> docs(roadmap): add i18n module to the roadmap

- docs/package.json
- docs/yarn.lock
Bump website theme version to 0.1.13
> docs: theme version 0.1.13

- docs/content/1.docs/1.getting-started/9.testing.md
> docs: update playwright url

- docs/content/1.docs/3.api/3.utils/preload-route-components.md
This PR adds documentation for `preloadRouteComponents` utility.
> docs: add docs for `preloadRouteComponents`

- docs/content/1.docs/1.getting-started/1.introduction.md
After reading the [Contribution page](https://nuxt.com/docs/community/contribution), it wasn't clear if I had to create an issue for this kind of errors.
> docs: add missing line breaks

- docs/yarn.lock
Bump website theme version to 0.1.23
> docs: bump website theme to 0.1.23

- docs/package.json
- docs/yarn.lock
> docs(theme): version 0.1.24

- docs/package.json
- docs/yarn.lock
> docs(version): theme 0.1.25

- docs/content/1.docs/5.community/1.nuxt-community.md
- docs/package.json
- docs/yarn.lock
> docs(community): temporary disable newsletter subscription

- packages/kit/README.md
- packages/nuxi/README.md
- packages/nuxi/src/commands/info.ts
- packages/nuxt/README.md
- packages/schema/src/config/adhoc.ts
- packages/schema/src/config/nitro.ts
- packages/schema/src/config/typescript.ts
- packages/schema/src/types/imports.ts
- packages/vite/README.md
- packages/webpack/README.md
Update the links to the main website.
> docs: link to nuxt.com instead of v3.nuxtjs.org

- docs/package.json
- docs/yarn.lock
nuxt.com Website theme v0.1.27
> docs: version 0.1.27

- docs/content/1.docs/2.guide/3.going-further/7.layers.md
> docs: improve wording and fix typo

- docs/.env.example
- docs/package.json
- docs/yarn.lock
Thanks to @danieroe for this 🚀
> docs: enable hybrid rendering

- docs/content/1.docs/1.getting-started/1.introduction.md
> docs: fixed typos and improved wording

- docs/content/1.docs/1.getting-started/3.configuration.md
- docs/content/1.docs/5.community/3.reporting-bugs.md
- docs/content/1.docs/5.community/4.contribution.md
This PR fixes a few minor typos and capitalization issues:
* 'overriden' -> 'overridden'
* 'Typescipt' -> 'TypeScript'
* 'prettier' -> 'Prettier'
* 'corepack' -> 'Corepack'
* 'nuxt' -> 'Nuxt'
> docs: fix typos and capitalisation

- docs/content/1.docs/1.getting-started/5.seo-meta.md
- docs/content/1.docs/2.guide/1.concepts/5.modules.md
> docs: fix typos

- docs/content/4.support/3.us.md
> docs(sponsors): fix hero

- docs/content/4.support/1.solutions.md
Update wording on support page
> docs(support): update wording

- docs/yarn.lock
Experiencing some style degradation caused by updating the docs lockfile, this PR is to confirm the cause.
> chore(docs): revert lockfile

- docs/package.json
- docs/yarn.lock
Publish v0.3.5 of website theme
> docs(version): 0.3.5

- docs/content/4.support/1.solutions.md
- docs/content/4.support/2.agencies/2.ship-shape.md
- docs/content/4.support/2.agencies/3.64robots.md
- docs/content/4.support/2.agencies/4.passionate-people.md
- docs/content/4.support/2.agencies/5.curotec.md
- docs/content/4.support/2.agencies/6.mirahi.md
- docs/content/4.support/2.agencies/7.webreinvent.md
- docs/content/4.support/2.agencies/8.software-things.md
- docs/content/4.support/2.agencies/9.zen-architects.md
- docs/content/4.support/2.agencies/91.funkhaus.md
- docs/content/4.support/2.agencies/92.the-coding-machine.md
- docs/content/4.support/2.agencies/93.epicmax.md
- docs/content/4.support/2.agencies/94.brain.md
- docs/content/4.support/2.agencies/96.macopedia.md
- docs/content/v3.md
- packages/kit/src/build.ts
- packages/nuxt/src/app/config.ts
- packages/nuxt/src/components/loader.ts
- packages/nuxt/src/pages/page-meta.ts
- packages/schema/src/config/app.ts
- packages/schema/src/types/components.ts
- packages/schema/src/types/hooks.ts
- packages/webpack/src/configs/client.ts
- packages/webpack/src/presets/style.ts
- test/basic.test.ts
applying case police goodness to other parts of the monorepo than just the docs
> chore: case police update

- docs/package.json
- docs/yarn.lock
> docs(version): 0.3.6

- docs/content/1.docs/2.guide/3.going-further/3.modules.md
None
Changes the link to the ESM guide.
> docs: update link

- docs/yarn.lock
Use Nuxt edge channel for the nuxt.com website
> docs(version): use nuxt edge channel

- docs/yarn.lock
> docs(version): revert back to stable nuxt version

- docs/package.json
- docs/yarn.lock
> docs(version): 0.3.8

- docs/content/1.docs/2.guide/3.going-further/2.hooks.md
Remove parentheses from setup defineNuxtModule, there is an error at that line.
Remove parentheses from setup defineNuxtModule, there is an error at that line.
> docs: remove stray parenthesis

- packages/kit/src/resolve.ts
> chore: fix typo in comment

- docs/package.json
- docs/yarn.lock
> docs(version): 0.3.10

- docs/content/vision-2023.md
#resolves nuxtlabs/nuxt.com#1171
> docs: fix hydration warnings on 2023 vision article

- packages/nuxi/src/commands/init.ts
https://github.com/nuxt/framework/pull/9946#issuecomment-1371278864
- ~[ ] 📖 Documentation (updates to the documentation or readme)~
- ~[ ] 🐞 Bug fix (a non-breaking change that fixes an issue)~
- ~[ ] ✨ New feature (a non-breaking change that adds functionality)~
- ~[ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)~
Prevent showing stack traces if an error happens while attempting to download the template.
- ~[ ] I have updated the documentation accordingly.~
> fix(nuxi): prevent showing stack traces while scaffolding
