nuxt/framework

- packages/vite/src/vite-node.ts
#5018
This reuses the externalization options from `dev-bundler` to make the behaviour more consistent.
> fix(vite): use `externality` to handle vite-node externals

- packages/vite/src/dev-bundler.ts
- packages/vite/src/server.ts
- packages/vite/src/utils/external.ts
- packages/vite/src/vite-node.ts
as https://github.com/nuxt/framework/pull/6153#pullrequestreview-1051018071
> refactor(vite): reuse logics and improve code splitting

- packages/nuxt/src/head/runtime/composables.ts
resolves #5554
This updates the types to reflect that these can be computed values.
> fix(nuxt): allow `useHead` to accept computed values

- packages/schema/src/config/_app.ts
- packages/schema/src/types/config.ts
resolves #5477
An early return for functions solves some issues with functional types (including missing types for `hook`, for example). There were also a couple of incorrect types in `_app`.
> fix(schema): exclude functions from `DeepPartial`

- packages/nuxt/src/core/runtime/nitro/renderer.ts
`.renderMeta` is not defined in SPA mode. I think we should also serialize `app.head` for use in this context, but that can be a follow-up PR.
> fix(nuxt): don't call renderMeta if it is not defined

- packages/kit/package.json
- yarn.lock
When running build to the repo, it warns:
```bash
ℹ Building @nuxt/kit
WARN  Inlining implicit external ohash
WARN  Inlining implicit external ohash
```
> fix(kit): add implicit `ohash` dependency

- packages/vite/src/plugins/composable-keys.ts
resolves https://github.com/nuxt/framework/issues/6178
Introduced in #4955, we were creating hashed based on code index. But this differs between server + client for vue components (among others) due to differences in the code generated in the two environments. However, I think the _order_ of keyed composables is more solid and likely to remain fixed between client/server.
Other approaches I also tried:
1. using sourcemaps to get original LOC - I think the best approach conceptually. This did not match however (1 line out), surprisingly, due to a bug (I think) in vite's vue plugin - I'll need to investigate further and report. Additionally, we don't yet have isomorphic support for sourcemaps in unplugin (https://github.com/unjs/unplugin/issues/146) so it would add some complexity for …
> fix(vite, webpack): generate composable keys based on order

- test/fixtures/basic/components/WithSuffix.global.vue
- test/fixtures/basic/components/global/TestGlobal.vue
Small issue - we're getting a hydration error because these components need to be wrapped in a `<div>`.
> test: wrap components with `<div>`

- packages/schema/build.config.ts
- packages/schema/src/config/vite.ts
- packages/schema/src/types/config.ts
resolves #6218
This adds typings for `vite.vue` to the schema.
> fix(schema): add typings for `vite.vue` options

- packages/nuxt/src/core/app.ts
#3222 
Following up https://github.com/nuxt/framework/issues/3222 (extends support progress) this PR allows extending `app.vue`.
> feat(nuxt): extends support for app.vue

- packages/schema/src/config/webpack.ts
- test/utils.ts
We are outputting `.js` files for webpack, which means we also don't add the `crossorigin` attribute when rendering. Because of a typo in our tests we weren't pick up on this.
Bug shows up with following warnings (+ double fetches of all webpack JS assets):
```
A preload for 'http://localhost:3000/_nuxt/59e3a34.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
The resource http://localhost:3000/_nuxt/59e3a34.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```
> fix(webpack): output `.mjs` to use crossorigin preloads

- packages/kit/src/resolve.ts
…vided
`resolvePath` utility, has a fast path check to directly return absolute and existing paths but this prevents continuing searching for extensions when there is an existing directory (`/full/path/app` stops searching for `/full/path/app.vue`).
> fix(kit): try extensions with `resolvePath` with absolute input

- packages/nuxt/src/pages/utils.ts
- packages/nuxt/test/pages.test.ts
failing case shown in updated test
This PR checks that a potential parent is not a catchall before giving it children, which can lead to very unexpected behaviour when present.
> fix(nuxt): do not allow catchalls to have child routes

- packages/nuxt/src/core/plugins/import-protection.ts
resolves #6271
This narrows down import protection for `nuxt.config`. Vite will pass the id `/nuxt.config.ts` even when aliased or relative imports are used. Webpack will pass the full ID so it's possible to devise imports that won't be caught (but the import of `defineNuxtConfig` from `nuxt` will be caught).
> fix(nuxt): narrow `nuxt.config` import protection

- packages/nuxt/src/app/components/nuxt-root.vue
- packages/nuxt/src/app/composables/router.ts
- packages/nuxt/src/pages/runtime/page.ts
- packages/nuxt/src/pages/runtime/router.ts
resolves #6274
This PR provides the current route directly at the point of suspense, meaning within the context of a suspense fork, the route will not change until suspense has resolved. We also update the default `useRoute` behaviour to mean that the route will not change outside of a page context until suspense has resolved.
**Context**: https://github.com/nuxt/framework/pull/4124, https://github.com/nuxt/framework/issues/4122, https://github.com/nuxt/framework/pull/4092.
---
**Previous behaviour**:
**New behaviour**:
> fix(nuxt): separate routes for different suspense forks

- docs/content/2.guide/2.features/4.head-management.md
- packages/nuxt/package.json
- packages/nuxt/src/head/runtime/lib/vueuse-head.plugin.ts
- test/basic.test.ts
- test/fixtures/basic/pages/head.vue
- test/fixtures/basic/pages/index.vue
- yarn.lock
Related PR: https://github.com/vueuse/head/commit/1382c43c5efd9d00efb17fefefa732febbea2d80
When working on https://github.com/nuxt/framework/pull/6293, I updated the @vueuse/head package to get the [dedupe fix](https://github.com/vueuse/head/commit/c02a96fd2489e74a1bf80ceb64f128f544629b4a). 
In updating, I noticed that all titles had duplicate template processing. For example `Home - My Title`, became `Home - My Title - My Title`. This was due to @vueuse/head introducing its own [titleTemplate](https://github.com/vueuse/head/commit/1382c43c5efd9d00efb17fefefa732febbea2d80) feature.
I figured the best course of action would be to adopt the native titleTemplate logic which, as far as I tested, includes the same feature set. 
All seems to work well, however, there is one very minor …
> fix(nuxt): avoid duplicate titleTemplate

- docs/content/2.guide/2.features/4.head-management.md
- packages/nuxt/src/core/runtime/nitro/renderer.ts
- packages/nuxt/src/head/runtime/lib/vueuse-head.plugin.ts
- test/basic.test.ts
- test/fixtures/basic/pages/head.vue
@vueuse/head PR: https://github.com/vueuse/head/pull/67
issues: https://github.com/nuxt/framework/issues/2374, https://github.com/nuxt/framework/issues/5014, https://github.com/nuxt/framework/issues/3130
With nuxt using the latest version of @vueuse/head, it already has support for appending script and links to the end of the body tag with the `body: true` option. 
However due to a mismatch with property names of NuxtMeta and @vueuse/head nothing is rendered, this fixes that and adds some small doc and tests around the feature
Note: This does not work in components, this will need to be looked at in a separate PR as there is some extra complexity involved
> fix(nuxt): render head scripts that use `body: true`

- packages/kit/src/resolve.ts
This PR allows module authors to opt-out of following symbolic links when using `resolveFiles`, as there are many cases where this current default isn't the desired.
> feat(kit): support `followSymbolicLinks` option for  `resolveFiles`

- docs/nuxt.config.ts
Hi, By adding `<meta name="theme-color " />` we can customise the colour of the app bar. For more info please [click here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color)
I have added #00db80 as a theme-colour  :)
_Extremely sorry if I made any mistakes :(_
> docs: add `theme-color` meta

- packages/nuxt/src/core/nitro.ts
As a regression of https://github.com/unjs/nitro/issues/166, we were generating `dist/200/index.html` instead of `dist/200.html` for spa fallbacks. This makes expected output.
> fix(nuxt): generate `200.html` and `404.html` spa fallback files

- docs/utils/createTitle.js
#6319 
Display the link directly if no title in `ReadMore` is set, instead of parsing it as it's the link to some page in the documentation.
Resolves #6319
> docs: fix external link display text

- packages/nuxt/src/pages/runtime/page.ts
resolves #6318
This fixes a regression where we _always_ rerender route components.
> fix(nuxt): extract component to provide route

- packages/nuxt/src/app/components/client-only.mjs
Seems there's a compiler bug (which I will look into) giving this error when using client-only. This PR is a hotfix.
```
ERROR  [@vue/compiler-sfc] Missing semicolon. (1:10)                                                  12:30:39
anonymous.vue
22 |    const { setup, render: _render, template: _template } = component
23 |    if (_render) {
24 |      // override the component render (non <script setup> component)
|                                                                    ^
25 |      component.render = (ctx, ...args) => {
26 |        return ctx.mounted$
anonymous.vue
22 |    const { setup, render: _render, template: _template } = component
23 |    if (_render) {
24 |      // override the component render (non <script setup> component)
| …
```
> fix(nuxt): remove literal `<script setup>` from comment

- packages/vite/src/runtime/vite-node.mjs
- packages/vite/src/vite-node.ts
close #6243
This PR implemented the full HMR support of vite-node as mentioned in https://github.com/nuxt/framework/pull/6154#issuecomment-1195505167
Re #6243, the bug is caused because in the release build, `entry.mjs` is laying under `node_modules` which bypasses the cache clear up due to https://github.com/nuxt/framework/pull/6153
> fix(vite): improve `vite-node` hmr

- docs/content/3.api/4.advanced/1.hooks.md
Resolves #6327
I would love a second pair of eyes to make sure I am not mistaken.
> docs(api): add missing hooks and environment column

- packages/vite/src/runtime/vite-node.mjs
Previous: #6281
This PR adds console output when vite server is rebuilt with vite-node enabled.
Since vite-node has a passive rebuild mechanism, we could only show it after file changes and by next request.
(PS: Damn is fast!!)
> feat(vite): log vite-node hmr updates

- packages/kit/src/internal/cjs.ts
- packages/nuxi/src/commands/info.ts
- packages/schema/src/config/_common.ts
Related: #6340, https://github.com/unjs/unctx/pull/23, https://github.com/unjs/unctx/issues/25
Some dependencies like `estree-walker`, are not only esm-only but only use `exports.import` field in `package.json`. This makes sure they are broken unless using esm native resolution!
We introduced an experimental flag few months ago for jiti to enable esm resolution and handle such package. It is already enabled for c12 and framework repo. This PR enabled it for kit utils as well.
> fix(nuxi, kit): enable `esmResolve` flag for `jiti`

- packages/nuxt/src/core/app.ts
- packages/nuxt/src/core/plugins/unctx.ts
- test/fixtures/basic/modules/example.ts
- test/fixtures/basic/modules/runtime/middleware.ts
- test/fixtures/basic/modules/runtime/plugin.ts
resolves  #6300
When a plugin is in injected like `/path/to/someplugin` without the extension, we can likely match `/path/to/someplugin.*`. A more accurate, but more costly, route would be to use `resolvePath` when adding plugins (or to normalize afterwards before `app:resolve`.
> fix(nuxt): resolve plugins and middleware to their full path

- packages/test-utils/src/server.ts
- packages/test-utils/src/types.ts
I seems that we forgot to remove the code related to `listener` in #3755
> refactor(test-utils): remove unused codes

- test/basic.test.ts
- test/fixtures/basic/pages/keyed-composables.vue
Adds some extra tests to protect against https://github.com/nuxt/framework/issues/6178. See also https://github.com/nuxt/framework/pull/6191.
> test: add key matching test for keyed composables

- packages/nuxt/src/pages/macros.ts
- test/basic.test.ts
resolves #6023
Currently any CSS imports or other imports with side effects in meta chunk are preserved. This change strips them, which enables bundle splitting for page CSS.
> fix(nuxt): remove side-effect imports from page metadata

- packages/schema/src/config/_app.ts
- this [example ](https://v3.nuxtjs.org/api/configuration/nuxt.config#head) is a configuration for `<head>` have missed `,`
> docs(schema) : add a missing comma in example config 

- docs/content/3.api/1.composables/use-fetch.md
> docs(useFetch): minor punctuation fixes

- docs/content/2.guide/3.directory-structure/10.pages.md
- packages/schema/src/config/router.ts
Updated links to the correct Vue Router Options documentation URL
[https://router.vuejs.org/api/#routeroptions](https://router.vuejs.org/api/#routeroptions) (broken) -> [https://router.vuejs.org/api/interfaces/routeroptions.html](https://router.vuejs.org/api/interfaces/routeroptions.html) (working)
> docs: update vue-router links

- packages/kit/package.json
- packages/kit/src/internal/template.ts
- packages/nuxt/src/core/templates.ts
- yarn.lock
This reverts commit d135608ef0d607259c0ae6f5156c8f46ff78ddc3.
https://github.com/nuxt/content/issues/1422
This reverts https://github.com/nuxt/framework/pull/6030, returning template utils API to previous behaviour/shape. At the same time, it moves the fix in that PR into nuxt internals and deprecates the template utils. (There are other utils that can be used directly with `knitwork`, `mlly`, etc.)
> fix(kit): move relative path handling back into nuxt templates

- packages/nuxt/src/app/composables/error.ts
- packages/nuxt/src/pages/runtime/router.ts
With #4539 and https://github.com/unjs/h3/pull/148 we introduced new `fatal` flag for error that are intended to be logged. 404 Page not found errors we throw are not _fatal_ to be verbosely logged by h3.
Also with this change, `showError` by default does not set fatality of error but only mark there is an error and display it (locally testing works both when calling from client and server side).
Related: In future versions of h3, we might make createError smarter to infer fatal flag from known codes.
Appendix current output:
> fix(nuxt): do not log `404` and `showError` as fatal by default

- packages/nuxt/package.json
- packages/nuxt/src/core/runtime/nitro/renderer.ts
- yarn.lock
Update nitropack to latest releast ([changelog](https://github.com/unjs/nitro/blob/main/CHANGELOG.md)). 
One major improvement is that with the latest nitropack, we can use new `defineRenderHandler` that allows caching, response handling and assets (such as `favicon.ico`) fallback. And enhanced in parallel to nuxt releases.
[edge-only] Breaking change: `nuxt:app:response({ response })` nitro hook will be changed to `render:response(response, { event })`
> feat(nuxt): update nitropack to latest

- packages/vite/src/vite-node.ts
`@vite/client` is a module. Without this we get `Uncaught SyntaxError: import declarations may only appear at top level of a module`. Evidently missed from vue-bundle-renderer upgrade.
> fix(vite): add `module` type to vite node entry

- docs/content/2.guide/5.deploy/2.static-hosting.md
> docs: update full static status

- packages/nuxt/src/pages/utils.ts
- packages/schema/src/config/experimental.ts
Resolves #6204
Vue-router has a built-in feature to interop default export of component imports (Source code: [here](https://github.com/vuejs/router/blob/df836529db63360f0bf9810ccd4e8911846aef45/packages/router/src/utils/index.ts#L10) and [here](https://github.com/vuejs/router/blob/df836529db63360f0bf9810ccd4e8911846aef45/packages/router/src/navigationGuards.ts#L317))
`isESModule` utility in `vue-router` normally works when importing in native esm (`obj[Symbol.toStringTag] === 'Module'`) or with esm-compatible chunks (`obj.__esModule`). But this can be broken if there is a second transform build step (in this case was recent change in netlify builder) that converts component dynamic imports to simple `{ default: [getter] }` without `__esModule` flag.
This PR, enables a more direct …
> fix(nuxt): interopDefault for page component imports

- packages/nuxt/src/app/composables/asyncData.ts
A regression of https://github.com/nuxt/framework/pull/6441 - we were not passing context to asyncdata calls.
> fix(nuxt): ensure asyncdata handler has nuxt app context

- packages/nuxt/src/head/runtime/lib/vueuse-head.plugin.ts
- test/fixtures/basic/pages/index.vue
follow on from #6296
It seems we have a little leftover `titleTemplate` handling. I think we don't need this - was there a reason we left it in?
If you were previously using `titleTemplate: null` you should update this to `titleTemplate: ''`.
> refactor(nuxt)!: remove `null` handling for `titleTemplate`

- packages/nuxt/src/core/runtime/nitro/error.ts
https://github.com/unjs/h3/pull/162
This logs fatal errors in addition to unhandled ones.
> fix(nuxt): log fatal errors as well as unhandled ones

- packages/nuxi/src/commands/upgrade.ts
- packages/nuxi/src/utils/fs.ts
- Handle situation when local nuxt is not installed
- Fix typo introduced in #6125 for force-upgrade cleanup
- Improve `rmRecursive` util to validate input, gracefully handle errors and support debugger
- Ensure lockfile exists after force cleanup
> fix(nuxi): fix issues with `nuxi upgrade`

- packages/vite/src/dev-bundler.ts
Resolves #6527
Regression might have appeared with #6355. When checking for external paths, `@fs/` prefix should be omited as is a vite-specific prefix. Windows paths are still safe since with have `pathToFileURL` for generating import statements.
> fix(vite): remove `/@fs` from external ids

- docs/content/1.getting-started/1.quick-start.md
none
For newcomers, when they first see the `defineNuxtConfig` section, they don't know in which file to modify the configuration, it would be better if the path to the file is given
---
> docs(quick-start): clarify using `nuxt.config` to disable shims

- packages/schema/src/config/_app.ts
- packages/schema/src/config/_common.ts
- packages/schema/src/config/build.ts
- packages/schema/src/config/experimental.ts
- packages/schema/src/config/generate.ts
- packages/schema/src/config/nitro.ts
- packages/schema/src/config/render.ts
- packages/schema/src/config/router.ts
- packages/schema/src/config/typescript.ts
- packages/schema/src/config/vite.ts
- packages/schema/src/config/webpack.ts
- packages/schema/src/types/compatibility.ts
- packages/schema/src/types/components.ts
- packages/schema/src/types/imports.ts
- packages/schema/src/types/module.ts
- packages/schema/src/types/nuxt.ts
> docs(schema): grammar, punctuation and typo fixes

- packages/nuxt/src/core/nitro.ts
Resolves #6534
`vue-router`, uses new esm export conditions (dev, prod) which solved to remove devtools from production bundle in #5874 but other dependencies such as `vue-i18n`, with their bundler dist depend on special `__VUE_PROD_DEVTOOLS__` flag. This PR explicitly sets it to remove from final nitro bundle.
Note: We still need to fix `@vue/devtools-api` mock to avoid conditions it is leaked for any other reason.
> fix(nuxt): tree-shake devtools from production bundle

- packages/nuxt/src/components/module.ts
- packages/vite/src/client.ts
- packages/vite/src/plugins/cache-dir.ts
- packages/vite/src/plugins/dev-ssr-css.ts
- packages/vite/src/runtime/vite-node.mjs
- packages/vite/src/vite-node.ts
With a custom `srcDir`, various things were not working, including scanning of new components.
This also makes a couple of changes to vite-node, to match the non-vite node implementation where `root` is set to `srcDir` and not `rootDir` but would value @antfu's verdict on these.
> fix(vite, nuxt): resolve relative to `srcDir` rather than `rootDir`

- packages/schema/src/config/webpack.ts
- packages/vite/src/client.ts
https://github.com/nuxt/framework/pull/6232#issuecomment-1199214638
https://github.com/nuxt/framework/discussions/6168
Now that we have updated `vue-bundle-renderer`, we can output`.js` files on client-side, for better support with CDN/web servers.
This PR also allows users to configure their output filenames on vite. (Previously it always overrode them.)
```js
import { defineNuxtConfig } from 'nuxt'
vite: {
build: {
rollupOptions: {
output: {
chunkFileNames: '_nuxt/[hash].mjs'
}
}
}
}
})
```
> feat(webpack, vite): default to `.js` extension for client

- docs/content/2.guide/3.directory-structure/4.components.md
Add 'fallbacktag', without adding 'placeholder' and 'placeholdertag'`
> docs(components): use `fallbackTag` in `ClientOnly` examples

- packages/nuxi/src/commands/dev.ts
- packages/vite/src/vite-node.ts
Currently, vite-node depends on `server.port` for listener. It works for default port and also when using `PORT` environment variable. But in case of random or fallback port, it fails. This PR updates those from real value in listener
> fix(nuxi): update `server.port` and `server.host` with listener info

- packages/vite/src/client.ts
resolves #6586
Interestingly, vite does not always use `renderBuiltUrl` but sometimes checks `.base` by itself. This sets a relative base as the default, which will mean that vite-inserted link preloads will point to the correct location with a dynamic base.
> fix(vite): pass relative url as default base

- packages/nuxt/package.json
- packages/nuxt/src/core/plugins/unctx.ts
- packages/nuxt/src/pages/macros.ts
- packages/vite/package.json
- packages/vite/src/client.ts
- packages/vite/src/css.ts
- packages/vite/src/dev-bundler.ts
- packages/vite/src/manifest.ts
- packages/vite/src/plugins/analyze.ts
- packages/vite/src/plugins/cache-dir.ts
- packages/vite/src/plugins/composable-keys.ts
- packages/vite/src/plugins/virtual.ts
- packages/vite/src/server.ts
- packages/vite/src/utils/external.ts
- packages/vite/src/utils/index.ts
- packages/vite/src/utils/wpfs.ts
- packages/vite/src/vite-node.ts
- packages/vite/src/vite.ts
- packages/vite/tsconfig.json
- packages/webpack/package.json
- yarn.lock
> refactor(vite):  enable strict type checking 

- packages/nuxt/src/app/composables/asyncData.ts
resolves #4702
We were ignoring `initialCache` setting if data was already present in payload. I've exempted us from respecting `initialCache` if we are hydrating. (In this case, `server: false` should be used rather than `initialCache: false`.)
> fix(nuxt): don't set asyncData to existing payload on CSR if `initialCache` is disabled

- packages/schema/src/config/experimental.ts
- packages/schema/src/types/config.ts
- packages/vite/src/vite.ts
#6227
This PR enables opting out from entry point warmup feature of vite using `vite.warmupEntry: false`.
This feature ensures that nuxt starts transforming entrypoint code before developer even initiates first request to any page, speeding up time from command to initial render. But as @antfu mentioned, there might be performance overhead in concurrency.
> feat(vite): allow disabling entry warmup

- packages/vite/src/utils/warmup.ts
- packages/vite/src/vite.ts
#6647
Without this fix, we were actually adding some overhead to transform server assets without ssr condition.
> fix(vite): warmup server entries with `ssr` condition

- docs/content/2.guide/2.features/5.data-fetching.md
- docs/content/2.guide/2.features/9.server-routes.md
- docs/content/2.guide/3.directory-structure/5.composables.md
Review of https://github.com/nuxt/framework/pull/5770, https://github.com/nuxt/framework/pull/6507 and https://github.com/nuxt/framework/pull/6615.
> docs: tweaks for data fetching, server routes and composables

- packages/nuxt/src/pages/module.ts
- packages/schema/build.config.ts
- packages/schema/src/types/hooks.ts
- packages/vite/src/manifest.ts
- packages/webpack/src/plugins/vue/client.ts
- packages/webpack/src/presets/vue.ts
https://github.com/nuxt/framework/issues/6638
This excludes page chunks from being prefetched within HTML, as these can be managed specifically via vue-router + NuxtLink. (And possibly even handled via nitro prerenderer: https://github.com/nuxt/framework/issues/3649#issuecomment-1125879884.)
> feat(nuxt): exclude page chunks from being prefetched

- packages/nuxi/src/commands/cleanup.ts
- packages/nuxi/src/commands/dev.ts
- packages/nuxi/src/commands/upgrade.ts
- packages/nuxi/src/utils/fs.ts
- packages/nuxi/src/utils/nuxt.ts
Resolves #6668 and adds basic manifest implementing #6670
When a major change in a project happens (such as updating nuxt or renaming directory) we most likely need to invalidate caches to avoid unpredictable behavior. This PR does two things:
- Write a basic `nuxt.json` to `buildDir`/`.nuxt` only for `nuxi dev` (1)
- Checks manifest hash (full hash) against the previous build and call `nuxi cleanup` in case of hash mismatches.
Remarks:
- I've not included more extensive manifest info and hashes unless we find initial change is not enough. As mentioned by @danielroe in #6668, bundlers (vite and webpack) also handle cache invalidation for dependencies
- We probably need to generate two separate manifests for dev and prod (https://github.com/nuxt/framework/issues/6671)
- It only invalidates …
> feat(nuxi): auto cleanup with project manifest changes

- packages/nuxt/src/components/tree-shake.ts
resolve https://github.com/nuxt/framework/issues/6673
Hi, this PR aims to add missing attributes when the tag is not a self-closing tag by fixing the regex. Previously, attributes were missing on non self-closing tags.
Test fixtures of this PR can be considered as included by PR https://github.com/nuxt/framework/pull/6584 ?
> fix(nuxt): include tag attrs for non self-closing tags in tree-shake regex

- docs/content/2.guide/2.features/9.server-routes.md
- docs/content/2.guide/5.deploy/1.node-server.md
- docs/content/2.guide/5.deploy/3.presets.md
- docs/content/2.guide/5.deploy/providers/aws.md
- docs/content/2.guide/5.deploy/providers/azure.md
- docs/content/2.guide/5.deploy/providers/cloudflare.md
- docs/content/2.guide/5.deploy/providers/digitalocean.md
- docs/content/2.guide/5.deploy/providers/firebase.md
- docs/content/2.guide/5.deploy/providers/heroku.md
- docs/content/2.guide/5.deploy/providers/layer0.md
- docs/content/2.guide/5.deploy/providers/netlify.md
- docs/content/2.guide/5.deploy/providers/render.md
- docs/content/2.guide/5.deploy/providers/stormkit.md
- docs/content/2.guide/5.deploy/providers/vercel.md
- packages/schema/src/config/nitro.ts
> docs: update links to nitro.unjs.io

- packages/nuxt/src/core/runtime/nitro/error.ts
- test/basic.test.ts
Part of #6683
When there is a server error, the `/__nuxt_error` might also fail to render, we fallback to use static HTML render in this case.
> fix(nuxt): fallback to static error page on server error

- packages/nuxi/src/commands/upgrade.ts
When using `nuxi update` command with a custom path, it won't honour that path when running the package manager install, instead, it will always run in the `cwd`.
This is apparent in a monorepo or sub-path nuxt installs.
For example, run in this repo `yarn nuxi upgrade ../some-nuxt-app --force` and you'll see it modifies the frameworks package.json and lock.
In providing the proper path, a new issue appears where the `getNuxtVersion` fails. It seems like a cache issue where it's resolving to the old version path, leading to a failure to read the file, as it didn't exist. 
**Exception**
```
ERROR  ENOENT: no such file or directory, open '/home/harlan/forks/nuxt-app/node_modules/.pnpm/nuxt@3.0.0-rc.6/node_modules/nuxt/package.json'                                                 19:49:21 …
```
> fix(nuxi): ensure `nuxi upgrade` runs in rootDir

- packages/nuxi/src/commands/upgrade.ts
- packages/nuxi/src/utils/nuxt.ts
When upgrading RC versions, the Changelog link is assuming that nuxt was installed using a version with a git commit as the suffix. 
For versions that don't have this, only the last digit is used, so the user gets messages like this:
```
ℹ Cleaning up generated nuxt files and caches...                                                                                                                                                20:39:36
ℹ Upgraded nuxt version: 3.0.0-rc.8                                                                                                                                                         20:39:36
✔ Successfully upgraded nuxt from 3.0.0-rc.6 to 3.0.0-rc.8 …
```
> fix(nuxi): properly detect hash and tag for upgrade changelog

- packages/nuxt/package.json
- packages/nuxt/src/core/nitro.ts
- test/fixtures/basic/pages/index.vue
- yarn.lock
resolves https://github.com/nuxt/framework/issues/4325
When `@vue/devtools-api` is imported in an ESM module (as in pinia), our cjs proxy doesn't work. Thanks to @pi0, we now have a standalone stub we can use that works in both ESM + CJS contexts.
> fix(nuxt): use `vue-devtools-stub` to mock `@vue/devtools-api` for both cjs + esm

- packages/schema/src/config/vite.ts
- packages/vite/src/client.ts
resolves #6720, also see https://github.com/nuxt/framework/issues/4084
This enables vite's dedupe functionality for vue, where we definitely want to ensure we have a single instance bundled. A previous issue with this plugin (where it emitted CJS code) seems to have been resolved in Vite 3.
**Edit**: enabling only for client.
~~It injects the following code in the server bundle:~~
https://github.com/vitejs/vite/blob/9e9cd23763c96020cdf1807334368e038f61ad01/packages/vite/src/node/plugins/ssrRequireHook.ts#L53-L71
~~We can alternatively enable this only for the client bundle. WDYT @pi0?~~
> fix(vite): dedupe `vue` in client bundle

- docs/content/2.guide/3.directory-structure/7.layouts.md
> docs: make wording slightly clearer

- docs/content/2.guide/2.features/9.server-routes.md
```
export default anync( should delete ) defineEventHandler(async (event) => {
const data = await useStorage().getItem('redis:test')
return data
})
```
This function should not be called with async。
> docs: fix typo in `defineEventHandler` example

- packages/nuxt/src/components/loader.ts
resolves  #6781
Lazy components (defined with `defineAsyncComponent`) were marked as having a side effect, so were persisting into the routes bundle. We should certainly not be including async component _statements_ within the entry bundle, which _also had_ the effect of marking them as dependencies of the entry rather than the page they correspond to (resulting in over-prefetching - see https://github.com/nuxt/framework/issues/6638).
---
Note that I encountered this when debugging what I believe to be an upstream rollup bug that I'm still looking into, which is difficult to reproduce but essentially boils down to two modules which each contain:
```js
defineAsyncComponent(() => __vitePreload(() => import('./Text.3d3cd0e1.js'),true?"__VITE_PRELOAD__":void 0,import.meta.url));
const meta = …
```
> fix(nuxt): ensure component helper methods do not create side-effects

- packages/nuxt/src/app/config.ts
This fix allows using `useAppConfig().theme` to remain reactive with HMR support
> fix(nuxt): use deep assignment for app.config hmr

- docs/content/3.api/4.advanced/2.kit.md
Added some `@nuxt/kit` utilities I found that are missing from docs
> docs(api): add missing kit utilities

- packages/nuxt/src/pages/runtime/router.ts
resolves  #5467
We only throw a hard error at the moment on server middleware being aborted. But on initial load of a SPA, we also need to throw an error if `abortMiddleware` is called, or the denied page will go ahead and load...
> fix(nuxt): throw hard error on initial spa load if aborted

- packages/schema/src/config/experimental.ts
https://github.com/nuxt/framework/issues/4084
This enables external vue by default on edge releases. Instead, it can be disabled by setting `experimental.externalVue` to `false`. Before RC, we can then remove the flag entirely.
I have tested on a few projects (small + large projects, no monorepo, a module's playground) with no issues, but some issues might be expected, particularly in complex projects with multiple vue component libraries. Feedback is particularly welcome. Please feel free to tag me in a new issue if you encounter any problems.
> feat!(schema): enable external vue by default

- packages/nuxt/src/core/nitro.ts
Somehow we dropped this configuration out. We can hard code defaults in as if user is using webpack builder we can't assume options are compatible. User can override with `nitro.analyze` directly.
> fix(nuxt): pass analyze options through to nitro

- docs/content/3.api/1.composables/update-app-config.md
- examples/advanced/config-extends/app.config.ts
- examples/advanced/config-extends/base/app.config.ts
- packages/nuxt/src/app/config.ts
- packages/nuxt/src/core/templates.ts
- packages/nuxt/src/imports/presets.ts
#6832
Resolves:
- In c54292b17f56609e81fecea29eafcbf01f303ea9 I implemented it how it was made in [@nuxt-themes/kit](https://github.com/nuxt-themes/config/blob/main/src/utils.ts#L47-L53)
- In 1b07424dce819355e2d479bf73639cb70e2e3289 I implemented it using `arrayFn` as suggested in #6832
- Leads to strange behaviors with HMR (array keys going `null` when going from a play array to function format)
- I would say that overwriting is **expected** behavior in this kind of config, and that `function` format seem to introduce a bit of overhead for the user to understand when reading config files.
- This portion of codes properly deepAssign on changes, but does not delete existing keys
- [Reproduction](https://stackblitz.com/edit/nuxt-starter-rsskjr?file=package.json,app.vue,app.config.ts)
Few …
> feat(nuxt): `app.config` improvements

- docs/content/3.api/3.utils/add-route-middleware.md
Added API documentation for `addRouteMiddleware` utility function
> docs(api): add `addRouteMiddleware` util

- docs/content/migration/2.configuration.md
Minor edit: just linked to the exact section for the Nuxt Pinia module.
> docs: update link to pinia nuxt module

- docs/content/2.guide/5.deploy/2.static-hosting.md
As tried, when you want to generate client-side only output, even with "ssr : false" in nuxt.config.ts,
"nuxi build" doesn't generate the correct output, it still generates node ssr output,
but nuxi generate does the job.
> docs(deploy): update command for csr prerendering

- package.json
Add `playground` preview
See the packaged preview
```ts
"dev:start": "yarn run nuxi start playground",
```
> chore: add `dev:preview` for playground preview

- docs/content/3.api/3.utils/abort-navigation.md
Add examples to API documentation for `abortNavigation` utility function
> docs(api): enhance `abortNavigation` util

- docs/content/3.api/3.utils/define-nuxt-route-middleware.md
Added API documentation for `defineNuxtRouteMiddleware` utility function
> docs(api): add `defineNuxtRouteMiddleware` util

- docs/content/3.api/3.utils/define-page-meta.md
Added API documentation for `definePageMeta` utility function
> docs(api): add `definePageMeta` util

- docs/content/bridge/2.bridge-composition-api.md
> docs: replace backtick with apostrophe

- packages/vite/src/manifest.ts
resolves  #7020
Currently, vite manifest gets accidentally included in public assets dir. It is not used and the data within it is incorrect (i.e. non-normalised)
> fix(vite): remove client manifest.json from public dir

- docs/content/2.guide/2.features/5.data-fetching.md
- test/basic.test.ts
- test/fixtures/basic/pages/legacy/async-data.vue
resolves #7013
We have support for asyncData with options API syntax. This PR documents it (with a note that it is likely to change!) and adds a test to ensure it does not break.
Might be worth a discussion about how we want to continue to support this, and (if so) whether it needs any additional features ways of passing options to asyncData.
> docs: add information on how to use options api asyncData

- packages/nuxt/src/app/composables/asyncData.ts
- packages/nuxt/src/app/nuxt.ts
- test/basic.test.ts
- test/fixtures/basic/composables/asyncDataTests.ts
- test/fixtures/basic/pages/useAsyncData/double.vue
- test/fixtures/basic/pages/useAsyncData/promise-all.vue
- test/fixtures/basic/pages/useAsyncData/refresh.vue
- test/fixtures/basic/pages/useAsyncData/single.vue
- test/fixtures/basic/server/api/useAsyncData/count.ts
#4758 #5078 #5738
With the initial implementation of `useAyncData`, we were using a shared promise to avoid running two asyncData promises with the same key at the same time but the fetching state and data was not shared. It makes problems if someone tries to make a higher-order composable that **returns a new instance of asyncData with the same key**.
This PR resolves it using a shared `_asyncData` map in nuxtApp interface also adding tests from #5738 by @OhB00.
**Remarks:**
We probably can iterate over this. Normally each useAsyncData should be **unique** based on its key and a factory pattern shall be introduced for `createAsyncData` and `createFetch` (discussion: #7026)
I will follow up with more PRs to have proper changelog.
> fix(nuxt): use shared state for asyncData

- packages/nuxt/src/app/composables/asyncData.ts
Extracted from #5738 by @OhB00
Move the client-only logic to `process.client` scope so that we are sure bundler can tree-shake it for server also increase code readability since is only used in if condition block.
Co-authored-by: Ohb00 <43827372+OhB00@users.noreply.github.com>
> perf(nuxt): tree-shake asyncData client logic from server

- packages/vite/src/client.ts
resolves  #7035
This sanitizes asset filenames as well as chunks, and also fixes an issue where we were mutating the shared config (and therefore affecting server) but not the client.
> fix(vite): sanitize client asset chunk names

- packages/nuxt/src/components/module.ts
- test/basic.test.ts
resolves  #6876
This removes global components from being prefetched by default. (They will still be preloaded if they are used on the page being rendered on the server.)
This isn't a breaking change as such, but users who are heavily using dynamic/global components, such as with a catchall page rendering CMS content or page building libraries, will likely want to use the [`prefetchComponents`](https://v3.nuxtjs.org/api/composables/prefetch-components) and [`preloadComponents`](https://v3.nuxtjs.org/api/composables/preload-components#preloadcomponents) utilities. (At the moment they do the same thing, but should semantically match the difference between link preload/prefetch.)
> perf(nuxt): don't prefetch all global components

- packages/schema/src/types/global/vite.ts
1. `globEager` is [deprecated](https://vitejs.dev/guide/migration.html#general-changes)
2. add some types according to [latest types](https://github.com/vitejs/vite/blob/main/packages/vite/types/importGlob.d.ts)
3. `glob` will always exists in `import.meta`, I think there is no need to set it as an optional field here?
If we try to use optional chain in the code, it will break this feature in Vite 3:
```ts
// Works in Vite 2 but not in Vite 3
const result = import.meta.glob?.('assets/images/svg/**/*.svg')
console.log(result) // `undefined` in Vite 3
// Works fine
const result = import.meta.glob('assets/images/svg/**/*.svg')
console.log(result) // { '.../...svg': () => import(...) }
```
> fix(schema): sync types of vite v3.x

- scripts/bump-edge.ts
Currently versions of edge channel are `{latestRC}-{hash}`. While they are actually for next RC. 
Remarks:
- We should change `prerelease` to semver type based on changelog after 3.0.0 
- As a related issue we should adjust version when internally developing framework. Needs few code bytes to kit to make happen (we were doing similar thing in Nuxt2)
> chore: bump rc version for edge versions

- packages/kit/src/compatibility.ts
Resolves #6699
This PR allows modules to use constraints like `^3.0.0-rc.9`. Previously prerelease section were being ignored.
**Breaking change:** (module authors)
If your module was previously using `defineNuxtModule` from `@nuxt/kit` and constraint as `^3.0.0` it needs to be updated to `^3.0.0-rc.8` in order to work again.
> fix(kit)!: handle prerelease constraint

- packages/nuxt/src/app/components/nuxt-error-page.vue
https://github.com/nuxt/framework/pull/7114
We were deliberately preventing a reactive update here.
> fix(nuxt): prevent error page rendering a null error

- docs/content/3.api/4.advanced/1.hooks.md
- packages/nuxt/src/app/nuxt.ts
https://github.com/nuxt/framework/discussions/7125
This removes a hook that was only used for Nuxt Bridge integration: https://github.com/nuxt/framework/pull/664.
It might be useful to reconsider adding back some kind of hook implementation in future but for now it's unused and can be removed.
> refactor(nuxt): remove unused `meta:register` hook

- packages/nuxi/src/commands/build.ts
- packages/nuxi/src/commands/dev.ts
- packages/nuxi/src/commands/info.ts
- packages/nuxi/src/utils/banner.ts
Resolves #6935
With this PR, we show (installed) versions of Nuxt (it can be different than Nuxi!) and Nitro.
Remarks: I used `_require` instead of getPkg or inference from `package.json` to ensure we show actually installed versions and use native resolver. This also reduces CLI entry dependencies. Later we should refactor this.
> feat(nuxi): display nuxt and nitro versions for dev and build commands

- packages/nuxi/src/utils/banner.ts
- packages/nuxi/src/utils/cjs.ts
Fixes issue with #7118 found in edge. `createRequire` accepts a file name instead of dirname and it was breaking behavior. Reusing existing cjs utils as fix.
After
> fix(nuxi): fix version search path

- docs/content/3.api/1.composables/use-fetch.md
[#5895](https://github.com/nuxt/framework/issues/5895#issuecomment-1184457578)
[#4955](https://github.com/nuxt/framework/pull/4955)
Documentation about how the default key is generated was not updated.
> docs: add note about `useFetch` auto generated key

- docs/content/3.api/1.composables/use-head.md
Enhance API documentation for `useHead` composable
> docs(api): enhance `useHead` composable

- packages/nuxt/src/app/composables/router.ts
Follow up on https://github.com/nuxt/framework/pull/7188
This PR updates the default redirect code of the `navigateTo` (from `301 Moved Permanently` to `302 Found`).
> fix(nuxt): update default redirect code of `navigateTo` to `302 Found`

- docs/content/2.guide/3.directory-structure/8.middleware.md
- docs/content/3.api/1.composables/use-router.md
- docs/content/3.api/3.utils/navigate-to.md
- packages/nuxt/src/app/composables/router.ts
https://github.com/nuxt/framework/issues/6906
This PR documents the `external` option of `navigateTo`.
> docs: document `external` option of `navigateTo`

- packages/nuxt/src/head/runtime/components.ts
- test/basic.test.ts
- test/fixtures/basic/pages/head.vue
Currently, when using the `Meta` component, it's not possible to provide a value for `http-equiv`. This is because `http-equiv` gets turned to  `httpEquiv`, from Vue prop passing. 
`httpequiv` is the final DOM result and it's not honoured by browsers
This PR simply swaps out the key for the correct one, I beleive this will be a temporary fix if unjs is working on a dom handling package.
https://stackblitz.com/edit/nuxt-starter-jdegdy?file=app.vue
> fix(head): case `http-equiv` correctly

- packages/kit/src/compatibility.ts
- packages/nuxi/src/utils/nuxt.ts
[](https://github.com/nuxt/framework/issues/7192)
It closes https://github.com/nuxt/framework/issues/7192 with updated regExp, which match both `nuxt3`/`nuxt-edge` releases
> fix(kit, nuxi): semver regexp to support `nuxt-edge` current releases (bridge)

- docs/content/2.guide/3.directory-structure/4.components.md
Hi 👋 I couldn't find any documentation about the .client components even if there was some *.client.vue components in the examples . This PR adds a small documentation for *.client.vue components, it also warn that directly importing a component (with direct path) does not work.
> docs(guide): add .client and .server components documentation

- packages/schema/src/config/nitro.ts
It was not clear to me how server handlers should be specified until diving a bit deeper in the source code.
> docs: extend description of server handlers

- docs/content/3.api/1.composables/use-fetch.md
Added request settings and response data, error handling
> docs(api): add example for fetch interceptors

- packages/nuxt/src/pages/utils.ts
- packages/schema/src/types/hooks.ts
Add capability to setup alias in hook pages:extend or module like
I made sure we could keep `definedMeta` alias and **`pages:extend`** alias at the same time
Issue #7059
> feat(nuxt): allow extending routes with custom alias

- packages/vite/src/client.ts
resolves https://github.com/nuxt/framework/issues/7233, resolves https://github.com/nuxt/framework/issues/6626
This adds a vite base in dev mode which prevents collisions with pages (e.g. `~/pages/app.vue` and `~/app.vue`) and also respects `baseURL`.
> fix(vite): use baseURL + assetsDir as base in dev mode

- docs/content/3.api/1.composables/use-async-data.md
Update signature acording to https://github.com/nuxt/framework/blob/80a66dc5af74b9532f32f77bb463131bd9fb6058/packages/nuxt/src/app/composables/asyncData.ts#L20-L43
I noticed that the signature in the documentation was different from the actual one and made the changes.
In particular, documented that `data` now may be `null`, after https://github.com/nuxt/framework/commit/f350a70775016a8bde92670b4856d5d1edb1e7e0
> docs(api): fix `useAsyncData` signature

- docs/content/4.examples/1.app/app-config.md
- examples/app-config/app.config.ts
- examples/app-config/app.vue
- examples/app-config/nuxt.config.ts
- examples/app-config/package.json
- examples/app-config/tsconfig.json
Useful to showcase our last feature on app.config :)
ly.
> docs: add `app-config` example

- packages/nuxt/src/core/nitro.ts
- packages/nuxt/src/core/nuxt.ts
- packages/nuxt/src/core/runtime/nitro/renderer.ts
- packages/schema/src/config/experimental.ts
resolves https://github.com/nuxt/framework/issues/7156
This allows turning off all Nuxt-injected JS (preload/prefetch `<link>` and `<script>`). It does not affect user code, which can still inject scripts. It does remove all scripts from buildDir, though perhaps this could be reconsidered in future? (wdyt @pi0?)
> **Warning**
> This will only be advisable for the very small minority of sites that would not benefit from client-side JS.
> feat(nuxt): support experimental flag to render no client-side js

- packages/vite/src/utils/warmup.ts
https://github.com/nuxt/framework/pull/6649
This adds a missing condition to `getModuleByUrl`
> fix(vite): pass ssr condition to `getModuleByUrl`

- packages/nuxt/src/app/components/client-only.mjs
- packages/nuxt/src/components/loader.ts
fix https://github.com/nuxt/framework/issues/7226
Previously `createClientOnly` was called inside the render function, which unexpectedly created new components on each render.
Before:
After:
> fix(nuxt): import and wrap client-only components once

- packages/vite/src/server.ts
- packages/vite/src/vite-node.ts
We are [already resolving the entrypoint for the app](https://github.com/nuxt/framework/blob/de6252099052b5eae6af7cb187e9549dba79a412/packages/vite/src/server.ts#L15-L17), so I think we can remove this extra code. I see that the `.mjs` extension by default in vite node creation was added to fix a bug, so instead I'm moving that logic to the vite server creation so we can share that path (for example) in warming up the app. I'm not sure this makes a difference, but thought it would be better to keep logic central.
> refactor(vite): reuse resolved server entry from context

- docs/content/3.api/5.commands/dev.md
- packages/nuxi/src/commands/dev.ts
resolves https://github.com/nuxt/framework/issues/7218
This PR passes the value of `https` through to vite-node (which was reading it). Note that if users are using a _self-signed_ certificate then they will also need to set `NODE_TLS_REJECT_UNAUTHORIZED=0`, for example:
```bash
NODE_TLS_REJECT_UNAUTHORIZED=0 yarn dev --https --ssl-cert localhost.pem --ssl-key localhost-key.pem
```
> fix(nuxi): pass value of `https` through to vite-node

- docs/content/5.community/3.contribution.md
None
Fixes typo in link URL that goes from https://v3.nuxtjs.org/community/contribution to https://v3.nuxtjs.org/guide/going-further/modules/#joining-nuxt-community.
> docs: fix typo in url

- packages/kit/src/imports.ts
- packages/nuxt/src/core/nuxt.ts
Context: https://github.com/nuxt/framework/pull/7158
This PR adds support for auto-imports sources. With deprecation of `autoImports:sources` hook there is not an easy tool for module authors to add sources without manually passing `allowDeprecated` themselves.
> feat(kit): add `addImportsSources` utility

- packages/nuxt/src/core/runtime/nitro/renderer.ts
- test/basic.test.ts
- test/fixtures/basic/pages/error.vue
resolves  #6918
Currently if a renderering error occurs after another error the rendering error will take precedence. (e.g. if an error is thrown in `<script setup>`). This PR simply ensures that the original error is the one we handle.
I've moved the test case to the end of the file as https://github.com/vuejs/core/issues/6110 means that the dev test fixture is broken after a rendering error. We either need to work around it in a separate PR or 🤞 that it is resolved upstream. (But either way, the issue already exists apart from this PR.)
> fix(nuxt): don't override payload error if it is present

- packages/nuxt/src/app/components/client-only.mjs
PR https://github.com/nuxt/framework/pull/7243 
Hi ! this PR is based on PR #7243 and @antfu suggestion to use a WeakMap. This avoid to recreate another client only component when a `.client` component is called multiple times.
> perf(nuxt): cache `createClientOnly` wrapper using weakmap

- packages/nuxt/src/app/composables/cookie.ts
resolves #5183
We were trying to set headers after redirect when cookies were used. Alternatively we could check writableEnded but I think it's better to have warning surface in this kind of way.
> fix(nuxt): don't try to set cookie after redirect

- packages/schema/build.config.ts
- packages/schema/src/types/hooks.ts
- packages/webpack/build.config.ts
- packages/webpack/src/configs/client.ts
- packages/webpack/src/webpack.ts
resolves #7236
Currently the first `next()` call from webpack devMiddleware short-circuits second next call from hotMiddleware meaning we currently get a 404 for webpack HMR endpoint.
I think it's a non-breaking change to update schema type for devMiddleware (as CompatibilityEvent should be backwards compatible).
> fix(webpack): promisify webpack dev/hot handlers using `h3.promisifyHandler`

- test/basic.test.ts
regression of https://github.com/nuxt/framework/pull/7312
> test: fix dynamic dev paths

- .github/ISSUE_TEMPLATE/bug-report.yml
- docs/content/1.getting-started/1.quick-start.md
- docs/content/5.community/2.reporting-bugs.md
Hello team!
In this PR, I updated the links for the starter CodeSandbox projects to the new version of CodeSandbox. This is a more smooth experience, and should also work faster and more consistently with the local environment.
These are the new links:
- Nuxt Starter: https://codesandbox.io/p/github/nuxt/starter/v3-codesandbox
- Nuxt Bridge: https://codesandbox.io/p/github/nuxt/starter/v2-bridge-codesandbox
- Vue 3 SSR starter: https://codesandbox.io/p/github/nuxt-contrib/vue3-ssr-starter/main
> chore: update CodeSandbox links

- packages/nuxt/src/components/module.ts
- packages/nuxt/src/core/nitro.ts
- packages/nuxt/src/core/nuxt.ts
- packages/nuxt/src/imports/module.ts
- packages/nuxt/src/pages/module.ts
- packages/schema/src/config/build.ts
- packages/schema/src/types/config.ts
- packages/vite/src/client.ts
- packages/vite/src/server.ts
- packages/vite/src/vite.ts
- packages/webpack/src/configs/client.ts
- packages/webpack/src/configs/server.ts
- packages/webpack/src/webpack.ts
resolves #7294
This PR bundles a couple of changes to sourcemap handling:
1. fixes a bug where nitro sourcemaps were not respecting `sourcemap` config (a typo)
2. generates client-side sourcemaps for webpack/vite in production if sourcemap is set to true (or allows either falling back to previous behaviour with new option 'server' or generating _only_ client-side sourcemaps with 'client')
3. defaults to previous behaviour (generates all sourcemaps in dev, and only server-side sourcemaps in production)
4. fixes (unrelated) issue with https://github.com/nuxt/framework/pull/5750 where client-only components were being tree-shaken out of client build as well 🙈
> feat(vite, webpack): allow client-side sourcemaps in production

- docs/content/3.api/3.utils/clear-nuxt-data.md
- packages/nuxt/src/app/composables/asyncData.ts
Continuation of  https://github.com/nuxt/framework/pull/5227
Uncovered use case: 
Remove cache for several unknown keys. Example: you have app with posts and filter for posts. Each query for posts saved in cache in uniq key, like `posts.list-{param1:1}`, `posts.list-{param2:2}`, `posts.list-{param1:1,param2:3}` (nuxt-trpc works llike that). In this case you may want clear data for all keys `posts.list-*`. 
May be `clearNuxtData` should also accept function to filter keys?
```ts
clearNuxtData(key => key.startsWith('posts.list'))
```
Or provide another method to get all keys in cache and filter it manually:
```ts
clearNuxtData(
getNuxtDataKeys().filter(key => key.startsWith('posts.list'))
)
```
> feat(nuxt): filter support for `clearNuxtData`

- packages/schema/src/types/config.ts
https://github.com/nuxt/framework/pull/7317
Fixes a regression where `vite.server` was marked as both required and `never`.
> fix(schema): mark vite server as optional

- packages/nuxt/src/app/composables/router.ts
- test/basic.test.ts
- test/fixtures/basic/middleware/abort.global.ts
resolves https://github.com/nuxt/framework/issues/5041
This is the last piece in the linked issue. It means we can respect a nuxt error thrown in middleware, namely set our own status code/message.
> fix(nuxt): allow `abortMiddleware` to receive a nuxt error or error options

- packages/vite/src/plugins/composable-keys.ts
- test/fixtures/basic/pages/keyed-composables.vue
resolves #7330
With webpack, we have some code in a string in the style block, e.g.:
```
const code = ["\\nconst a ..."]
```
This wrongly gets parsed by the composable keys, and `\\n` breaks the parser.
But we shouldn't be parsing code from a style block for automatic useFetch/useState keys, anyway.
> fix(webpack): don't parse styles for composable keys

- packages/schema/src/config/_common.ts
resolves #7357
This is a hotfix for an upstream issue in untyped which we need to look at (cc: @pi0). `get('ssr')` was not returning the value in the user's config, but the default value in the config.
> fix(schema): resolve `ssr`

- packages/kit/src/loader/config.ts
Resolves #7355
We filter extend layers without config entry but in case that user also has no `nuxt.config` file, they become empty and it breaks scanning.
> fix(kit): add default config layer without `nuxt.config` file

- docs/content/3.api/5.commands/prepare.md
discussion https://github.com/nuxt/framework/discussions/7338
hi ! This PR adds `nuxi prepare` documentation. I use it before running tests during CI. @Lyokolux use it for Histoire
> docs(api): add `nuxi prepare` command

- packages/vite/src/runtime/vite-node.mjs
resolves https://github.com/nuxt/framework/issues/7345
I may be misunderstanding the implementation here, but it seems that we were not updating the render function when it was invalidated. This PR ensures that if the entry is invalidated, we fetch it fresh from the runner.
> fix(vite): update render if it is invalidated

- docs/content/2.guide/2.features/4.head-management.md
- docs/content/4.examples/3.composables/use-head.md
- docs/content/migration/4.meta.md
#4104
Hi ! This PR adds some changes to the documentation:
- it adds `noscript` mentions
- fix some links : 
- in composable/use-head, change the read more from use-fetch to use-head
- in composable/use-head, change the Meta Tag link (broken) from /api/composables/use-meta to /migration/meta
> docs(head): enhance usehead and fix broken links

- packages/vite/src/client.ts
- packages/vite/src/runtime/vite-node.mjs
- packages/vite/src/server.ts
- packages/vite/src/utils/warmup.ts
- packages/vite/src/vite.ts
These are some small improvements to improve warmup consistency.
wdyt @antfu?
> fix(vite): warmup improvements

- packages/nuxi/src/utils/cjs.ts
https://github.com/nuxt/bridge/issues/515. https://github.com/nuxt/bridge/pull/514. ctx: https://github.com/nuxt/framework/pull/6943
`global.__NUXT_PREPATHS__` is an array (if defined) and the `resolveModule` was choking on this (sometimes):
https://github.com/nuxt/framework/blob/8b24992f6d905c6d1188830087f8d59a14b3f544/packages/nuxi/src/utils/cjs.ts#L20-L22
`Array.concat()` handles this for us.
> fix(nuxi): don't include an array of paths within an array

- packages/vite/src/server.ts
resolves #7371
We were omitting building client-manifest due to a regression from https://github.com/nuxt/framework/pull/7264.
> fix(vite): write dev manifest before spa build

- packages/nuxt/src/app/components/nuxt-error-page.vue
- packages/nuxt/src/app/components/nuxt-root.vue
- packages/nuxt/src/components/loader.ts
- packages/nuxt/src/core/templates.ts
resolves #7325, resolves https://github.com/nuxt/framework/issues/5996
When we were producing a single inlined file, we were not de-defaulting the exports.
So, for example, a default layout ended up resolving to `{ default: /* layout */ }`, triggering a warning from vue that it had no render property. (The actual render property could have been accessed on `layout.default.render`.)
This completely broke all inlined targets (cloudflare, vercel-edge, netlify-edge) if you were using layouts or lazy components.
Adding interop defaults resolves the issue. I've gone ahead and done the same for lazy components and custom error components which were not mentioned in the original report, but had the same buggy behaviour in my testing.
Middleware doesn't need it as it is de-defaulted at point of …
> fix(nuxt): de-default layout/component imports

- packages/nuxt/src/core/runtime/nitro/renderer.ts
- packages/vite/src/plugins/ssr-styles.ts
Previously if we were rendering a page without any styles in its `.vue` file, we would also not render global styles, because they are only concatenated to styles that already exist.
Alternatively we could amend [this line](https://github.com/nuxt/framework/blob/1b1b4eefad07a34aa626301d85fd811072729389/packages/vite/src/plugins/ssr-styles.ts#L28-L30) so that we explicitly add all used components, even if they have no styles, but this would make the file much larger.
> fix(nuxt): always inline entry styles

- packages/nuxt/src/core/nuxt.ts
- packages/nuxt/src/core/plugins/import-protection.ts
resolves #2886
We can avoid triggering import protection from a top-level `this.resolve` call (i.e. within another vite plugin), as there may be valid use cases for this, like tailwind resolving the nuxt.config file.
**Relevant vite section**:
https://github.com/vitejs/vite/blob/757a92f1c7c4fa961ed963edd245df77382dfde6/packages/vite/src/node/server/pluginContainer.ts#L562-L566
> fix(nuxt): do not apply import protection to top-level resolution

- packages/nuxt/src/app/composables/fetch.ts
- test/fixtures/basic/types.ts
resolves  #7429
In the case of `useFetch`, errors will almost certainly be of the `FetchError` type so we can provide a bit more type hinting to the user to avoid the requirement of casting...
> fix(nuxt): use more specific `FetchError` for `useFetch` errors

- packages/vite/src/client.ts
- packages/vite/src/vite.ts
resolves #7430
It seems we need to share asset filename generator between server + client so filenames match up between client + server builds.
> fix(vite): use same asset filenames between server and client

- docs/content/3.api/1.composables/use-runtime-config.md
Added API documentation for `useRuntimeConfig` composable
> docs(api): add `useRuntimeConfig` page

- packages/nuxt/src/core/nuxt.ts
- test/fixtures/basic/extends/bar/index.d.ts
- test/fixtures/basic/types.ts
resolves  #7373
This allows extends layers to automatically add their augments to the end user's app by placing an `index.d.ts` file in their root directory (I think this is correct, vs. srcDir)...
> feat(nuxt): allow exposing type augmentations from extends layers

- packages/vite/src/plugins/ssr-styles.ts
- test/fixtures/basic/nuxt.config.ts
resolves #7372
Virtual CSS files that want Nuxt inline styles need to respond to the resolved ID with the correct query flags (`?inline&used`). I've updated three key virtual CSS modules (see linked issue). But we shouldn't fail builds if user is using some other virtual CSS module; this PR simply makes sure we skip those virtual modules. Any CSS they inject will not be inlined.)
We could also display a warning message so users at least know this is happening and know where to raise an issue. wdyt @pi0?
> fix(vite): don't fail builds for virtual modules that don't support inlining

- docs/package.json
- package.json
- packages/kit/package.json
- packages/kit/src/loader/config.ts
- packages/kit/src/module/define.ts
- packages/nuxt/package.json
- packages/nuxt/src/core/templates.ts
- packages/schema/package.json
- packages/schema/src/config/_adhoc.ts
- packages/schema/src/config/_app.ts
- packages/schema/src/config/_common.ts
- packages/schema/src/config/build.ts
- packages/schema/src/config/experimental.ts
- packages/schema/src/config/generate.ts
- packages/schema/src/config/postcss.ts
- packages/schema/src/config/render.ts
- packages/schema/src/config/router.ts
- packages/schema/src/config/vite.ts
- packages/schema/src/config/webpack.ts
- yarn.lock
#7439 > https://github.com/unjs/untyped/pull/50
This PR upgraded to untyped 0.5.x using async `$resolve` and `get` methods. This change guarantees better forward compatibility with cost of little bit verbose code inside schema.
> refactor(schema): upgrade to untyped 0.5

- packages/nuxt/src/core/nuxt.ts
- packages/nuxt/src/core/templates.ts
- packages/schema/src/config/build.ts
- packages/schema/src/types/config.ts
This started out as a simple small perf improvement but ended up fixing a couple of bugs as well. The changes are:
* only inject the server preload plugin when webpack builder is used (it adds a needless overhead with vite)
* update NuxtOptions schema so it correctly shows resolved value of `builder`
* update resolver for builder so it respects a custom builder value
> perf(nuxt): only inject preload helper when webpack is used

- .github/workflows/docs-e2e.yml
- docs/content/migration/6.pages-and-layouts.md
- package.json
- scripts/crawl.mjs
- yarn.lock
This adds an e2e test for the docs deployment to ensure we have no broken links when refactoring.
> ci: crawl docs site for new deployments to track broken links

- packages/nuxt/src/core/nuxt.ts
When `noScripts` is enabled, we would end up deleting the entry file within node_modules (as it is now fully resolved) 🤦.
> fix(nuxt): only delete assets when building

- packages/nuxt/src/app/components/nuxt-link.ts
- packages/nuxt/src/app/composables/asyncData.ts
- packages/nuxt/src/app/composables/cookie.ts
- packages/nuxt/src/app/composables/error.ts
- packages/nuxt/src/app/composables/hydrate.ts
- packages/nuxt/src/app/composables/payload.ts
- packages/nuxt/src/app/composables/preload.ts
- packages/nuxt/src/app/composables/router.ts
- packages/nuxt/src/app/composables/ssr.ts
- packages/nuxt/src/app/composables/state.ts
- packages/nuxt/test/nuxt-link.test.ts
I came a significant performance hit (in Nuxt Bridge) from importing from `#app` alias with vite, because `#app` re-exports lots of files which themselves import from `#app`.
We can work around that by using relative imports, which I think is also slightly nicer. Even though I haven't measured a slow-down in this repo, it can't hurt and should be a more intelligible approach for vite. I've left a number of imports from `#app` untouched within plugins/components as these are not re-exported from `#app`. (It might also be possible to do the same with `head`, but it's still in a quasi-independent state and this can wait for improvements to its implementation.
> refactor(nuxt): use relative imports into composables

- packages/nuxt/src/pages/runtime/page.ts
resolves https://github.com/nuxt/framework/issues/6161
This allows the user to pass transition & keepalive config directly to `<NuxtPage>` rather than configuring it through default values or route metadata. This should mean it is easier to configure dynamic keepalive/transition configuration. It may also solve the underlying use case for https://github.com/nuxt/framework/issues/7428.
> feat(nuxt): allow passing transition & keepalive props to <NuxtPage>

- packages/kit/src/loader/config.ts
- packages/nuxt/config.cjs
- packages/nuxt/config.d.ts
- packages/nuxt/config.mjs
- packages/nuxt/package.json
- packages/nuxt/src/core/nuxt.ts
- playground/nuxt.config.ts
resolves #7267
This PR introduces new `nuxt/config` subpath export with CJS+MJS build to avoid jiti extra transformations.
~~Also using jiti aliases, `nuxt` is aliases to `nuxt/config` within `nuxt.config` file. This way we transparently introduce this enhancement to all nuxt 3 users.~~ `defineNuxtConfig` from `nuxt` is deprecated. Pending docs/examples update to after release and try. Alias seemed little bit hacky to do and causing potential breaking changes.
> perf(nuxt): import `defineNuxtConfig` from `nuxt/config`

- packages/schema/src/config/experimental.ts
> perf: enable `treeshakeClientOnly` flag by default

- packages/kit/src/loader/config.ts
- packages/nuxt/src/core/nuxt.ts
- packages/nuxt/src/index.ts
- packages/nuxt/types.d.ts
- playground/nuxt.config.ts
#7485
A quick implementation to make `defineNuxtConfig` available when loading configuration. This way we can remove `import { defineNuxtConfig } from 'nuxt/config' at all!`. If feature proven to be stable, will probably move it to c12.
Type support: It is possible with a global reference defined in `'nuxt'` types. Since we run `nuxi prepare` after installing dependencies, it should be immediately available.
> feat(nuxt, kit): auto import `defineNuxtConfig`

- packages/nuxt/src/app/plugins/payload.client.ts
- packages/nuxt/src/core/nuxt.ts
#6455
Payload extraction is currently not used for dev mode (but planned https://github.com/nuxt/framework/issues/6411). While plugin auto disables itself, there is no need for it to be added.
> fix(nuxt): add `payload.client` plugin only for production build

- packages/nuxt/package.json
- packages/nuxt/src/core/nitro.ts
- packages/nuxt/src/core/runtime/nitro/renderer.ts
- yarn.lock
Resolves #5003
This PR generates fallback SPA page for `nuxt generate` (ssr: true) in order to make fallback supported.
- `nuxt: generate` + `ssr: true` (default): `200.html` is generated (new) without being server-side rendered.
- `nuxt: generate` + `ssr: false`: `200.html`, `404.html` and `index.html` (new) are generated
Nitro prerenderer detects this _explicit_ routes and disable SSR for them. To avoid confusing with actually prerendering top level `/`, `index.html` is only pre-rendered for `ssr: false`. Also `404.html` is only generated for `ssr: false`. It can be added for `ssr: true` using `nitro.prerender.routes: ['/404.html']` if needed.
> feat(nuxt): generate spa fallbacks for `nuxt generate`

- packages/schema/src/config/_common.ts
Hello,
`srcDir` also affects `server` directory, so using `client/` as an example can be misleading
> docs(schema): change srcDir example to `src/`

- packages/vite/src/vite.ts
https://github.com/nuxt/framework/issues/7510
Disable vite-node cache warmup until investigating #https://github.com/nuxt/framework/issues/7510 and benchmarking. Currently it has _negative_ performance effect.
> fix(vite): disable server warmup with `vite-node`

- packages/nuxt/src/core/runtime/nitro/renderer.ts
https://github.com/nuxt/framework/discussions/7513#discussioncomment-3649155
SPA pages have no actual payload data (other than initial state). 
This also fixes issue for special spa (`index.html`, `200.html` and `404.html`) routes.
> fix(nuxt): disable payload extraction for spa generated pages

- packages/nuxt/src/app/components/nuxt-link.ts
resolves  #7520
We shouldn't pass prefetched class to routerlink if it's a custom link. (Later, might be worth thinking about how to pass prefetched class to slot.)
> fix(nuxt): do not pass prefetched class to custom link

- docs/content/1.getting-started/5.routing.md
Following RC 10, explain the prefetch feature of `<NuxtLink>`
> docs: add note about link prefetching

- packages/schema/src/config/build.ts
This should only affect typings for Bridge, but we hadn't updated the `get('sourcemap')` call.
> fix(schema): update resolver for `cssSourceMap` to new `sourcemap`

- docs/content/2.guide/4.going-further/3.modules.md
- docs/content/3.api/4.advanced/2.kit.md
Added example of using `@nuxt/kit` for adding components, and testing out the module locally
Also fixed outdated mention of auto-import utils
> docs: add `addComponent` and testing to modules and update `addImports`

- packages/schema/src/types/config.ts
https://github.com/nuxt/framework/pull/7317#issuecomment-1247923503
So options like `hmr` can be configured seamlessly.
> fix(schema): only disallow vite server port and host

- packages/nuxi/src/commands/build.ts
- packages/nuxi/src/commands/generate.ts
resolves #7511
Using new useNitro utility (https://github.com/nuxt/framework/pull/7557) we can access the resolved publicDir for nitro and print the relative path to it, rather than hard coding `.output/public`.
> fix(nuxi): print resolved public directory after generate

- packages/nuxt/src/core/nitro.ts
- packages/nuxt/src/core/nuxt.ts
- packages/nuxt/src/core/runtime/nitro/renderer.ts
- packages/schema/src/config/experimental.ts
resolves #7587
This PR allows disabling payload extraction with `nuxi generate` introduced in RC.10 (#6455) using `experimental.payloadExtraction: false`
```js
experimental: {
payloadExtraction: false
}
})
```
Remarks:
- Even by disabling the (static) payload extraction, `/_payload.js` endpoint is still available for renderer. It is a separate feature
- I've confirmed tree-shaking keeps working with refactors
> feat: allow disabling payload extraction

- packages/nuxt/src/app/plugins/payload.client.ts
https://github.com/nuxt/framework/issues/7562
This is not an alternative to https://github.com/nuxt/framework/pull/7567, but a separate fix. It ensures the data is only applied immediately before the route resolves (so after all middleware have been processed - and not when the data is prefetched)....
Where same asyncData keys are used for different routes (e.g. in a `[slug].vue`), this will resolve the issue, with one exception: if there are still additional async setups required and the keys collide.
In some ways this mitigates https://github.com/nuxt/framework/issues/7562 because data isn't overwritten when it is prefetched, but only when the route is changed.
---
**Note**: although it hotfixes content + prerender, we still would want to change content implementation as suspense …
> fix(nuxt): load payload after middleware and once final route is resolved

- packages/nuxt/src/app/plugins/payload.client.ts
- packages/nuxt/src/core/runtime/nitro/renderer.ts
- test/basic.test.ts
Resolves #7562
#6455 adds `payload.state` (set by `useState`) to the extracted payload. This will cause hydration and unwanted behavior on navigation by orriding already initialized state. 
This PR, makes behavior closer to Nuxt 2 by keeping state to the initial state inlined in the pages. Only payload data is now extracted.
Alternatives: We could instead keep extracting state and only try to set keys that are not assigned yet but it seems wrong performance wise if state is _initial state_ it should be set once and if is same across pages, loading it adds to network overhead. We can revise it later with some better approach to only record state change diffs and include that in `_payload.js` somehow.
> fix(nuxt): keep `state` in initial state instead of extracting it

- docs/content/2.guide/2.directory-structure/1.pages.md
I have fixed typo on the `directory-structure/pages` page, capitalized StabilityEdge texts.
> docs: fix typo on directory-structure/pages

- packages/nuxi/src/commands/build.ts
If used with an older version of kit without the feature it will error out on:
```
ERROR  useNitro is not a function
```
> fix(nuxi): backward compatibility for kit <= RC.10 without `useNitro`

- packages/vite/src/vite-node.ts
resolves https://github.com/nuxt/framework/issues/7534
There are vast different possibilities from errors rollup and vite throw. Since vite-node tries to make a network request to fetch the modules, we were missing some information (such as module id). This PR _tries_ to normalize it beforehand.
> fix(vite): normalize vite-node error data

- packages/vite/src/vite-node.ts
resolves #7609
We are overriding `shouldExternalize` (PR: #6153) of vite-node, and use mlly resolver to directly resolve paths. Issue with #7609 happens because directly setting URL to the directory of `rootDir`, causes resolving from parent `node_modules` and finally different resolved `vue` version. (Correct way is setting `rootDir + '/_node_modules'` or `rootDir + /index.mjs`)
This PR resolves issue by respecting `modulesDir` for resolving `vue` and other dependencies. In the future we might come of with better implementation to actually reuse same vite resolution. I didn't use `return id` on external branch (while it works!) until getting confirmation from @antfu. Vite-node's default external handler however does this. [src](https://github.com/vitest-dev/vitest/blob/95da4d66933db46da36 …
> fix(vite): respect `ctx.nuxt.options.modulesDir` for resolving externals with `vite-node`

- packages/nuxt/src/app/composables/router.ts
- test/basic.test.ts
- test/fixtures/basic/pages/navigate-to-redirect.vue
resolve https://github.com/nuxt/framework/issues/7501
Hi :wave: , this PR is a small fix adding process.client to early redirect on client side for `navigateTo()`. There's also a small test to ensure the http status code is correct.
However there's an issue using `navigateTo` in async middlewares which throws a `nuxt instance not available` error. I believe this has been already reported in some issues.
> fix(nuxt): add missing `process.client` for early redirect in navigateTo

- packages/vite/src/runtime/vite-node.mjs
Ref #7534
This PR tries to include (last) importer in stack traces of vite-node formatted errors.
> fix(vite): include importer in `vite-node` error stack

- packages/vite/src/plugins/composable-keys.ts
resolves #7578
With webpack, we were processing code _twice_ and therefore injecting several auto-generated keys, one after the other. This PR prevents double-insertion of keys, and also prevents insertion when there is an obvious string or template literal key provided already.
It also excludes nuxt sourcefiles (e.g. `#app`) from having keys inserted into them.
> fix(vite, webpack): avoid generating keys where a key is already provided

- packages/nuxt/src/components/tree-shake.ts
- test/basic.test.ts
- test/fixtures/basic/pages/client-only-components.vue
resolves https://github.com/nuxt/framework/issues/7517
This is an alternative approach to https://github.com/nuxt/framework/pull/7527, using pure regexp to handle fallback/placeholder slots.
It also fixes a bug where we matched _partial_ component names.
> fix(nuxt): don't treeshake client-only fallback templates

- docs/content/1.getting-started/6.data-fetching.md
- docs/content/3.api/3.utils/define-nuxt-component.md
- docs/utils/createTitle.js
Added API documentation for `defineNuxtComponent` utils
> docs(api): add `defineNuxtComponent` utils

- docs/content/1.getting-started/9.testing.md
- docs/content/2.guide/4.going-further/3.modules.md
#7640
Move the Modules Testing section to Module authors guide
> docs(testing): move modules testing section to module authors guide

- packages/nuxt/src/app/components/nuxt-link.ts
resolves #7524
It's possible that NuxtLink doesn't render an HTML element; we can skip observing it in this case and leave the user to implement prefetching on their own.
> fix(nuxt): only observe tag elements for `<NuxtLink>` prefetching

- docs/content/1.getting-started/3.views.md
~~The `layout/default.vue` file will be used by default.~~
The `layouts/default.vue` file will be used by default.
> docs(getting-started): fix typo in views

- packages/nuxt/src/app/composables/index.ts
- packages/nuxt/src/imports/presets.ts
- packages/nuxt/test/auto-imports.test.ts
resolves https://github.com/nuxt/framework/issues/7705
This PR exports clearNuxtData. The test suite wasn't broken, but I added a line to prevent swallowing an error if it ever were to be.
> fix(nuxt): export and auto-import `clearNuxtData`

- packages/test-utils/src/run.ts
resolves https://github.com/nuxt/framework/issues/3252, resolves https://github.com/nuxt/framework/issues/7709
Vitest v0.20 added an additional parameter, which we weren't respecting with test-utils. This PR also adds nuxt/test-utils to `deps.inline` which is required to avoid `Vitest was initialized with native Node instead of Vite Node` error.
We can drop the workaround if we want to have a hard dependency on vitest 0.20+
> fix(test-utils): support vitest v0.20.x

- docs/content/2.guide/2.directory-structure/1.server.md
This should return an error 405, not 404.
> docs(directory-structure): fix typo in server

- docs/content/3.api/3.utils/navigate-to.md
resolves #7732 
1. Changes the `navigateTo` example to use `await` instead of return, as `return` will throw a compilation error.
2. Formats the block of code to be consistent with other blocks.
> docs(navigate-to): use await instead of return

- docs/content/1.getting-started/8.error-handling.md
Resolves #7743
Fixes type definitions of `useError()` in documentation. 
That differed because of the following change.
https://github.com/nuxt/framework/pull/6389/files
> docs(error-handling): fix useError() type definition

- packages/nuxi/src/commands/info.ts
resolves #7727
With recent change to not require `defineNuxtConfig` to be registered, we neglected to update `nuxi info` - this PR does the same trick to make loading nuxt.config possible in this case.
> fix(nuxi): stub `defineNuxtConfig` for `nuxi info`

- packages/nuxt/src/pages/runtime/composables.ts
- packages/nuxt/src/pages/utils.ts
- packages/schema/src/types/hooks.ts
- test/basic.test.ts
- test/fixtures/basic/pages/index.vue
- test/fixtures/basic/pages/redirect.vue
resolves #5222
This PR:
* supports redirect (as well as alias) in page metadata
* adds types for redirect within `extend:pages`
* updates types for redirect + alias in page metadata
* adds some tests for the behaviour
> feat(nuxt): support `redirect` within page metadata

- packages/nuxt/src/app/components/layout.ts
reported by @ckald in https://github.com/nuxt/framework/issues/7292#issuecomment-1254280881
In the case of a non-existent default layout (such as when user did not have a custom `app.vue` but had `~/pages`) we were wrongly warning about DOM nodes, despite no transition being rendered. This PR ignores this case.
> fix(nuxt): do not warn for non-existent default layout

- packages/nuxt/src/app/composables/fetch.ts
resolves  #7715
We were not passing `immediate` from `useFetch` -> `useAsyncData`.
> fix(nuxt): respect immediate option in `useFetch`

- packages/nuxt/src/app/components/layout.ts
replace isref to unref of layout.ts
> refactor(nuxt): use `unref` in `layout.ts`

- packages/nuxt/src/app/composables/fetch.ts
change the isref of fetch.ts to unref
> refactor(nuxt): use `unref` in  `fetch.ts`

- packages/nuxt/src/core/runtime/nitro/renderer.ts
resolves https://github.com/nuxt/framework/issues/7806
This respects the baseURL when rendering payload URL in HTML.
> fix(nuxt): respect `baseURL` when rendering payload path

- docs/content/2.guide/4.going-further/2.hooks.md
- docs/content/3.api/4.advanced/1.hooks.md
resolves https://github.com/nuxt/framework/issues/6571
📖 Hi this PR document nitro render hooks 📖
> docs: document nitro hooks

- docs/content/5.community/5.roadmap.md
There is a wrong url to the Auth repo in the "Core Modules" section.
> docs(roadmap): remove not working link from `nuxt/auth`

- docs/content/bridge/1.overview.md
added a section about the public runtime config change in Nuxt 3
Resolves #7667 
Added section to bridge migration guide about public runtime configs in Nuxt 3
> docs: updated nuxt bridge migration guide

- packages/nuxt/src/core/nitro.ts
resolves #7737
We should only respect `experimental.noScripts` in built mode.
> fix(nuxt): don't disable scripts in dev mode with experimental `noScripts`

- docs/content/1.getting-started/4.assets.md
Sass import needs newline code.
The following error will be displayed if the line feed code is within
```
[sass] expected newline.                                                                                                   
╷
1 │ @use "@/assets/_colors.sass" as *abbr,
│                                       ^
╵
assets/styles/reset.sass 1:39  root stylesheet
```
> docs: add newline at end of sass import

- examples/routing/layouts/pages/dynamic.vue
This might be a better use of ` ? : `. Thought about it for a long time but couldn't resist submitting a PR. Apologize for reviewers' effort loss.
> docs(examples): optimize writing of ` : ? `

- packages/nuxt/src/core/templates.ts
In the case where a module is specified with a _relative_ path, it is not properly typed in `schema.d.ts`. For example:
```js
modules: [
'../src/module'
],
})
```
results in the following type:
```ts
declare module '@nuxt/schema' {
interface NuxtConfig {
["metaKey"]?: typeof import("../src/module").default extends NuxtModule<infer O> ? Partial<O> : Record<string, any>
}
}
```
But this relative import path either needs to be absolute or resolved relative to the generated schema.d.ts.
> fix(nuxt): handle schema types for relative module paths

- scripts/crawl.mjs
This fixes an issue with the crawler trying to crawl `<a>` links used purely for their anchor value.
> ci(crawl): ignore `<a>` links without hrefs

- packages/test-utils/src/context.ts
- packages/test-utils/src/setup/jest.ts
- packages/test-utils/src/setup/vitest.ts
resolves #5460
Previously we were not doing anything with `setupTimeout`, but hard coding the setup length.
> fix(test-utils): respect `setupTimeout`

- examples/composables/use-head/app.vue
- packages/nuxt/src/head/runtime/components.ts
Resolves #7853 
Resolves #7853 by aligning the script component's functionality to the noscript and style tags, which already allow using the default slot to specify the children property of useHead.
(not sure if this should be marked as a new feature or an enhancement)
(I also did not find any documentation that I should update, the documentation is written in a way where I already thought this is possible :P)
> fix(head): allow using the default slot for script content like noscript

- packages/nuxt/src/core/nitro.ts
resolves #7826
We should not be prerendering `index.html` if there is a dynamic server as runtime config (or nitro plugins) may change the response.
> fix(nuxt): don't prerender index.html with a server

- .markdownlint.yml
- docs/content/1.getting-started/1.introduction.md
- docs/content/5.community/3.contribution.md
This PR adds explanations of the different Nuxt core features to the Getting Started/Introduction section
> docs(introduction): add nuxt key features to the introduction

- packages/nuxt/src/core/app.ts
- packages/schema/src/config/_common.ts
resolves https://github.com/nuxt/framework/issues/7962
This allows configuring the plugins directory.
> feat(nuxt): allow configuring plugins directory

- docs/content/1.getting-started/3.configuration.md
- docs/public/_redirects
Resolves #8037 
Fixes dead link + add redirect
> fix(docs): link to api config reference

- docs/content/1.getting-started/3.views.md
Fixes indentation in code blocks on "Views" page
> docs: fix indentation in "Views" code blocks

- docs/content/1.getting-started/2.installation.md
- docs/content/1.getting-started/4.assets.md
- docs/content/1.getting-started/5.seo-meta.md
- docs/content/1.getting-started/6.data-fetching.md
- docs/content/2.guide/1.concepts/1.auto-imports.md
- docs/content/2.guide/1.concepts/3.rendering.md
- docs/content/2.guide/1.concepts/5.modules.md
- docs/content/2.guide/1.concepts/8.typescript.md
- docs/content/2.guide/2.directory-structure/1.pages.md
- docs/content/3.api/1.composables/use-fetch.md
- docs/content/3.api/1.composables/use-head.md
- docs/content/3.api/3.utils/add-route-middleware.md
- docs/content/3.api/3.utils/define-nuxt-route-middleware.md
- docs/content/3.api/3.utils/define-page-meta.md
- docs/content/3.api/3.utils/prefetch-components.md
- docs/content/3.api/5.commands/typecheck.md
- docs/content/4.examples/3.composables/use-head.md
- docs/content/5.community/4.framework-contribution.md
- docs/content/6.bridge/1.overview.md
- docs/content/6.bridge/2.bridge-composition-api.md
- docs/content/7.migration/1.overview.md
- docs/content/7.migration/4.meta.md
- docs/public/_redirects
- scripts/crawl.mjs
Various issues of pages being renamed.
For future reference, `scripts/crawl.mjs` is what I use to identify these issues.
> docs: fix more redirect issues

- packages/nuxt/src/app/components/layout.ts
- packages/nuxt/src/app/components/nuxt-root.vue
- packages/nuxt/src/app/entry.ts
- packages/nuxt/src/app/nuxt.ts
- packages/nuxt/src/core/templates.ts
- packages/nuxt/src/pages/runtime/page.ts
- test/basic.test.ts
- test/fixtures/basic/layouts/custom-async.vue
- test/fixtures/basic/layouts/custom2.vue
- test/fixtures/basic/nuxt.config.ts
- test/fixtures/basic/pages/async-parent.vue
- test/fixtures/basic/pages/async-parent/child.vue
- test/fixtures/basic/pages/fixed-keyed-child-parent.vue
- test/fixtures/basic/pages/fixed-keyed-child-parent/[foo].vue
- test/fixtures/basic/pages/internal-layout.vue
- test/fixtures/basic/pages/keyed-child-parent.vue
- test/fixtures/basic/pages/keyed-child-parent/[foo].vue
- test/fixtures/basic/pages/with-layout.vue
- test/fixtures/basic/pages/with-layout2.vue
- test/utils.ts
Fix #7337, fixes #6592, closes https://github.com/nuxt/framework/pull/7400
This PR is a remake of #7400
Besides of fix and workaround in #7400.
1. This PR use a different approach to handle hydrating, so change of page wrapper isn't required.
2. This PR ensure that layout and any page wrapper never change outside of the window that route navigation happens.
- so #6592 should never happen again
3. This PR adds proper test for linked issue
- so regression after this should be noticed
A remaining issue is temporary blank page when switching between layout and navigate at the same time.
But that isn't fixable without vuejs/core#6736.
So it isn't handled here.
> fix(nuxt): page hydration and double load

- docs/content/1.getting-started/6.data-fetching.md
Seems like the code highlighter is not able to escape an apostrophe in the comment block and does not. This PR removes it so code this code block is readable.
> docs: fix code highlighting

- packages/nuxt/src/app/composables/payload.ts
https://github.com/nuxt/framework/pull/7809#discussion_r986629100
Two issues:
1. we were not caching payloads
2. we were not respecting baseURL when fetching payloads on client side
> fix(nuxt): use correct cache and add baseURL to payload

- docs/content/1.getting-started/6.data-fetching.md
- docs/content/3.api/1.composables/use-async-data.md
- docs/content/3.api/1.composables/use-fetch.md
- packages/nuxt/src/app/composables/asyncData.ts
- packages/nuxt/src/app/composables/fetch.ts
- test/basic.test.ts
- test/fixtures/basic/pages/useAsyncData/override.vue
resolves #7058, resolves #2973
This adds an `override` option to force override previous async data calls. With `useFetch`, we additionally use `AbortController` (if available in user's target) to cancel the fetch request. Either way, previous async data calls do not affect pending state or resolved data, and any promises returned by previous calls will await the new, overriding call.
> feat(nuxt): refresh override for data fetching composables

- packages/nuxt/src/core/nitro.ts
- packages/schema/src/config/_common.ts
resolves #7626
Allows user to specify `serverDir`.
> feat(schema, nuxt): allow user-configurable `serverDir`

- packages/nuxt/src/core/runtime/nitro/renderer.ts
https://github.com/unjs/nitro/issues/439
This PR adds support for rendering Early Hints in node-based servers. We could also consider locating this elsewhere (e.g. in nitropack: https://github.com/unjs/nitro/issues/439), but the particular hints we want to render are very tied to the specifics of the Nuxt renderer, and not easily portable. Thoughts/suggestions welcome.
I have opened a PR to refactor L104 -> h3 (https://github.com/unjs/h3/pull/184), where it may also be used in userland (e.g. nitro middleware or plugins). If merged, we can refactor this PR to use the same utility.
If you want to test this, build the app and run:
```
curl -D - http://localhost:3000
```
It's only [currently supported](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103#browser_compatibility) in …
> perf(nitro): respond with early hints in node-based environments

- packages/vite/src/client.ts
resolves #7904
As is, `/app` will render `/app.vue`. (The `base` config option is completely ignored - and in fact removed by vite - so no need to do the same ourselves.) A workaround is to inject and remove a random string to _bypass_ matching vite-handled paths.
> fix(vite): prevent overlap between vite assets and app routes

- docs/content/2.guide/2.directory-structure/1.plugins.md
From discussion https://github.com/nuxt/framework/discussions/1260#discussioncomment-3842023
Controlling the order of plugin registration is a common requirement, so I think this should be added as an explicit recommendation in the docs.
Right now, it just says "Plugins are called in order sequentially and before everything else" in a small part of the docs. I don't think it's verbose enough. A section titled something like "Plugin registration order" would be very helpful.
From discussion https://github.com/nuxt/framework/discussions/1260#discussioncomment-3842023
> docs: Add recommendation for controlling plugin registration order.

- docs/nuxt.config.ts
- docs/yarn.lock
- yarn.lock
Add missing url not detected by crawler 🤔
> docs: add app.config route to pre-render

- docs/content/2.guide/4.going-further/10.runtime-config.md
Since the public runtime config moved from `$config` into `$config.public` and the docs only mention use with Composition API it seemed to me at first that runtime config was not available in Options API. Therefore, added a small note so save other people a few minutes.
> docs: clarify access of RuntimeConfig with Options API

- docs/content/2.guide/2.directory-structure/1.pages.md
`https://v3.nuxtjs.org/guide/directory-structure/pages/#router-options`
'RouterOptions' is deprecated so replaced it to 'RouterConfig'
> docs: use `RouterConfig` interface in examples

- examples/advanced/config-extends/package.json
- examples/advanced/jsx/package.json
- examples/advanced/module-extend-pages/package.json
- examples/advanced/testing/package.json
- examples/app-config/package.json
- examples/app/error-handling/package.json
- examples/app/plugins/package.json
- examples/app/teleport/package.json
- examples/auto-imports/components/package.json
- examples/auto-imports/composables/package.json
- examples/composables/use-async-data/package.json
- examples/composables/use-async-data/server/api/hello.ts
- examples/composables/use-async-data/server/api/hello/[slug].ts
- examples/composables/use-cookie/package.json
- examples/composables/use-fetch/package.json
- examples/composables/use-head/package.json
- examples/composables/use-state/package.json
- examples/essentials/hello-world/package.json
- examples/experimental/reactivity-transform/package.json
- examples/experimental/vite-node/package.json
- examples/experimental/wasm/package.json
- examples/other/locale/package.json
- examples/routing/layouts/package.json
- examples/routing/middleware/package.json
- examples/routing/nuxt-link/package.json
- examples/routing/pages/package.json
- examples/routing/universal-router/package.json
- examples/server/routes/package.json
- yarn.lock
https://github.com/nuxt/framework/pull/8159
This bumps the dependencies in the example repos to trigger a refresh on sandboxes, and fixes a small bug.
> chore: bump example dependencies

- packages/nuxt/src/head/module.ts
- packages/nuxt/src/head/runtime/mixin-plugin.ts
https://github.com/nuxt/framework/issues/8166
Rather than globally registering all meta components, this PR uses the component loader to register them. This should reduce initial bundle size by approx 3kB.
> perf(nuxt)!: use component loader to add meta components

- packages/nuxt/src/app/components/nuxt-link.ts
resolves #8171 
Added possible types for target value, in order to provide autocompletion.
> types: include `nuxt-link` target types

- packages/nuxt/src/app/components/nuxt-link.ts
- packages/nuxt/src/app/composables/component.ts
- packages/nuxt/src/pages/runtime/page.ts
- packages/nuxt/src/pages/runtime/utils.ts
This removes `vue-router` dependency from default app (extracted from #8133). Note that there's still a dependency if using `<NuxtLayout>` which needs to be resolved separately.
> perf(nuxt): remove `vue-router` dependency from minimal app

- packages/nuxt/package.json
- packages/nuxt/src/app/plugins/debug.ts
- packages/nuxt/src/core/nitro.ts
- packages/nuxt/src/core/nuxt.ts
- packages/nuxt/src/core/runtime/nitro/plugins/debug.ts
- packages/schema/src/config/_common.ts
- yarn.lock
resolves #3718
This PR adds support for `debug: true` in your nuxt config (disabled by default). At the moment, it prints out hook names and timings on the server, and logs hook arguments as well in the browser.
**Server**
```bash
[nuxt] app:created: 2.109ms
[nuxt] vue:setup: 0.035ms
[nuxt] app:rendered: 0.019ms
[nitro] render:html: 0.048ms
[nitro] render:response: 0.01ms
```
**Client**
> feat(nuxt): add hook debug mode

- docs/content/1.getting-started/6.data-fetching.md
- docs/content/3.api/1.composables/use-async-data.md
- docs/content/3.api/1.composables/use-fetch.md
- packages/nuxt/src/app/composables/asyncData.ts
- test/fixtures/basic/pages/useAsyncData/override.vue
https://github.com/nuxt/framework/pull/7864
This renames `override` to `dedupe` and enables it by default, which should be more the expected behaviour.
If you were relying on the previous behaviour (not re-calling a fetch function if one was already running) then you can update your refresh calls like so:
```diff
- refresh()
+ refresh({ dedupe: false })
```
> feat(nuxt)!: `refresh` to override previous requests by default

- docs/content/2.guide/2.directory-structure/1.pages.md
- packages/nuxt/src/pages/module.ts
resolves #8177 
If the user provides a `router.options` file, the module should be enabled, even without a pages dir.
> fix(nuxt): enable router when `app/router.options.ts` file is present

- packages/nuxt/src/head/runtime/components.ts
Including `<Script>`  in template may possibly open the door to unexpected behaviour. We expect to release `nuxt/scripts` to significantly improve experience for users and module authors, and in preparation, we want to deprecate `<Script>` in favour of directly using `useHead`.
> refactor(nuxt): deprecate `<Script>` component tag in template

- packages/kit/src/internal/cjs.ts
- packages/kit/src/module/install.ts
#8191 
Resolves #8191 - in case of error during module require/import it will be printed to the console in the form of 'Error while requiring module {module_name}: {error}'.
> fix(kit): log module id to the console when import fails

- packages/webpack/src/plugins/dynamic-base.ts
Previously we could end up with invalid JS and the following error:
```bash
[nuxt] [request error] [unhandled] [500] publicAssetsURL__webpack_public_path__ is not defined
```
> fix(webpack): add global to new line

- test/basic.test.ts
Hi :wave: , I just saw `expectNoClientErrors` didn't have the correct path in `/client-only-explicit-import` test
> test(basic): set correct route for /client-only-explicit-import test

- packages/schema/src/config/nitro.ts
https://github.com/nuxt/framework/pull/8251
Sorry! missed this off the last PR. 🙈
> fix(schema): routeRules config

- packages/nuxt/src/app/components/nuxt-link.ts
regression from https://github.com/nuxt/framework/pull/8225 - we should avoid using `router.resolve` on routes we know are external.
> fix(nuxt): avoid preloading external routes

- packages/nuxt/src/core/nitro.ts
- packages/nuxt/src/core/runtime/nitro/renderer.ts
- packages/schema/src/config/experimental.ts
https://github.com/nuxt/framework/pull/8067#issuecomment-1281323715
Just in case of any problems, this allows disabling early hints (https://github.com/nuxt/framework/pull/7893) in the Nuxt server. Also following up with fix in h3 for underlying issue.
> feat(nuxt): allow disabling early hints

- docs/content/2.guide/2.directory-structure/1.server.md
none
`useBody` is now deprecated in favor of `readBody`. See [this response on twitter](https://twitter.com/danielcroe/status/1582131640922701824) with info from @danielroe. This PR updates the Nuxt docs to reflect that change.
> docs: change deprecated `useBody` with `readBody`

- packages/kit/src/build.ts
#8265
An array of plugins is also a valid Vite plugin, we should support that.
> feat(kit): `addVitePlugin` `addWebpackPlugin` support plugin array

- packages/nuxt/src/core/runtime/nitro/error.ts
#7339 
Add headers to `/__nuxt_error` request(ErrorPage request)
> fix(nuxt): pass original request headers to the error page

- packages/test-utils/src/run.ts
https://github.com/nuxt/framework/pull/6764/files
We can now access typed vitest args. This does drop support for <0.20 vitest as well.
> refactor(test-utils)!: update vitest args

- packages/nuxt/src/core/runtime/nitro/error.ts
This casts incoming headers to HeadersInit and resolves lint issue. @pi0 can you confirm that this is valid (ie. that the actual type of these headers is assignable in fetch) or do we need to normalise them instead?
> chore(nuxt): add type for headers

- packages/nuxt/src/pages/runtime/router.options.ts
Improvement over #3851 so we scroll to top when it's the same page but with different params.
Example: Going from `/movies/14` to `/movies/15` should scroll to top.
I am only using params to `/movies` to `/movies?q=test` does not scroll to top.
> fix(nuxt): scroll to top on dynamic routes with different params

- packages/nuxt/src/pages/module.ts
- [feat(nuxt): default router scroll behavior](https://github.com/nuxt/framework/pull/3851)
Router default options were introduced in https://github.com/nuxt/framework/commit/ba3a11800c9cc03ba62decfe935d1844f2be34a9. That's great! But now, custom implementations (via `app/router.options.(js|ts)` won't have an effect. The default options stay at the top of all router option layers.
The source of the error seems to be:
https://github.com/nuxt/framework/blob/ba3a11800c9cc03ba62decfe935d1844f2be34a9/packages/nuxt/src/pages/module.ts#L148
`unshift` adds the default to the beginning, but the router options are `reverse`d anyway later:
https://github.com/nuxt/framework/blob/ba3a11800c9cc03ba62decfe935d1844f2be34a9/packages/nuxt/src/pages/module.ts#L159
> fix(nuxt): router defaults overwrite custom options always

- packages/nuxi/src/commands/analyze.ts
> fix(nuxi): update `nuxi analyze` index handler format

- packages/nuxt/src/pages/runtime/router.options.ts
#8327
Using `JSON.stringify` to compare two route params as suggested by @Atinux. It saves 1.53Kb gzip (~1.6%) bundle size when pages are enabled by not importing `ohash`. Difference is that we _assume_ order of params remains same.
Note: we probably need this library in other places in the future such as `useFetch` if depending on URL again (#6632).
> perf(nuxt): use simple `JSON.stringify` to compare params

- docs/content/1.getting-started/5.transitions.md
Resolves https://github.com/nuxt/framework/issues/8348
> docs: add missing opening `<NuxtLayout>` tag in a code sample

- docs/content/1.getting-started/2.installation.md
- docs/content/3.api/5.commands/typecheck.md
- docs/content/6.bridge/1.overview.md
- docs/content/7.migration/2.configuration.md
- packages/schema/src/config/typescript.ts
> docs: update links for external tools

- docs/content/1.getting-started/5.routing.md
> docs: update for clarity and fix typos

- docs/content/3.api/1.composables/use-fetch.md
- packages/nuxt/src/app/composables/fetch.ts
resolves #5993
This allows passing refs/computed properties as fetch options (e.g. for a param value), and automatically refetching when these values change.
> feat(nuxt): make `useFetch` options reactive

- packages/nuxt/src/pages/runtime/router.options.ts
- [ x] 🐞 Bug fix (a non-breaking change that fixes an issue)
Unless I'm mistaken, the comparison made here should be checking if the routes are `===` and not `!==`. Before, the hash logic wasn't reachable.
> fix(nuxt): routerBehavior comparison for hash block

- packages/nuxt/src/app/plugins/payload.client.ts
Regression of https://github.com/nuxt/framework/pull/8225. We need to ensure we're only loading payloads for internal URLs. (Actually we need to implement something like https://github.com/nuxt/framework/pull/7805 as a proper fix.)
> fix(nuxt): don't load payloads for external urls

- packages/vite/src/vite-node.ts
resolves https://github.com/nuxt/framework/issues/8130, resolves https://github.com/nuxt/framework/issues/7855
We invalidate virtual files in the vite server whenever templates are regenerated. But hitherto we weren't invalidating them in vite-node.
> fix(vite): invalidate virtual modules with `vite-node`

- docs/nuxt.config.ts
hotfix to work around #8414 
I do not believe we are currently using transitions so we probably should disable these anyway. This also serves to seriously reduce a memory leak that we're looking into.
> docs: disable transitions by default

- packages/nuxt/src/app/components/layout.ts
- packages/nuxt/src/pages/module.ts
resolves https://github.com/nuxt/framework/issues/8415
As noted in https://github.com/nuxt/framework/pull/8133, this follows up to remove a `vue-router` dependency from all use of `<NuxtLayout>`.
> fix(nuxt): avoid directly importing `vue-router` inside `<NuxtLayout>`

- docs/content/2.guide/4.going-further/10.runtime-config.md
Closes #8419
Add a sub section about de-/serialization constraints to the runtime config docs.
> docs: add note about runtime config serialization

- docs/content/1.getting-started/2.installation.md
#8407
#8335
Nuxt 3 seems not work on node versions bellow 16. So the documentation need to be updated
> docs: change required node version to be above 16.11

- docs/content/3.api/4.advanced/2.kit.md
- packages/kit/src/template.ts
- packages/nuxt/src/components/module.ts
- packages/nuxt/src/core/app.ts
- packages/nuxt/src/core/builder.ts
- packages/nuxt/src/imports/module.ts
- packages/nuxt/src/pages/module.ts
- packages/schema/src/types/hooks.ts
resolves https://github.com/nuxt/framework/issues/2215
This adds new `updateTemplates` utility that supports using a filter (with `{ filter: template => boolean }`) to selectively update templates.
> feat(kit): add `updateTemplates` utility

- examples/advanced/testing/package.json
- pnpm-lock.yaml
https://github.com/nuxt/framework/issues/7937
The example is not actually runnable as is as there is no test script or test-utils dependency
> chore(examples): add missing dependency and script for testing example

- packages/test-utils/src/server.ts
resolves #8261
We override `PORT` but also need to override `NITRO_PORT` if this is set by the user in an `.env` file.
> fix(test-utils): override `NITRO_PORT` as well

- docs/content/1.getting-started/5.seo-meta.md
- docs/content/1.getting-started/6.data-fetching.md
- docs/content/1.getting-started/7.state-management.md
- docs/content/1.getting-started/8.error-handling.md
- docs/content/2.guide/2.directory-structure/1.components.md
- docs/content/2.guide/2.directory-structure/1.composables.md
- docs/content/2.guide/2.directory-structure/1.layouts.md
- docs/content/2.guide/2.directory-structure/1.middleware.md
- docs/content/2.guide/2.directory-structure/1.pages.md
- docs/content/2.guide/2.directory-structure/1.plugins.md
- docs/content/3.api/1.composables/use-cookie.md
- docs/content/3.api/1.composables/use-fetch.md
- docs/content/3.api/2.components/4.nuxt-link.md
- docs/content/3.api/2.components/8.teleports.md
resolves nuxt/content#1635
`LinkExample` is a block component since it renders block tags like `div`. We can't use it as an inline component. 
Using a block component as inline results hydration issue
> docs: use `LinkExample` as block component

- packages/nuxt/src/app/composables/router.ts
resolves https://github.com/nuxt/framework/issues/8247
This PR adds warnings in dev mode when `setPageLayout` is used in a location where it will cause a hydration mismatch.
> feat(nuxt): add dev warnings when `setPageLayout` is used incorrectly

- packages/nuxt/src/core/runtime/nitro/error.ts
follow-up to https://github.com/nuxt/framework/pull/7340, resolves https://github.com/nuxt/framework/issues/7469
This allows responding to an error within `error.vue` with more than just HTML and the original error code, such as modifying the code or redirecting to a different page.
> fix(nuxt): allow responding with custom headers from `error.vue`

- packages/schema/src/config/experimental.ts
https://github.com/nuxt/framework/issues/8306
> docs: add note about early hints and nginx

- packages/schema/src/config/experimental.ts
In view of the fact that Early Hints have quite minimal support, I think it's worth disabling these by default, for now at least.
> fix(schema): disable early hints by default

- docs/content/1.getting-started/5.routing.md
- docs/content/1.getting-started/5.transitions.md
- docs/content/2.guide/2.directory-structure/1.components.md
- docs/content/3.api/3.utils/define-page-meta.md
- docs/content/7.migration/7.component-options.md
> docs: update stability edge banners

- packages/kit/src/resolve.ts
Currently if nuxt instance is not present when calling `resolvePath`, we will throw an error. We already check for existence, so this was likely not intended.
> fix(kit): don't require nuxt when resolving path

- docs/scripts/gen-docs.ts
resolves https://github.com/nuxt/framework/issues/8534
This generates docs for new unversioned schema
> docs: generate docs for unversioned schema

- packages/nuxt/src/pages/module.ts
resolves https://github.com/nuxt/framework/issues/8526
It seems that we could end up with multiple versions of `vue-router` when optimising dependencies, and therefore have mismatching route symbols.
This PR ensures that when using the pages integration we process the router first.
> fix(nuxt): add `vue-router` to optimized deps

- docs/content/1.getting-started/5.transitions.md
wording change in transitions page.
> docs: fix transition wording to include layouts

- packages/vite/src/client.ts
Fix #8522
Vite plugin might register their custom server middleware to the Vite dev server, for example:
- [vite-plugin-inspect](https://github.com/antfu/vite-plugin-inspect#install)
- [unocss/inspector](https://github.com/unocss/unocss/tree/main/packages/inspector)
#7989 introduced a regression that bypassed all custom vite middleware. This PR fixes it by checking the registered routes to Vite middleware and forwarding them as-is. This also removes the hard-code `/__nuxt_vite_node__` handling.
> fix(vite): handle all vite middleware routes

- packages/vite/src/plugins/composable-keys.ts
resolves https://github.com/nuxt/framework/issues/8499
We were previously not confirming whether there was a trailing comma before appending our own.
> fix(nuxt): check before appending comma in composable keys

- packages/kit/src/nitro.ts
https://github.com/Baroshem/nuxt-security/issues/42
This normalizes paths to handlers passed in via `addServerHandler` and `addDevServerHandler`.
> fix(kit): normalize nitro handler paths

- packages/schema/src/config/typescript.ts
> docs: add information about type checking to `typescript.typeCheck` config

- docs/content/2.guide/2.directory-structure/1.pages.md
- packages/nuxt/src/pages/runtime/composables.ts
- packages/nuxt/src/pages/utils.ts
resolves https://github.com/nuxt/framework/issues/8619
This allows setting custom name/path for a route via `definePageMeta`. I've also alphabetised this section of the docs.
> feat(nuxt): allow setting `name` and `path` for a route in `definePageMeta`

- packages/nuxt/src/pages/module.ts
https://github.com/nuxt/framework/issues/5483#issuecomment-1157960000
With pages module, we add routes to the default routes values. But if the user doesn't have a `~/pages/index.vue` file we can safely skip processing the default `/` route for prerender.routes.
> fix(nuxt): don't force prerender `/` if user doesn't have that route

- packages/kit/src/nitro.ts
This adds a helper utility for adding a nitro plugin.
> feat(kit): add `addServerPlugin` utility

- packages/nuxt/src/core/runtime/nitro/renderer.ts
- packages/vite/src/plugins/ssr-styles.ts
- packages/vite/src/server.ts
- test/basic.test.ts
https://github.com/nuxt/framework/issues/7619
This reverts https://github.com/nuxt/framework/pull/7386. Rather than attempt to lazy load the entry CSS, it's safer to rely on browser fetching it in the previous (blocking) manner. We still experience the benefit of inlining SFC styles and we can reconsider entry CSS inlining in future.
> fix(nuxt): do not inline global styles in HTML response

- packages/schema/src/config/typescript.ts
resolves #8631
This enables TypeScript's strict mode by default for users who are using TS. This is a better default and best practice.
Users can disable this if they prefer.
```js
typescript: {
strict: false
}
})
```
> fix(schema)!: use strict typescript mode by default

- test/fixtures/basic/components/Nested/SugarCounter.vue
- test/fixtures/basic/nuxt.config.ts
- test/fixtures/basic/pages/client-only-components.vue
- test/fixtures/basic/pages/useAsyncData/refresh.vue
- test/fixtures/basic/types.ts
#8667
This updates our test fixture to respect the new default `strict` mode for TS.
> test: update type test for strict mode

- docs/content/3.api/4.advanced/1.hooks.md
- docs/content/3.api/4.advanced/2.kit.md
- packages/kit/src/nitro.ts
- packages/nuxt/src/core/nitro.ts
- packages/schema/src/types/hooks.ts
- Add `prerender:routes({ routes })` hook proxied from nitro
- Add `addPrerenderRoutes(routes: string | string[])` kit utility for extending prerender routes
> feat(kit, nuxt): support `prerender:routes` and `addPrerenderRoutes`

- packages/nuxt/src/core/runtime/nitro/renderer.ts
Fixes security issues can be caused by directly rendering `/__nuxt_error` route. Only it should be rendered with direct ssr call.
> fix(nuxt): disallow directly rendering error page

- packages/nuxt/src/core/templates.ts
#5411
Since `paths.mjs` and `app.config.mjs` templates are directly written to `.nuxt` directory, their implicit (defu and ufo) dependencies need to be already resolved. This almost fixes pnpm support!
> fix(nuxt): resolve ids to support pnpm

- packages/schema/src/config/vite.ts
Enable vite fs restriction by default(https://vitejs.dev/config/server-options.html#server-fs-strict). 
This ensures avoiding access to fs using `/_nuxt/@fs/` url.
This PR might introduce regressions with modules trying to access outside of `rootDir`, `srcDir`, `buildDir`, `workspaceDir` or either of `modulesDir` (modules are automatically added). In this case, can be manually added using `nuxt.options.vite.server.fs.allow[]`
```ts
vite: {
server: {
fs: {
allow: [
'/xyz'
]
}
}
}
})
```
> fix(vite): enable fs strict mode

- packages/nuxt/src/app/composables/payload.ts
Use `URL` parser to extract pathname from URL for internal `_getPayloadURL` utility and ensure input does not contain hostname or search params. 
Previously an invalid URL like `loadPayload('/\\example.com')` could be passed.
Credits to @ohb00 for discovering this.
> fix(nuxt): ensure payload url has no protocol

- packages/nuxt/src/pages/runtime/router.options.ts
Resolves a regression from #8463
And resolves #8699
Learn more in the comments from #8327
Regression since we need to detect if there are global transitions activated in order to listen to `page:transition:finish` hook. Otherwise it's never called and the scrollBehavior is inactive.
Also, since the value of the next and previous page can be `undefined`, using `!== false` was also a wrong usage.
> fix(nuxt): check if global transitions are activated for scroll behavior

- packages/nuxt/src/core/runtime/nitro/renderer.ts
No issue.
Tried to use Nitro's `render:html` hook in a server plugin and noticed `bodyPrepend` was actually `bodyPreprend`.
> refactor(nuxt)!: fix typo for `NuxtRenderHTMLContext.bodyPrepend`

- examples/experimental/wasm/server/api/sum.ts
> docs: use update import for `defineLazyEventHandler`

- packages/nuxt/src/app/composables/cookie.ts
- test/fixtures/basic/types.ts
remake of https://github.com/nuxt/framework/pull/8754
> fix(nuxt): allow cookies to be set to `null` to unset them

- packages/nuxt/src/pages/module.ts
Where users had only a catchall but no other pages, we weren't generating anything. In this case we can almost certainly render the base URL that would otherwise be caught by the catchall. (I've also included optional params, e.g. `~/pages/[[something]].vue`.)
> fix(nuxt): add catchall paths to prerender list

- packages/nuxt/src/app/composables/ssr.ts
https://github.com/nuxt/framework/discussions/8803
Makes headers case-insensitive.
Would be good to double-check if headers always come lower-cased from the server. If no, maybe add a transform step there too.
https://github.com/unjs/h3/blob/6beee463d0e95207480acfd21badc2c2fa46f6c3/src/utils/request.ts#L58-L65 does not handle casing. Should I create a PR or an issue there too?
> fix(ssr): ensure useRequestHeaders are case-insensitive

- packages/nuxt/src/pages/runtime/router.ts
- packages/nuxt/src/pages/utils.ts
- packages/nuxt/test/pages.test.ts
resolves https://github.com/nuxt/framework/issues/6895
This PR removes support for the `404.vue` shorthand (mapping to a catchall with 404 status code). This was confusing when users also had a manual catchall, such as `[...slug].vue` (as the latter would never be hit). And it also separated out the 404 error page from `error.vue` which was used to render every other error page.
1. Rename your `404.vue` page to `[...slug].vue`.
2. Manually set the response status within that page.
```diff
<script setup>
+   setResponseStatus(404)
</script>
```
> refactor(nuxt)!: remove support for `404.vue` shorthand

- packages/nuxt/src/pages/runtime/router.ts
resolves https://github.com/nuxt/framework/issues/8816
This ensures that we do not go on to render the page if we are going to be throwing an error or returning a redirect.
> fix(nuxt): do not render page if we are throwing error

- docs/content/3.api/1.composables/use-request-headers.md
Added example for `useRequestHeaders` composable
> docs(api): add `useRequestHeaders` composable example

- packages/nuxt/src/pages/runtime/router.options.ts
resolves #8732
This swalls any issues with invalid query selectors which otherwise would completely crash a page.
Note that `vue-router` will rightly still warn:
```
[Vue Router warn]: The selector "#accesstoken=ey.4" is invalid. If you are using an id selector, make sure to escape it. You can find more information about escaping characters in selectors at https://mathiasbynens.be/notes/css-escapes or use CSS.escape (https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape).
```
> fix(nuxt): swallow issues with query selectors

- packages/nuxt/src/app/components/nuxt-root.vue
- packages/nuxt/src/app/entry.ts
This is a micro optimisation. We likely don't need access to `<App>` outside of `<NuxtRoot>` and it feels like having it in the vue component registry isn't necessary. But I may have missed something here - wdyt @antfu?
> refactor(nuxt): explicitly import app in nuxt-root

- packages/nuxi/src/cli.ts
This PR uses `consola.wrapAll` instead of `consola.wrapConsole` in order to intercept all console outputs. Code running in SSR worker, writes to `stdout` and `stderr` instead of (main process) `console` object. 
Now, it is possible to use something like ``console.log('Hello `123`')`` from a Vue SFC to have beautiful output formatted by console:
This way we can intercept console output and also improve DX for some known issues:
- Hide 404 SSR warnings thrown by vue-router `[Vue Router warn]: No match found for location with path'`
- Hide vite missing sourcemap warns originating from `node_modules`
It is possible to also use vite's custom logger (probably other custom loggers including one for SSR) but i assume it is easier to manage console logging and filtering from one place. We made …
> feat(nuxi): wrap and normalize all console outputs

- packages/nuxt/src/app/composables/fetch.ts
- test/basic.test.ts
resolves https://github.com/nuxt/framework/issues/8650
It's tricky to use `refreshNuxtData` to refresh a `useFetch` with an explicit key as there is currently an undocumented `$f` prefix added. I think we can choose only to add this prefix with an auto-key, meaning that users can manually invalidate the key more easily.
> fix(nuxt)!: only add `$f` fetch prefix to auto-keys

- packages/test-utils/src/nuxt.ts
N/A
When using `test-utils` with a project that has `.mjs` config file and no `pages` folder (ex: doc-driven), user'd have to explicitly set `options.rootDir` to make vitest works, otherwise it'll throw error.
> fix(test-utils): detect project root using `nuxt.config` with `.mjs` and `.cjs` extensions

- packages/nuxi/src/utils/prepare.ts
resolves https://github.com/nuxt/framework/issues/8847
`.nuxt/dist`, `.output`, `.netlify`, etc. aren't caught because they start with `.`, but the 'dist' folder does get caught by TS when type-checking a project. Excluding it should improve type-checking performance, and also resolve the linked issue.
> fix(nuxi): exclude `dist` from type checking

- docs/content/1.getting-started/6.data-fetching.md
resolves #4925, resolves https://github.com/nuxt/framework/issues/5837
The example would fail as the nuxt instance would not be available.
> docs: get event before running async function

- docs/content/3.api/1.composables/use-hydration.md
Added API documentation for `useHydration` composable
> docs(api): add `useHydration` composable

- docs/content/3.api/1.composables/use-fetch.md
Update useFetch with description and example of query option, which is inherited from ohmyfetch, resolves #8708
resolves #8708
Update useFetch with description and example of query option, which is inherited from ohmyfetch. So far this is not documented. resolves #8708
> docs: add `query` option with example for `useFetch`

- packages/nuxt/src/pages/page-meta.ts
- test/fixtures/basic/pages/index.vue
- test/fixtures/basic/some-exports.ts
resolves https://github.com/nuxt/framework/issues/8676
This slightly expands the detection of imports to include standalone identifiers and not just functions.
> fix(nuxt): detect non-functional imports within page meta

- packages/nuxt/src/app/entry.ts
- packages/nuxt/src/core/nitro.ts
- packages/nuxt/src/core/runtime/nitro/renderer.ts
- packages/schema/src/config/app.ts
Resolves #8099 Resolves #8603
This PR allows customizing root element id and tag:
```ts
app: {
rootId: 'app',
rootTag: 'main'
}
})
```
Renders Nuxt app into `<main id="app">`
> feat: allow customizing root id and tag

- packages/nuxt/src/core/runtime/nitro/renderer.ts
Resolves #8706
Nitro Renderer is expected always to return a response or throw an error.
> fix(nuxt): preserve render errors

- docs/content/3.api/1.composables/use-async-data.md
- docs/content/3.api/1.composables/use-fetch.md
- packages/nuxt/src/app/composables/asyncData.ts
- packages/nuxt/src/app/composables/fetch.ts
- packages/nuxt/src/app/nuxt.ts
- packages/nuxt/src/app/plugins/payload.client.ts
Race condition issue in #3985 seems to be resolved. Removing initialCache option and only use utility to preserve payload data **while hydrating**.
BREAKING CHANGE: Payload cache won't be used when doing client-side navigation back to same page and fresh data will be fetched.
> fix(nuxt)!: remove `initialCache` option

- packages/nuxt/src/core/runtime/nitro/error.ts
Resolves #8886.
Resolves #8886 by prepending `app.baseURL` when fetching the error page during SSR. This is needed because the `localFetch` method used has no default `baseURL` value.
> fix(nuxt): use `app.baseURL` when fetching error page on server

- docs/content/3.api/1.composables/on-before-route-leave.md
- docs/content/3.api/1.composables/on-before-route-update.md
Quick update for new router composables to point back to `vue-router` docs.
> docs: add stub documentation for router composables

- docs/content/2.guide/2.directory-structure/1.server.md
The tls option isn't mentioned within the docs, why one has to dig deep to find out how to use server storage with tls.
> docs: add tls option to server storage example

- docs/content/2.guide/2.directory-structure/1.server.md
Added one missing `,` and removed one unnecessary comma in the Redis example, causing at least syntax highlighting not to work. Now it is also copy&pastable again.
> docs: fix syntax errors in server storage example

- docs/content/3.api/5.commands/add.md
This PR add spaces in long inline code example to avoid breaking mobile layout.
> docs(api): add spaces to avoid breaking mobile layout

- docs/content/3.api/1.composables/use-nuxt-app.md
Noticed a typo in line:39 under the under the hook section
Changed `avialble` to `available`
> docs: typo in `available`

- packages/nuxt/src/app/components/client-only.mjs
resolve https://github.com/nuxt/framework/issues/8920
Hi :wave:, this PR remove the attributes inheritance from `<ClientOnly>`. It was causing a `[Vue warn]: Extraneous non-props attributes (class) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.` warn log in console in dev
> fix(nuxt): avoid passing attrs to default slot for ClientOnly

- packages/nuxt/src/pages/runtime/composables.ts
This addresses #3175 - a bit more detail on having to be in a page
> docs: add a bit more detail in the `definePageMeta` warning to specify it needs to be in a page

- docs/content/1.getting-started/5.seo-meta.md
https://ogp.me/ suggests to use the attribute `property` instead of `name` when defining OpenGraph metadata.
> docs: match the open graph protocol markup

- packages/vite/src/vite.ts
Reported by @Atinux 
This allows extending from local dirs without explicitly adding to `vite.fs.allowlist` in `nuxt.config`
> fix(vite): add extend layers to `fs.allow`

- packages/nuxt/src/core/nitro.ts
If we are using typescript files within a layer, esbuild doesn't process this and the nitro build will fail. This PR exempts layers from the node_modules exclude, but otherwise preserves it.
> fix(nuxt): include layers in esbuild transform

- packages/kit/src/module/install.ts
https://github.com/nuxt/content/issues/1665
If we add external module in `nuxt.config.ts`, that auto add to build transpile. so `installModule ` need add external module name to build transpile.
> fix(kit): add manually installed module to transpile

- packages/nuxi/src/commands/build.ts
- packages/schema/src/config/experimental.ts
- test/fixtures/basic/nuxt.config.ts
Resolves #8914
Only enable full-static support with payload extraction when using `nuxi generate`. It will display a warning always with how to opting out.
With this PR landing for v3, payload extraction support for `nuxi build` will be **always opt-in**.
> fix(nuxt)!: enable payload extraction only for `nuxi generate`

- docs/content/1.docs/1.getting-started/5.transitions.md
- docs/content/1.docs/3.api/2.components/5.nuxt-loading-indicator.md
#8493 #8753 
As I discussed with @danielroe on Discord. I added a warning for the bugs on page transitions & nuxt loading indicator.
> docs: add warning about `definePageMeta` issues with transitions and `NuxtLoadingIndicator`

- packages/nuxt/src/app/composables/asyncData.ts
- test/fixtures/basic/server/api/union.ts
- test/fixtures/basic/types.ts
Resolves #6910.
Resolves #6910 by updating the `KeysOf` type so that a union type argument yields all keys of all types in the union. This ensures that calling `useAsyncData` with a union type argument will result in the returned `data` value having the same union type instead of a type consisting of only the members that are common to all types in the union.
> fix(nuxt): allow union type arguments for `useAsyncData`

- packages/schema/src/config/postcss.ts
- packages/webpack/src/utils/postcss.ts
resolves https://github.com/nuxt/framework/issues/5368
> fix: remove `postcss.config` from schema

- packages/nuxt/src/core/plugins/dev-only.ts
- packages/nuxt/src/core/plugins/tree-shake.ts
- packages/nuxt/src/core/plugins/unctx.ts
resolves #9200
I've fixed typo in 3 files where the `transfrom` was written instead of `transform`.
> refactor(nuxt): fix typo in internal rollup plugin names

- docs/content/1.docs/1.getting-started/6.data-fetching.md
Resolves #9275
There was a missing space between two sentences in the doc, added it to make the documentation more consistent & clean. Minor mistakes can be bad for first impressions to new users, hence why I fixed it.
> docs: add missing space

- docs/content/1.docs/2.guide/2.directory-structure/1.components.md
resolves https://github.com/nuxt/framework/issues/9185
hi :wave: This PR warns about the `onMounted` hooks on .client components.
Since the `createClientOnly` only render the component after being mounted, we don't have any access to the rendered template defined on the .vue file before the nextTick
> docs: add warning about `.client` onMounted hook

- docs/content/1.docs/3.api/3.utils/define-page-meta.md
The main example showed the usage of the `title` parameter which is not part of the `definePageMeta` interface. The example should reflect real values since in the current example it easy to confuse it with `useHead` which must actually be used to set the page title using the `title` parameter.
> docs: use `layout` in example of `definePageMeta`

- packages/schema/src/config/adhoc.ts
#9345 
Specify that `imports.dirs` will not override the default directories (~/composables, ~/utils) but rather be **appended** to them. This change is required in order to avoid confusion.
> docs(schema): add example and description for `imports.dirs`

- packages/nuxt/src/app/components/layout.ts
- test/basic.test.ts
- test/fixtures/basic/layouts/with-props.vue
- test/fixtures/basic/pages/layouts/with-props.vue
resolves #9253
This PR allows passing props directly to layouts via the `<NuxtLayout>` component.
> fix(nuxt): allow layouts to receive custom props

- docs/content/1.docs/1.getting-started/2.installation.md
With this it should be more obvious for the user that instead of `nuxt-app` the actual project name is meant. 
This was the case and example also in the nuxt 2 docs: https://nuxtjs.org/docs/get-started/installation/
> docs: use placeholder name in the installation step

- packages/test-utils/src/nuxt.ts
- packages/test-utils/src/runtime/global-setup.ts
close #9434
`kit.logger.level` was overriding globally to hide all output including Vitest
> fix(test-utils): do not hide Vitest output

- packages/nuxt/src/app/composables/cookie.ts
- test/fixtures/basic/types.ts
https://github.com/nuxt/framework/pull/8769#issuecomment-1322207665
This reverts the previous change in linked PR, allowing user to choose whether or not the cookie should be nullable by providing a generic type. This is a type-breaking change and should likely occur in a minor release rather than a major one.
If you were relying on the default nullable behaviour, you can pass a generic instead:
```diff
- useCookie('test', () => 'something').value = null
+ useCookie<string | null>('test', () => 'something').value = null
```
> fix(nuxt): `useCookie` with defaults should return non-null value

- packages/nuxt/src/app/components/nuxt-link.ts
- packages/nuxt/src/app/nuxt.ts
- packages/vite/src/client.ts
Two related performance bugs:
1. When loading a page with links, these pages are prefetched immediately, which will delay the DOM Content Loaded event. This PR defers initialising observer until component is mounted, and additionally waits until the entire app is hydrated.
2. If we are rendering a page with inlined styles, vite will immediately inject a preload for the very same CSS chunk that is inlined; we can use control of the chunk preloader to skip loading those chunks.
> fix(nuxt): defer render-blocking prefetches until after load

- docs/content/1.docs/1.getting-started/3.configuration.md
Vite was the only option that wasn't in monospace, but instead a normal link.
> docs: make `vite` monospace too

- packages/nuxt/src/app/plugins/cross-origin-prefetch.client.ts
Previously new crossorigin prefetches were not being injected into the head as it was not reactive outside a vue component. This PR fixes that by manually calling `patch` when necessary.
> fix(nuxt): update head entry when speculation rules are updated

- packages/nuxt/src/core/app.ts
Resolves https://github.com/nuxt/framework/issues/9520
Related: https://github.com/nuxt/framework/issues/3222
Adds layer/`extends` support for `error.vue`
> feat(nuxt): support for extending error.vue in layers

- packages/nuxt/src/core/app.ts
Follow-up of https://github.com/nuxt/framework/pull/9521
Use `pathe.join` for app components too
> refactor(nuxt): use `pathe.join` for layer lookup

- docs/content/1.docs/1.getting-started/11.testing.md
- docs/content/1.docs/2.guide/3.going-further/3.modules.md
resolves #9542
With the release of nuxt 3, we no longer need to recommend installing an edge version.
> docs: recommend to install non-dge version of `@nuxt/test-utils`

- packages/kit/src/ignore.ts
resolves https://github.com/nuxt/framework/issues/8634
This PR adds support for applying `.nuxtignore` in relation to the root directory of each layer.
> fix(kit): support applying `.nuxtignore` within external layers

- packages/nuxt/src/core/runtime/nitro/renderer.ts
A few missing places where we should update to `event.node` rather than accessing `res`/`req` directly off the event
> fix(nuxt): remove deprecated `req`/`res` access

- docs/content/1.docs/2.guide/1.concepts/3.rendering.md
- [ x] 📖 Documentation (updates to the documentation or readme)
The page at https://nuxt.com/docs/guide/concepts/rendering shows both light and dark versions of the images. I don't know how to conditionally render an image from within markdown(?), but this PR at least hides the light version of the image when dark mode is set by simply adding a tailwind class of `dark:hidden`.
N.B. I'm not sure what the current classes of `.light-img` and `.dark-img` currently do, if anything?
- [ x] I have updated the documentation accordingly.
> docs(rendering): hide light image in dark mode

- packages/nuxt/src/app/composables/asyncData.ts
- packages/nuxt/src/app/entry.ts
- test/basic.test.ts
- test/fixtures/basic/plugins/async-plugin.ts
resolves #9315 
Added a check for the presence of currentInstance before calling the vue hook onServerPrefetch
Fix vue warn when calling useFetch in serverPlugin
[Vue warn]: onServerPrefetch is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
Resolves #9315
> fix(nuxt): await plugin asyncdata promises in nuxt hook

- packages/schema/package.json
- pnpm-lock.yaml
fix the phantom dependency issue
relate #5411
Add `hookable`. It's only added in `nuxt` package. I only need `defineNuxtModule` from `@nuxt/kit`. Then `hookable` pkg is missing.
> fix(schema): add hookable dependency

- packages/vite/src/client.ts
resolves https://github.com/nuxt/framework/issues/9205, resolves https://github.com/nuxt/framework/issues/9467, resolves https://github.com/nuxt/framework/issues/9107
This PR avoids modifying the URL for vite middleware injected prior to `viteTransformMiddleware`, instead injecting another middleware to make the modification within the vite stack.
The underlying mechanism of skipping the vite transform hasn't changed, just the time of making the change.
cc: @patak-dev
> fix(vite): skip _only_ vite transform middleware

- packages/nuxt/src/pages/utils.ts
resolves https://github.com/nuxt/framework/issues/9653
Absolute file paths were being embedded in the build by the pages integration in two places - in the meta variable as well as in the `.file` attribute (which is not used by `vue-router` as far as I can tell). We can safely relativise the former and remove the latter.
> fix(nuxt): remove absolute paths from routes objects

- docs/content/1.docs/2.guide/2.directory-structure/1.middleware.md
Indicate that argument 'options' of 'navigateTo' function is optional
> docs: indicate `navigateTo` options are optional

- packages/nuxt/src/core/plugins/dev-only.ts
- test/fixtures/basic/pages/index.vue
resolves #9676
This updates the dev-only regexp to be less greedy, so it won't accidentally swallow up intervening content between dev-only components.
> fix(nuxt): make dev-only regexp less greedy

- docs/content/1.docs/2.guide/1.concepts/1.auto-imports.md
N/A
The `utils` directory is missing in the list of directory-based auto-imports, so I added it.
> docs: list utils as auto-import directory

- packages/vite/src/client.ts
As the app getting big, the building on the client does not show any state and is stuck on this line, which could be confusing. We have `Building server...` indicator, I think we should do the same for client build.
> refactor(vite): show log when client build is starting

- docs/content/1.docs/3.api/1.composables/use-cookie.md
- packages/nuxt/src/app/composables/cookie.ts
`useCookie` only change when `.value` update. we can use deep flag in watch and track all change.
> feat(nuxt): deep watch `useCookie` ref value by default

- packages/nuxt/src/core/nitro.ts
- packages/schema/src/config/vite.ts
- packages/vite/src/client.ts
- packages/vite/src/server.ts
Change `vite.logLevel`'s default to `info` on build. And restore consola wrap on building to avoid breaking the layout of assets output (see nitro output for example)
Before:
After:
> feat(vite): display production build stats

- docs/content/1.docs/1.getting-started/2.installation.md
1, Add `--shamefully-hoist` for `pnpm install`.
2, Omit `run` for pnpm script.
1, For new project, `--shamefully-hoist` is more comfortable than `.npmrc` with `shamefully-hoist=true`. And `#` does not affect the copying of the entire shell run.
2, In terms of reading order, --shamefullu-hoist is written after the shell command, and although alert is visually obvious, there is a chance that it will be missed.
3, Since yarn omits run, pnpm can actually omit run as well😜.
> docs(getting-started): improve usage of `pnpm`

- docs/content/0.index.md
Fixed the typo in the name Github on the main page, it should be GitHub in respect to the conventions established by GitHub.
> docs(index): fix typo in 'GitHub'

- docs/content/1.docs/2.guide/2.directory-structure/2.nuxtignore.md
I found a typo in [.nuxtignore docs page](https://nuxt.com/docs/guide/directory-structure/nuxtignore).
Difference of `layout` and `layouts` is confusing because this is related to directory name, I think.
> docs: fix `layouts` typo in nuxtignore page

- docs/content/1.docs/1.getting-started/3.configuration.md
url for prettier.io was pointing to stylelint.io
now it points to prettier.io
> docs: fix url for prettier.io pointing to stylelint.io

- packages/nuxt/src/app/components/nuxt-loading-indicator.ts
Previously, animation will always trigger despite throttle being declared due to `isLoading.value` being `true` outside of the `setTimeout` function. Now the loading indicator only shows up if the page takes more than the configured throttle time, which is the intended purpose of it. Default is `200ms`. Setting it to 0 will always trigger the loading animation.
> fix(nuxt): set is loading state for  `<NuxtLoadingIndicator>` after throttle

- examples/advanced/config-extends/base/nuxt.config.ts
- examples/advanced/config-extends/nuxt.config.ts
The`runtimeConfig` part of the example doesn't work.
Deprecated `publicRuntimeConfig` prop isn't supported since [v3.0.0-rc.14](https://github.com/nuxt/framework/releases/tag/v3.0.0-rc.14) (due to #9029).
Changing `publicRuntimeConfig` to `runtimeConfig.public` in **nuxt.config.ts**.
> docs(examples): fix `runtimeConfig` usage in config-extends example

- docs/content/1.docs/1.getting-started/3.configuration.md
Resolve #9914 
The current [documentation](https://nuxt.com/docs/getting-started/configuration#app-configuration) says that the `app.config.ts` is in the root directory, but in reality it is the source directory. I slightly reworded the sentence to clarify this.
I also removed a link to a non-existing page in the following section (hope this is not too unrelated).
> docs(configuration): clarify the location of `app.config.ts` in the source directory

- packages/nuxi/src/commands/init.ts
https://github.com/nuxt/framework/issues/1408#issuecomment-1367535701
- ~[ ] 📖 Documentation (updates to the documentation or readme)~
- ~[ ] 👌 Enhancement (improving an existing functionality like performance)~
- ~[ ] ✨ New feature (a non-breaking change that adds functionality)~
- ~[ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)~
Previously not supplying a value with the `--template` flag results in the following error.
This PR aims at showing an error message and exiting with a code of `1` in this scenario.
- ~[ ] I have updated the documentation accordingly.~
> fix(nuxi): show an error if no value is supplied for the `--template` flag

- docs/content/1.docs/2.guide/2.directory-structure/0.output.md
The link to deployment-section may not have been updated, and it is now not jumping correctly.
> docs(guide): fix the link to deploy in `guide/.output`

- docs/content/1.docs/3.api/5.commands/generate.md
- packages/nuxi/src/commands/generate.ts
resolve https://github.com/nuxt/framework/issues/9966 
Hi :wave: , this PR adds the `--dotenv` arg to the documentation for the generate command. I think the `generate` command already support the `--dotenv` arg since it pass all its arguments to the `build` command.
> docs: update `generate` doc to include `--dotenv`

- packages/schema/src/config/generate.ts
https://github.com/nuxt/framework/issues/4919
We still have some information from Nuxt 2 docs in this section of the documentation. We can also consider removing this top-level key entirely (cc: @pi0) but as a first step we should remove the misleading docs.
> docs: remove nuxt 2 information from `generate` schema

- packages/vite/src/vite.ts
Related:
- https://github.com/unjs/nitro/pull/817
- https://github.com/unjs/nitro/pull/819
> fix(vite): defer to nitro to copy public dir

- packages/nuxt/src/app/components/nuxt-link.ts
This PR only improves internal type definitions of `<NuxtLink>`. This may make it easier to maintain in the future.
Before
After
> refactor: improve internal type definitions of `<NuxtLink>`

- packages/nuxt/build.config.ts
- packages/nuxt/src/components/loader.ts
`server-component` in the `runtime` dir was not being generated/included in the final bundle
> fix(nuxt): include components `runtime` dir in build output

- packages/nuxt/src/core/nitro.ts
https://github.com/unjs/nitro/issues/836
This automatically adds any string-based packages in `build.transpile` to be inlined in nitro as well, to improve DX for module authors and users.
> fix(nuxt): add `build.transpile` strings to nitro inline list

- packages/nuxt/src/app/config.ts
No linked issue, but a reproduction: https://stackblitz.com/edit/github-mgmeto?file=app.config.ts,app.vue
Tested locally in playground with my fix and works.
> fix(nuxt): support deep assign on empty object for app config

- packages/nuxt/src/imports/module.ts
- test/basic.test.ts
- test/fixtures/basic/composables/override-base.ts
- test/fixtures/basic/extends/bar/composables/base.ts
- test/fixtures/basic/pages/extends.vue
resolves https://github.com/nuxt/framework/issues/9871
This PR adds a priority to composables scanned from directories so that higher priority layers can override lower priority layers.
> fix(nuxt): allow overriding lower layer composables

- packages/nuxt/src/head/runtime/components.ts
#9118 
resolve #9118 - Add an `Object` to html and body class prop to solve a type error.
> fix(nuxt): update `class` prop type for head components

- packages/nuxt/src/app/components/layout.ts
- packages/nuxt/src/app/components/utils.ts
- packages/nuxt/src/pages/runtime/page.ts
resolves https://github.com/nuxt/framework/issues/9843
This names some of the anonymous components we use in our tree for better UX.
> fix(nuxt): name anonymous components in render tree

- docs/content/1.docs/3.api/4.advanced/1.hooks.md
The link point to the wrong line, probably after a change in the past.
> docs: update hooks source line number

- packages/vite/src/client.ts
- test/basic.test.ts
- test/fixtures/basic/nuxt.config.ts
> fix(vite): add additional before skipping vite transform

- docs/content/1.docs/2.guide/2.directory-structure/1.server.md
#4235
In the latest release of `h3`,  we should use `eventHandler` to wrap our handlers.
https://github.com/unjs/h3/releases/tag/v0.8.0
We should return a handler function, not a `Router`, use `router.handler` or `useBase` can fix it.
In this case, I think it should be `useBase('/api', router.handler)`
> docs: update nested router example

- packages/nuxt/src/components/tree-shake.ts
resolve https://github.com/nuxt/nuxt.js/issues/15396
Hi :wave: currently the tree-shake module does not treeshake .client components due to nuxt/framework#7412 that adds `ServerPlaceholder` as .client components server side component.
This PR fix the RegexpMap of the treeshake module by adding a condition to verify that `other.filePath` is not the path to `ServerPlaceholder`. 
btw this can be closed if nuxt/framework#8713 pass
> fix(nuxt): treeshake client-only components with placeholders
